### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by gj23** [platformio/platformio-atom-ide#1498] opened 2018-02-08 12:05 UTC
Error: Can not find Python Interpreter
    at PlatformIOCoreStage._callee8$ (C:\Users\whs\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:2478:23)
    at tryCatch (C:\Users\whs\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:832:40)
    at Generator.invoke [as _invoke] (C:\Users\whs\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1066:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\whs\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:884:21)
    at step (C:\Users\whs\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1839:191)
    at C:\Users\whs\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1839:361
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by gj23** [comment] 2018-02-08 12:11
i have try to install platformio-ide, but he cant find python 2.7 to complete. i have installed python 2.7 and set the variable in path on windows 10. python works correct...when i click on i have python and select the folder platformio installer won't accept it and is python still missing

**Comment by ivankravets** [comment] 2018-02-17 16:39
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment] 2018-02-17 16:39
Duplicate of #1364

**Closed by ivankravets** 2018-02-17 16:39 UTC
