### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by JIKJ** [platformio/platformio-atom-ide#1488] opened 2018-02-05 19:32 UTC
Error: spawn platformio ENOENT
This is shown every time I open some folder, but this do nothing.
I can compile normally, but my characters is weird. Look that:
![screenshot_2018-02-05_16-27-59](https://user-images.githubusercontent.com/20160397/35824548-f2c75da8-0a91-11e8-8981-d5b34494a25c.png)

Is that something in common?

**Comment by ivankravets** [comment] 2018-02-17 16:18
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1260

**Closed by ivankravets** 2018-02-17 16:18 UTC
