### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by alexkirillov** [platformio/platformio-atom-ide#1670] opened 2018-03-22 14:03 UTC
Traceback (most recent call last):
  File "/Users/akk/.platformio/penv/bin/platformio", line 11, in <module>
    load_entry_point('platformio==3.5.3a5', 'console_scripts', 'platformio')()
  File "/Users/akk/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py", line 126, in main
    error_str += str(e)
  File "/Users/akk/.platformio/penv/lib/python2.7/site-packages/platformio/exception.py", line 23, in __str__
    return Exception.__str__(self)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 2283-2285: ordinal not in range(128)

**Comment by ivankravets** [comment] 2018-06-20 19:18
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1228

**Closed by ivankravets** 2018-06-20 19:18 UTC
