### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by headHUB** [platformio/platformio-atom-ide#1333] opened 2018-01-01 16:19 UTC
Error: [Mon Jan  1 08:03:56 2018] Processing d1 (platform: espressif8266; board: d1; framework: arduino; lib_extra_dirs: ~/Documents/Arduino/libraries)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
PlatformioException: Could not load broken JSON: /home/james/Arduino/libraries/ESP8266wifi-master/library.json:
File "/home/james/.platformio/penv/local/lib/python2.7/site-packages/platformio/builder/main.py", line 158:
env.SConscript("$BUILD_SCRIPT")
File "/home/james/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py", line 541:
return _SConscript(self.fs, *files, **subst_kw)
File "/home/james/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py", line 250:
exec _file_ in call_stack[-1].globals
File "/home/james/.platformio/platforms/espressif8266/builder/main.py", line 357:
target_elf = env.BuildProgram()
File "/home/james/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py", line 224:
return self.method(*nargs, **kwargs)
File "/home/james/.platformio/penv/local/lib/python2.7/site-packages/platformio/builder/tools/platformio.py", line 76:
env.Append(LIBS=env.BuildProjectLibraries())
File "/home/james/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py", line 224:
return self.method(*nargs, **kwargs)
File "/home/james/.platformio/penv/local/lib/python2.7/site-packages/platformio/builder/tools/piolib.py", line 789:
lib_builders = env.GetLibBuilders()
File "/home/james/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py", line 224:
return self.method(*nargs, **kwargs)
File "/home/james/.platformio/penv/local/lib/python2.7/site-packages/platformio/builder/tools/piolib.py", line 761:
env, join(libs_dir, item), verbose=verbose)
File "/home/james/.platformio/penv/local/lib/python2.7/site-packages/platformio/builder/tools/piolib.py", line 52:
env, path, verbose=verbose)
File "/home/james/.platformio/penv/local/lib/python2.7/site-packages/platformio/builder/tools/piolib.py", line 102:
self._manifest = manifest if manifest else self.load_manifest()
File "/home/james/.platformio/penv/local/lib/python2.7/site-packages/platformio/builder/tools/piolib.py", line 537:
manifest = util.load_json(join(self.path, "library.json"))
File "/home/james/.platformio/penv/local/lib/python2.7/site-packages/platformio/util.py", line 193:
"Could not load broken JSON: %s" % file_path)
========================== [ERROR] Took 4.10 seconds ==========================

**Comment by ivankravets** [comment] 2018-01-10 17:53
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1204

**Closed by ivankravets** 2018-01-10 17:53 UTC
