### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by tripsBro** [platformio/platformio-atom-ide#1579] opened 2018-03-04 08:46 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Ubuntu 16.04.3
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'theme' of undefined

```
At /home/rahul/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1784

TypeError: Cannot read property 'theme' of undefined
    at Object.getFrontendUri (/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1784:25)
    at HomeView.render (/packages/platformio-ide/lib/home/view.js:60:45)
    at updateSync (/packages/platformio-ide/node_modules/etch/lib/component-helpers.js:107:34)
    at /packages/platformio-ide/node_modules/etch/lib/component-helpers.js:72:7
    at ViewRegistry.performDocumentUpdate (/usr/share/atom/resources/app/src/view-registry.js:238:13)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-clang 0.11.4 
build 0.70.0 
busy-signal 1.4.3 
file-icons 2.1.17 
intentions 1.1.5 
language-ini 1.19.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
platformio-ide 2.1.0 
platformio-ide-debugger 1.2.5 
platformio-ide-terminal 2.8.0 
tool-bar 1.1.6 
```

**Comment by ivankravets** [comment] 2018-03-05 14:15
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1573

**Closed by ivankravets** 2018-03-05 14:15 UTC
