### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by zs5ak** [platformio/platformio-atom-ide#1115] opened 2017-11-04 10:04 UTC
Error: Status 'PlatformIO: Rebuilding C/C++ Project Index for /Users/Khan/Downloads/Sonoff-Tasmota-development' is already set
    at Registry.statusAdd (/Users/Khan/.atom/packages/busy-signal/lib/registry.js:50:13)
    at /Users/Khan/.atom/packages/busy-signal/lib/registry.js:31:12
    at Function.module.exports.Emitter.simpleDispatch (/private/var/folders/gl/92pwwrrs7dd27ksh6v1r_bgc0000gn/T/AppTranslocation/C7C4BD6D-11F1-4F6D-A561-2EB18658333B/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/private/var/folders/gl/92pwwrrs7dd27ksh6v1r_bgc0000gn/T/AppTranslocation/C7C4BD6D-11F1-4F6D-A561-2EB18658333B/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Provider.add (/Users/Khan/.atom/packages/busy-signal/lib/provider.js:21:18)
    at beginBusy (/Users/Khan/.atom/packages/platformio-ide/lib/services/busy.js:25:20)
    at ProjectIndexer.<anonymous> (/Users/Khan/.atom/packages/platformio-ide/lib/project/indexer.js:158:7)
    at Generator.next (<anonymous>)
    at step (/Users/Khan/.atom/packages/platformio-ide/lib/project/indexer.js:11:273)
    at /Users/Khan/.atom/packages/platformio-ide/lib/project/indexer.js:11:443
    at ProjectIndexer.<anonymous> (/Users/Khan/.atom/packages/platformio-ide/lib/project/indexer.js:11:99)

**Comment by ivankravets** [comment] 2017-11-04 13:08
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1013

**Closed by ivankravets** 2017-11-04 13:08 UTC
