### ISSUE TITLE
UnicodeDecodeError / "C/C++ project index rebuild failed"

### ISSUE THREAD

**Issue by razorlikes** [platformio/platformio-atom-ide#930] opened 2017-09-11 13:01 UTC
```Error: Traceback (most recent call last):
  File "c:\.platformio\penv\lib\site-packages\platformio\__main__.py", line 120, in main
    cli(None, None, None)
  File "c:\.platformio\penv\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\.platformio\penv\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\.platformio\penv\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\.platformio\penv\lib\site-packages\click\decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\.platformio\penv\lib\site-packages\platformio\commands\init.py", line 102, in cli
    pg = ProjectGenerator(project_dir, ide, env_name)
  File "c:\.platformio\penv\lib\site-packages\platformio\ide\projectgenerator.py", line 39, in __init__
    self._gather_tplvars()
  File "c:\.platformio\penv\lib\site-packages\platformio\ide\projectgenerator.py", line 152, in _gather_tplvars
    self._tplvars.update(self.get_project_build_data())
  File "c:\.platformio\penv\lib\site-packages\platformio\util.py", line 135, in __call__
    value = self.func(*args)
  File "c:\.platformio\penv\lib\site-packages\platformio\ide\projectgenerator.py", line 74, in get_project_build_data
    target=["idedata"])
  File "c:\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\.platformio\penv\lib\site-packages\click\decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\.platformio\penv\lib\site-packages\platformio\commands\run.py", line 109, in cli
    result = (envname, ep.process())
  File "c:\.platformio\penv\lib\site-packages\platformio\commands\run.py", line 193, in process
    result = self._run()
  File "c:\.platformio\penv\lib\site-packages\platformio\commands\run.py", line 284, in _run
    self.verbose)
  File "c:\.platformio\penv\lib\site-packages\platformio\commands\run.py", line 307, in _autoinstall_libdeps
    ctx.invoke(cmd_lib_install, libraries=[lib], silent=not verbose)
  File "c:\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\.platformio\penv\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "c:\.platformio\penv\lib\site-packages\platformio\commands\lib.py", line 100, in lib_install
    lm.install(library, silent=silent, interactive=interactive)
  File "c:\.platformio\penv\lib\site-packages\platformio\managers\lib.py", line 252, in install
    trigger_event)
  File "c:\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 630, in install
    pkg_dir = self._install_from_piorepo(name, requirements)
  File "c:\.platformio\penv\lib\site-packages\platformio\managers\lib.py", line 231, in _install_from_piorepo
    dl_data['url'], requirements)
  File "c:\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 363, in _install_from_url
    dlpath = self.download(url, tmp_dir, sha1)
  File "c:\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 173, in download
    fd = FileDownloader(url, dest_dir)
  File "c:\.platformio\penv\lib\site-packages\platformio\downloader.py", line 56, in __init__
    self.set_destination(join(dest_dir, self._fname))
  File "c:\.platformio\penv\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 12: ordinal not in range(128)
```

Running Windows 7 64bit.

**Comment by ivankravets** [comment] 2017-10-17 13:57
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/812

**Closed by ivankravets** 2017-10-17 13:57 UTC
