### ISSUE TITLE
Problem occured while upgrading PlatformIO IDE

### ISSUE THREAD

**Issue by kosme** [platformio/platformio-atom-ide#1371] opened 2018-01-11 06:07 UTC
Error: undefined:130
"
^

SyntaxError: Unexpected string in JSON at position 5279
    at Object.parse (native)
    at /usr/share/atom/resources/app/apm/lib/install.js:470:33
    at fn (/usr/share/atom/resources/app/apm/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/async/lib/async.js:498:34)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)

    at /home/kosme/.atom/packages/platformio-ide/lib/installer/ide.js:59:9
    at Generator.throw (<anonymous>)
    at step (/home/kosme/.atom/packages/platformio-ide/lib/installer/ide.js:176:2)

**Comment by ivankravets** [comment] 2018-01-11 12:16
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1334

**Closed by ivankravets** 2018-01-11 12:16 UTC
