### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by eporocrail** [platformio/platformio-atom-ide#1652] opened 2018-03-18 16:04 UTC
Virtualenv Download: Traceback (most recent call last):
  File "/var/folders/dq/77mp5cys1bscw0r10y16bjv40000gn/T/tmp-52060MASWNGk18j0k/virtualenv-15.1.0/virtualenv.py", line 2328, in <module>

    main()
  File "/var/folders/dq/77mp5cys1bscw0r10y16bjv40000gn/T/tmp-52060MASWNGk18j0k/virtualenv-15.1.0/virtualenv.py", line 713, in main

    symlink=options.symlink)
  File "/var/folders/dq/77mp5cys1bscw0r10y16bjv40000gn/T/tmp-52060MASWNGk18j0k/virtualenv-15.1.0/virtualenv.py", line 925, in create_environment

    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/Users/ellard/.platformio/penv/lib/python2.7/posixpath.py", line 360, in abspath

    if not isabs(path):
  File "/Users/ellard/.platformio/penv/lib/python2.7/posixpath.py", line 54, in isabs

    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by ivankravets** [comment] 2018-06-21 09:36
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1556

**Closed by ivankravets** 2018-06-21 09:36 UTC
