### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by juankyestevez** [platformio/platformio-atom-ide#1283] opened 2017-12-19 01:52 UTC
PIP:   Failed building wheel for netifaces
Command "/home/juanky/.platformio/penv/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Awm95Q/netifaces/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-1MSaMd-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/juanky/.platformio/penv/include/site/python2.7/netifaces" failed with error code 1 in /tmp/pip-build-Awm95Q/netifaces/

**Comment by ivankravets** [comment] 2017-12-19 09:27
What is your OS?

**Comment by ivankravets** [comment] 2017-12-19 10:44
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1282

**Closed by ivankravets** 2017-12-19 10:44 UTC

**Comment by juankyestevez** [comment] 2017-12-19 13:54
Hi, I am testing Deepin 15.5

**Comment by ivankravets** [comment] 2017-12-19 13:54
Please restart IDE. All should work now.

**Comment by juankyestevez** [comment] 2017-12-19 14:05
"PlatformIO IDE has been successfully installed!
Please restart Atom to apply the changes"

After this message I restart Atom, but after start atom platformIO is installed again.

![deepinscreenshot_select-area_20171219090244](https://user-images.githubusercontent.com/18219921/34160615-9e3ac02a-e49b-11e7-9f37-4a84222bdc7b.png)
