### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by philsmithcomputime** [platformio/platformio-atom-ide#2085] opened 2018-10-04 02:27 UTC
Error: Error: Failed to download file examples.tar.gz
    at ProjectExamplesStage.<anonymous> (/Users/philsmith/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at Generator.throw (<anonymous>)
    at step (/Users/philsmith/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:13:273)
    at <anonymous>

**Comment by ivankravets** [comment] 2018-10-10 10:46
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/2075

Please switch to PlatformIO IDE for VSCode => https://platformio.org/platformio-ide

**Closed by ivankravets** 2018-10-10 10:46 UTC
