### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by sugawara-m33** [platformio/platformio-atom-ide#1982] opened 2018-07-05 17:57 UTC
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.27.2
PIO IDE: v2.1.7
System: Windows_NT, 10.0.17134, x64

# Exception
```
Error: Processing disco_f413zh (platform: ststm32; board: disco_f413zh; framework: stm32cube)

Verbose mode can be enabled via `-v, --verbose` option
Error: Unknown board ID 'disco_f413zh'
 [ERROR] Took 0.69 seconds 


```

**Comment by ivankravets** [comment] 2018-07-17 13:55
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1980

**Closed by ivankravets** 2018-07-17 13:55 UTC
