### ISSUE TITLE
duplicate 'Goto Declaration' context menus

### ISSUE THREAD

**Issue by Spongman** [platformio/platformio-atom-ide#309] opened 2017-03-31 16:41 UTC
my right click menu contains two items:
- "Goto Declaration"
- "Go to Declaration"

pick one?

**Comment by ivankravets** [comment] 2017-04-01 09:52
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/145

**Closed by ivankravets** 2017-04-01 09:52 UTC
Labels: duplicate
