### ISSUE TITLE
platformio_ide_terminal InstallationManager

### ISSUE THREAD

**Issue by usuf1** [platformio/platformio-atom-ide#1702] opened 2018-03-31 15:09 UTC
Error: Failed to download file https://pypi.python.org/packages/source/v/virtualenv/virtualenv-14.0.6.tar.gz: Error: EPERM: operation not permitted, open 'C:\Users\YUsuf\.platformio\.cache\virtualenv.tar.gz'
    at _callee$ (C:\Users\YUsuf\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:2668:19)
    at tryCatch (C:\Users\YUsuf\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:836:40)
    at Generator.invoke [as _invoke] (C:\Users\YUsuf\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1070:22)
    at Generator.prototype.(anonymous function) [as throw] (C:\Users\YUsuf\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:888:21)
    at step (C:\Users\YUsuf\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:2770:191)
    at C:\Users\YUsuf\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:2770:402
    at <anonymous>

**Comment by ivankravets** [comment] 2018-04-19 20:51
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1674

**Closed by ivankravets** 2018-04-19 20:51 UTC
