### ISSUE TITLE
Error: Can not find Python Interpreter

### ISSUE THREAD

**Issue by stojkovic-mladen** [platformio/platformio-atom-ide#1382] opened 2018-01-12 17:48 UTC
Error: Can not find Python Interpreter
    at PlatformIOCoreStage._callee8$ (C:\Users\Mladen Stojkovic\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:2471:23)
    at tryCatch (C:\Users\Mladen Stojkovic\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:831:40)
    at Generator.invoke [as _invoke] (C:\Users\Mladen Stojkovic\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1065:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\Mladen Stojkovic\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:883:21)
    at step (C:\Users\Mladen Stojkovic\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1836:191)
    at C:\Users\Mladen Stojkovic\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1836:361
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment] 2018-01-16 18:46
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment] 2018-02-17 16:39
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1364

**Closed by ivankravets** 2018-02-17 16:39 UTC
Labels: help wanted
