### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by rhodopsik** [platformio/platformio-atom-ide#1725] opened 2018-04-07 04:46 UTC
PIP:   Could not find a version that satisfies the requirement bottle<0.13 (from platformio==3.5.3a8) (from versions: )
No matching distribution found for bottle<0.13 (from platformio==3.5.3a8)

What can I do? Any suggestion?
Thanks!

**Comment by ivankravets** [comment] 2018-04-09 04:45
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1592

**Closed by ivankravets** 2018-04-09 04:45 UTC
