### ISSUE TITLE
Platform command failed: platform install linux_arm

### ISSUE THREAD

**Issue by albydnc** [platformio/platformio-atom-ide#357] opened 2017-04-11 15:20 UTC
Error: sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

Error: Could not find a version that satisfies the requirement '~1.40802.0' for your system 'linux_x86_64'

    at /home/albertoperro/.atom/packages/platformio-ide/lib/platform/helpers.js:61:25
    at onExit (/home/albertoperro/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/home/albertoperro/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/usr/lib/atom/src/buffered-process.js:322:11)
    at /usr/lib/atom/src/buffered-process.js:343:11
    at Socket.<anonymous> (/usr/lib/atom/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by ivankravets** [comment] 2017-04-30 21:29
Duplicate of https://github.com/platformio/platform-linux_arm/issues/2

**Closed by ivankravets** 2017-04-30 21:29 UTC
Labels: duplicate
