### ISSUE TITLE
Again: "Could not start PIO Home server"

### ISSUE THREAD

**Issue by ShardanX** [platformio/platformio-atom-ide#1335] opened 2018-01-02 14:42 UTC
"Uncaught Error: Could not start PIO Home server: Error: Could not install 'contrib-pysite' with version requirements '>=0.1.2,<2' for your system 'windows_x86'. If you use Antivirus, it can block PlatformIO Package Manager. Try to disable it for a while."

I've COMPLETELY DEINSTALLED Antivir, deactivated local firewall - no chance.

Then completely reinstalled atom + platformio - even worse! Now i get

"Error: Could not install 'espressif8266' with version requirements '*' for your system 'windows_x86'.
 If you use Antivirus, it can block PlatformIO Package Manager. Try to disable it for a while."

on top.

It is meaningless to tell "Deactivate Antivir" as it does not help.
Something must have changed as it was running with same antivir for months now.
Any new ports used? Maybe some newly set permissions?

**Comment by ivankravets** [comment] 2018-01-10 20:13
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1171

**Closed by ivankravets** 2018-01-10 20:13 UTC
