### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by Chirag-Modi** [platformio/platformio-atom-ide#2214] opened 2019-06-14 06:32 UTC
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.38.1
PIO IDE: v2.3.1
System: Windows_NT, 10.0.17763, x64

# Exception
```
Error: Could not create PIO Core Virtual Environment. Please create it manually -> http://bit.ly/pio-core-virtualenv 
 Error: Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\Chirag Modi\.platformio\.cache\tmp-5356WTueHTTZIMmk\virtualenv-16.1.0\src\virtualenv.py", line 2462, in <module>
    main()
  File "C:\Users\Chirag Modi\.platformio\.cache\tmp-5356WTueHTTZIMmk\virtualenv-16.1.0\src\virtualenv.py", line 762, in main
    symlink=options.symlink,
  File "C:\Users\Chirag Modi\.platformio\.cache\tmp-5356WTueHTTZIMmk\virtualenv-16.1.0\src\virtualenv.py", line 998, in create_environment
    install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)
  File "C:\Users\Chirag Modi\.platformio\.cache\tmp-5356WTueHTTZIMmk\virtualenv-16.1.0\src\virtualenv.py", line 1317, in install_python
    shutil.copyfile(executable, py_executable)
  File "C:\Users\Chirag Modi\.platformio\python27\Lib\shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: 'C:\\Users\\CHIRAG~1\\PLATFO~1\\penv\\Scripts\\python.exe'

New python executable in C:\Users\CHIRAG~1\PLATFO~1\penv\Scripts\python.exe

    at t.value (C:\Users\Chirag Modi\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:25605)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by ivankravets** [comment] 2019-07-23 14:02
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/2147

**Closed by ivankravets** 2019-07-23 14:02 UTC
