### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by echoGee** [platformio/platformio-atom-ide#1767] opened 2018-04-16 19:08 UTC
Error: Could not install 'toolchain-xtensa32' with version requirements '~2.50200.0' for your system 'windows_amd64'.

Please try this solution -> http://bit.ly/faq-package-manager

Popup message after installation
=========
Platform has been successfully installed
PlatformManager: Installing espressif32
espressif32 @ 0.12.0 is already installed
PackageManager: Installing toolchain-xtensa32 @ ~1.50200.2
Downloading...
Unpacking...
toolchain-xtensa32 @ 1.50200.2 has been successfully installed!
PackageManager: Installing tool-esptoolpy @ ~1.20100.0
tool-esptoolpy @ 1.20100.0 is already installed
Uninstalling toolchain-xtensa32 @ 2.50200.80: [OK]
The platform 'espressif32' has been successfully installed!
The rest of packages will be installed automatically depending on your build environment.
=================

**Comment by ivankravets** [comment] 2018-06-20 18:47
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1171

**Closed by ivankravets** 2018-06-20 18:47 UTC
