### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by Fuellhase** [platformio/platformio-atom-ide#805] opened 2017-08-04 15:33 UTC
Hello!
I get the following Error message when I try to install platformio-ide. Any Idea?

PIP: Error: spawn /Volumes/Macintosh HD/Users/Peter/.platformio/penv/bin/pip ENOENT

Greetings from Germany - Peter

**Comment by ivankravets** [comment] 2017-08-04 17:13
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/698

**Closed by ivankravets** 2017-08-04 17:13 UTC
Labels: duplicate
