### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by weezixx** [platformio/platformio-atom-ide#1312] opened 2017-12-28 09:17 UTC
Hello,

What can I do to fix this ? And the other problem that I got previously was : I can't compile in C.

Thanks folks !

> 
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\Kevin\.platformio\.cache\tmp-15644jsryPC5XHf6b\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\Kevin\.platformio\.cache\tmp-15644jsryPC5XHf6b\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\Kevin\.platformio\.cache\tmp-15644jsryPC5XHf6b\virtualenv-14.0.6\virtualenv.py", line 924, in create_environment
    download=download,
  File "C:\Users\Kevin\.platformio\.cache\tmp-15644jsryPC5XHf6b\virtualenv-14.0.6\virtualenv.py", line 877, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "C:\Users\Kevin\.platformio\.cache\tmp-15644jsryPC5XHf6b\virtualenv-14.0.6\virtualenv.py", line 747, in call_subprocess
    "Error %s while executing command %s" % (e, cmd_desc))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 19: ordinal not in range(128)

>

**Comment by ivankravets** [comment] 2017-12-28 18:54
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1276

**Closed by ivankravets** 2017-12-28 18:54 UTC
