### ISSUE TITLE
InstallationManager: Virtualenv Download

### ISSUE THREAD

**Issue by pelorr** [platformio/platformio-atom-ide#367] opened 2017-04-14 13:37 UTC
Virtualenv Download:   File "C:\Program Files\Python\Lib\site.py", line 177
    file=sys.stderr)
        ^
SyntaxError: invalid syntax

**Comment by ivankravets** [comment] 2017-04-30 21:46
Do you have `virtualenv` installed in a system?

```
python --version
virtualenv --version
```

**Comment by ivankravets** [comment] 2017-05-01 11:42
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/337

Issue with Python 3

**Closed by ivankravets** 2017-05-01 11:42 UTC
Labels: bug, duplicate
