### ISSUE TITLE
Error message when updating to 0.3.2.

### ISSUE THREAD

**Issue by sstaub** [platformio/platformio-atom-ide#29] opened 2016-01-31 08:57 UTC
When updating to 0.3.2., the update process seems to stop, in the background i get following error message, When I restart Atom there a no more messages and it works:
![installation 0 3 2](https://cloud.githubusercontent.com/assets/6450325/12701172/d0cc8208-c800-11e5-8bf8-d0438e5e2e03.png)

**Comment by orgkhnargh** [comment] 2016-01-31 10:18
1. Which version you were upgrading from?
2. Do you see any errors in Console? (To see the Console go to `View > Developer > Toggle Developer Tools` menu item, then navigate to the Console tab inside of opened panel.)
3. Do you experience any feature regressions caused by this error? Does everything work correctly after reload?

Thanks for report!

**Comment by sstaub** [comment] 2016-01-31 10:57
1. It happens when updating from 0.3.1 to 0.3.2
3. No
updated from 0.3.2 to 0.3.3 with no errors

**Comment by ivankravets** [comment] 2016-01-31 17:42
@sstaub this issue is linked with Atom installer. I close it but please reopen if you have similar issues in future.

Thanks!

**Closed by ivankravets** 2016-01-31 17:42 UTC
