### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by thingAS** [platformio/platformio-atom-ide#829] opened 2017-08-12 00:13 UTC
I don´t know why I have this error:

C:\Users\admin\.platformio\packages\tool-scons\script\..\engine\SCons\Environment.py:1303: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
val = [x for x in val if x not in dk]

UnicodeDecodeError: Non-ASCII characters found in build environment
See explanation in FAQ > Troubleshooting > Building
http://docs.platformio.org/page/faq.html

 [ERROR] Took 11.40 seconds

**Comment by ivankravets** [comment] 2017-09-06 11:55
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/768

**Closed by ivankravets** 2017-09-06 11:55 UTC
