### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by aslake** [platformio/platformio-atom-ide#1070] opened 2017-10-23 18:31 UTC
Error: Status 'PlatformIO: Rebuilding C/C++ Project Index for /home/aslak/Documents/platformio/ESPAsync' is already set
    at Registry.statusAdd (/home/aslak/.atom/packages/busy-signal/lib/registry.js:50:13)
    at /home/aslak/.atom/packages/busy-signal/lib/registry.js:31:12
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Provider.add (/home/aslak/.atom/packages/busy-signal/lib/provider.js:21:18)
    at beginBusy (/home/aslak/.atom/packages/platformio-ide/lib/services/busy.js:25:20)
    at ProjectIndexer.<anonymous> (/home/aslak/.atom/packages/platformio-ide/lib/project/indexer.js:158:7)
    at Generator.next (<anonymous>)
    at step (/home/aslak/.atom/packages/platformio-ide/lib/project/indexer.js:11:273)
    at /home/aslak/.atom/packages/platformio-ide/lib/project/indexer.js:11:443
    at ProjectIndexer.<anonymous> (/home/aslak/.atom/packages/platformio-ide/lib/project/indexer.js:11:99)

**Comment by ivankravets** [comment] 2017-11-04 13:09
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1013

**Closed by ivankravets** 2017-11-04 13:09 UTC
