### ISSUE TITLE
Problem occured while upgrading PlatformIO IDE

### ISSUE THREAD

**Issue by Igor122017** [platformio/platformio-atom-ide#1466] opened 2018-01-31 23:43 UTC
Error: Cannot read property 'getReferenceTarget' of null

    at file:///C:/Users/User_H/.atom/packages/platformio-ide/lib/installer/ide.js:59:9
    at Generator.throw (<anonymous>)
    at step (file:///C:/Users/User_H/.atom/packages/platformio-ide/lib/installer/ide.js:176:2)

**Comment by ivankravets** [comment] 2018-02-05 23:37
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1394

**Closed by ivankravets** 2018-02-05 23:37 UTC
