### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by talkingbeast** [platformio/platformio-atom-ide#1976] opened 2018-07-03 13:14 UTC
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.26.1
PIO IDE: v2.1.7
System: Windows_NT, 10.0.17134, x64

# Exception
```
Traceback (most recent call last):
  File "c:\users\talkingbeast\.platformio\penv\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\talkingbeast\.platformio\penv\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\talkingbeast\.platformio\penv\Scripts\platformio.exe\__main__.py", line 9, in <module>
  File "c:\users\talkingbeast\.platformio\penv\lib\site-packages\platformio\__main__.py", line 126, in main
    error_str += str(e)
  File "c:\users\talkingbeast\.platformio\penv\lib\site-packages\platformio\exception.py", line 23, in __str__
    return Exception.__str__(self)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 591-619: ordinal not in range(128)

```

**Comment by ivankravets** [comment] 2018-07-19 15:22
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1228

**Closed by ivankravets** 2018-07-19 15:22 UTC
