### ISSUE TITLE
Error Installing Platformio on Mac

### ISSUE THREAD

**Issue by danberlyoung** [platformio/platformio-atom-ide#1772] opened 2018-04-18 03:18 UTC
I'm getting a error while platformio is trying to install the "PlatformIO Core" on launch. I've tried reinstalling Atom, platformIO and deleting the .platformio prefs folder.  any suggestions?

Here's the error message.

PIP: /Volumes/TrevorAnnex/Users/danb/.platformio/penv/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/Volumes/TrevorAnnex/Users/danb/.platformio/penv/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Could not find a version that satisfies the requirement bottle<0.13 (from platformio==3.5.3a9) (from versions: )
No matching distribution found for bottle<0.13 (from platformio==3.5.3a9)
/Volumes/TrevorAnnex/Users/danb/.platformio/penv/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

**Comment by ivankravets** [comment] 2018-04-21 11:34
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1592

Just uninstall this package and install again

**Closed by ivankravets** 2018-04-21 11:34 UTC
