### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by TianaAnderson** [platformio/platformio-atom-ide#1766] opened 2018-04-16 16:23 UTC
Error: Failed to download file https://pypi.python.org/packages/source/v/virtualenv/virtualenv-14.0.6.tar.gz: 
    at _callee$ (C:\Users\Tiana\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:2679:19)
    at tryCatch (C:\Users\Tiana\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:836:40)
    at Generator.invoke [as _invoke] (C:\Users\Tiana\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1070:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\Tiana\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:888:21)
    at step (C:\Users\Tiana\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:2781:191)
    at C:\Users\Tiana\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:2781:361
    at <anonymous>

**Comment by ivankravets** [comment] 2018-04-19 20:51
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1674

**Closed by ivankravets** 2018-04-19 20:51 UTC
