### ISSUE TITLE
Installation failed platformio-ide@2.1.0

### ISSUE THREAD

**Issue by quito96** [platformio/platformio-atom-ide#1583] opened 2018-03-04 20:46 UTC
Hi,

when i wanted to install the platformio-ide@2.1.0 — Atom Vers. 1.24.0x64 (MAC OSX)
i get the following message:

`nstalling “platformio-ide@2.1.0” failed.Hide output…
fs.js:922
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: ENOENT: no such file or directory, mkdir '/var/folders/F-/F-lzMu3wG84oDc9ac4ebNE+++TI/-Tmp-/d-11824-31566-1t30jt0.rxine6zuxr'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at Object.mkdirSync (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/temp/lib/temp.js:137:6)
    at Request.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/lib/install.js:335:41)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestResponse (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/request/request.js:1068:10)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)`

Whats wrong here??

BR
quito96

**Comment by ivankravets** [comment] 2018-06-20 18:39
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1472

**Closed by ivankravets** 2018-06-20 18:39 UTC
