### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by maskac** [platformio/platformio-atom-ide#410] opened 2017-04-27 16:53 UTC
Virtualenv Download: Traceback (most recent call last):
  File "C:\Users\maska\AppData\Local\Temp\tmp-11852kZyS337B2jqw\virtualenv-15.1.0\virtualenv.py", line 2328, in <module>
    main()
  File "C:\Users\maska\AppData\Local\Temp\tmp-11852kZyS337B2jqw\virtualenv-15.1.0\virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "C:\Users\maska\AppData\Local\Temp\tmp-11852kZyS337B2jqw\virtualenv-15.1.0\virtualenv.py", line 945, in create_environment
    download=download,
  File "C:\Users\maska\AppData\Local\Temp\tmp-11852kZyS337B2jqw\virtualenv-15.1.0\virtualenv.py", line 901, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "C:\Users\maska\AppData\Local\Temp\tmp-11852kZyS337B2jqw\virtualenv-15.1.0\virtualenv.py", line 757, in call_subprocess
    "Error %s while executing command %s" % (e, cmd_desc))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 17: ordinal not in range(128)

**Comment by ivankravets** [comment] 2017-04-30 21:33
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/321

**Closed by ivankravets** 2017-04-30 21:33 UTC
Labels: duplicate
