### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by kenxausten** [platformio/platformio-atom-ide#957] opened 2017-09-18 08:56 UTC
Error: Error: Error: Failed to download file https://github.com/IntoYun/intoyuniot-examples/tarball/master: 
    at ProjectExamplesStage.<anonymous> (file:///C:/Users/austen/.atom/packages/intoyuniot-ide/lib/installer/stages/project-examples.js:157:13)
    at Generator.throw (<anonymous>)
    at step (C:\Users\austen\.atom\packages\intoyuniot-ide\lib\installer\stages\project-examples.js:13:273)

**Comment by ivankravets** [comment] 2017-10-17 12:25
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/934

**Closed by ivankravets** 2017-10-17 12:25 UTC
