### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by petrovichpit** [platformio/platformio-atom-ide#324] opened 2017-04-02 10:08 UTC
Virtualenv Download: Traceback (most recent call last):
  File "C:\Users\B19A~1\AppData\Local\Temp\tmp-7200QLqttaWPpnpO\virtualenv-15.1.0\virtualenv.py", line 2328, in <module>
    main()
  File "C:\Users\B19A~1\AppData\Local\Temp\tmp-7200QLqttaWPpnpO\virtualenv-15.1.0\virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "C:\Users\B19A~1\AppData\Local\Temp\tmp-7200QLqttaWPpnpO\virtualenv-15.1.0\virtualenv.py", line 925, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "C:\Users\B19A~1\AppData\Local\Temp\tmp-7200QLqttaWPpnpO\virtualenv-15.1.0\virtualenv.py", line 1148, in install_python
    writefile(join(site_dir, 'orig-prefix.txt'), prefix)
  File "C:\Users\B19A~1\AppData\Local\Temp\tmp-7200QLqttaWPpnpO\virtualenv-15.1.0\virtualenv.py", line 368, in writefile
    if c != content.encode("utf-8"):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 9: ordinal not in range(128)

**Comment by ivankravets** [comment] 2017-04-02 19:03
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/321

**Closed by ivankravets** 2017-04-02 19:03 UTC
