### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by gerhardvz** [platformio/platformio-atom-ide#1741] opened 2018-04-10 10:38 UTC
PIP: sh: module: line 1: syntax error: unexpected end of file
sh: error importing function definition for `module'
sh: scl: line 1: syntax error: unexpected end of file
sh: error importing function definition for `scl'
Could not import setuptools which is required to install from a source distribution.
sh: module: line 1: syntax error: unexpected end of file
sh: error importing function definition for `module'
sh: scl: line 1: syntax error: unexpected end of file
sh: error importing function definition for `scl'

**Comment by ivankravets** [comment] 2018-06-20 18:50
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1729

**Closed by ivankravets** 2018-06-20 18:50 UTC
