### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by enardone** [platformio/platformio-atom-ide#1955] opened 2018-06-27 16:00 UTC
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.0
PIO IDE: v2.1.7
System: Windows_NT, 6.1.7601, ia32

# Exception
```
"platformio" non � riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
Error: spawn platformio ENOENT
```

**Comment by ivankravets** [comment] 2018-07-17 13:54
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1243

**Closed by ivankravets** 2018-07-17 13:54 UTC
