### ISSUE TITLE
Goto Declaration shows up twice if i right-click on a function

### ISSUE THREAD

**Issue by ilovetogetspamed** [platformio/platformio-atom-ide#145] opened 2016-07-27 18:38 UTC
There are two Goto Declarations on the right-click menu.  One is spelled "Goto Declaration" the other, "Go to Declaration". See picture.

Only the first one works for me.

I'm running Atom 1.7.1 and PlatformIO 1.3.6 on OS X El Capitan 10.11.6 (15G31) iMac.

Picture at [https://www.dropbox.com/s/ofle15ml1wt5mkq/Goto%20Declaration.png?dl=0](url)

**Comment by ivankravets** [comment] 2016-07-28 21:18
Duplicate of https://github.com/yasuyuky/autocomplete-clang/issues/106

Need to wait when this issue will be fixed in Atom's autocomplete-clang package

**Closed by ivankravets** 2016-07-28 21:18 UTC
Labels: duplicate
