### ISSUE TITLE
platformio home  does not initialize

### ISSUE THREAD

**Issue by mac-bleck** [platformio/platformio-atom-ide#968] opened 2017-09-21 20:01 UTC
the platformio home tab only has the updating icon and it does not go away. Please, what should I do?

**Comment by igrcic** [comment] 2017-09-21 20:17
Hi, Im experience the same issue after the update

**Comment by ivankravets** [comment] 2017-10-17 20:27
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/918

**Closed by ivankravets** 2017-10-17 20:27 UTC
