### ISSUE TITLE
IOError: [Errno 0] Error

### ISSUE THREAD

**Issue by jamesmyatt** [platformio/platformio-atom-ide#1942] opened 2018-06-24 21:39 UTC
I keep getting the following error. It appears to happen randomly since it happens at different point in the build process each time. Also for targets that aren't compiling anything. Any suggestions?

```
Traceback (most recent call last):
  File "c:\users\james\.platformio\penv\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "c:\users\james\.platformio\penv\lib\site-packages\platformio\util.py", line 94, in run
    self.outcallback(line)
  File "c:\users\james\.platformio\penv\lib\site-packages\platformio\managers\platform.py", line 399, in on_run_out
    self._echo_line(line, level=1)
  File "c:\users\james\.platformio\penv\lib\site-packages\platformio\managers\platform.py", line 420, in _echo_line
    click.secho(line, fg=fg, err=level > 1)
  File "c:\users\james\.platformio\penv\lib\site-packages\platformio\__main__.py", line 114, in <lambda>
    click.secho = lambda *args, **kwargs: _safe_echo(1, *args, **kwargs)
  File "c:\users\james\.platformio\penv\lib\site-packages\platformio\__main__.py", line 111, in _safe_echo
    sys.stdout.write)("%s\n" % (args[0] if args else ""))
IOError: [Errno 0] Error
```

* PlatformIO, version 3.6.0a3
* Windows 10 Pro

*update*: I assume that this is relevant: https://stackoverflow.com/questions/19283118/python-ioerror-errno-0-error-what-is-triggering-this-error-in-my-code

**Comment by ivankravets** [comment] 2019-07-23 14:02
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/2147

**Closed by ivankravets** 2019-07-23 14:02 UTC
