### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat 'F:/DRIVE\Projects\Tesis\UAV\DESARROLLO ...

### ISSUE THREAD

**Issue by liver94** [platformio/platformio-atom-ide#1820] opened 2018-05-06 01:01 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.1.4

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'F:\DRIVE\Projects\Tesis\UAV\DESARROLLO TECNICO\MONITORIO ATMOSFERICO Y DE LOS NIVELES DE CONTAMINACION DEL AIRE MEDIANTE EL USO DE UN UAV DE ALA FIJA COMO PLATAFORMA DE VUELO DE MODULOS CANSAT\src\gps.ino'

```
At fs.js:961

Error: ENOENT: no such file or directory, lstat 'F:\DRIVE\Projects\Tesis\UAV\DESARROLLO TECNICO\MONITORIO ATMOSFERICO Y DE LOS NIVELES DE CONTAMINACION DEL AIRE MEDIANTE EL USO DE UN UAV DE ALA FIJA COMO PLATAFORMA DE VUELO DE MODULOS CANSAT\src\gps.ino'
    at fs.lstatSync (fs.js:961:11)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
    at Proxy.realpathSync (fs.js:1641:21)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:321:29)
    at /packages/platformio-ide/lib/project/helpers.js:32:25
    at getActivePioProject (/packages/platformio-ide/lib/project/helpers.js:36:6)
    at Object.highlightActiveProject (/packages/platformio-ide/lib/maintenance.js:133:13)
    at doHighlight (/packages/platformio-ide/lib/main.js:247:43)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at stoppedChangingActivePaneItemTimeout.setTimeout (~/AppData/Local/atom/app-1.26.1/resources/app/src/workspace.js:491:26)
```

### Commands

```
     -6:15.7.0 platformio-ide:target:build (div.tool-panel.tree-view)
     -6:15.7.0 platformio-ide:target:build-F:\DRIVE\Projects\Tesis\UAV\DESARROLLO TECNICO\MONITORIO ATMOSFERICO Y DE LOS NIVELES DE CONTAMINACION DEL AIRE MEDIANTE EL USO DE UN UAV DE ALA FIJA COMO PLATAFORMA DE VUELO DE MODULOS CANSAT (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -5:55.8.0 platformio-ide:target:build (input.hidden-input)
     -5:55.8.0 platformio-ide:target:build-F:\DRIVE\Projects\Tesis\UAV\DESARROLLO TECNICO\MONITORIO ATMOSFERICO Y DE LOS NIVELES DE CONTAMINACION DEL AIRE MEDIANTE EL USO DE UN UAV DE ALA FIJA COMO PLATAFORMA DE VUELO DE MODULOS CANSAT (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -5:29.1.0 platformio-ide:target:build (ul.list-inline.tab-bar.inset-panel)
     -5:29.1.0 platformio-ide:target:build-F:\DRIVE\Projects\Tesis\UAV\DESARROLLO TECNICO\MONITORIO ATMOSFERICO Y DE LOS NIVELES DE CONTAMINACION DEL AIRE MEDIANTE EL USO DE UN UAV DE ALA FIJA COMO PLATAFORMA DE VUELO DE MODULOS CANSAT (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -5:13.6.0 intentions:highlight (input.hidden-input)
     -5:13.5.0 core:copy (input.hidden-input)
     -1:04.6.0 editor:consolidate-selections (input.hidden-input)
     -1:04.6.0 core:cancel (input.hidden-input)
     -0:59.7.0 tree-view:duplicate (span.name.icon.arduino-icon.dark-cyan)
     -0:57 core:backspace (input.hidden-input)
     -0:49.3.0 core:confirm (input.hidden-input)
     -0:45.2.0 tree-view:duplicate (span.name.icon.arduino-icon.dark-cyan)
     -0:43.7.0 core:backspace (input.hidden-input)
     -0:40.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-clang 0.11.4 
build 0.70.0 
busy-signal 1.4.3 
file-icons 2.1.19 
intentions 1.1.5 
language-ini 1.19.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
platformio-ide 2.1.4 
platformio-ide-debugger 1.2.5 
platformio-ide-terminal 2.8.1 
tool-bar 1.1.7 
```

**Comment by ivankravets** [comment] 2018-06-20 18:39
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1472

**Closed by ivankravets** 2018-06-20 18:39 UTC
