### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by rmillerin** [platformio/platformio-atom-ide#1803] opened 2018-04-27 19:45 UTC
PIP: Error: spawn /Network/Servers/server.millerin.co.uk/Users/Richard/Documents/Home Folders/Richard/.platformio/penv/bin/pip ENOENT

**Comment by ivankravets** [comment] 2018-06-20 18:42
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1243

**Closed by ivankravets** 2018-06-20 18:42 UTC
