### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by mogplus8** [platformio/platformio-atom-ide#755] opened 2017-07-21 14:12 UTC
Error: spawn platformio ENOENT. Did a fresh install of Platformio (Linux LMDE). Platformio menu didn't do anything. Used the Atom open a project command, and got the error.

**Comment by ivankravets** [comment] 2017-08-04 17:14
Duplicate of #698

**Closed by ivankravets** 2017-08-04 17:14 UTC
Labels: duplicate
