### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by adriansebastian** [platformio/platformio-atom-ide#1816] opened 2018-05-04 11:39 UTC
Virtualenv Create: Traceback (most recent call last):
  File "<string>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 12: ordinal not in range(128)

**Comment by ivankravets** [comment] 2018-06-20 18:53
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1276

**Closed by ivankravets** 2018-06-20 18:53 UTC
