### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by JoergZ2** [platformio/platformio-atom-ide#1663] opened 2018-03-20 16:16 UTC
Please manually remove file `/home/jz/.platformio/packages/contrib-pysite/twisted/words/__init__.py`
Error: Traceback (most recent call last):
  File "/home/jz/.platformio/penv/local/lib/python2.7/site-packages/platformio/__main__.py", line 120, in main
    cli(None, None, None)
  File "/home/jz/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/jz/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/jz/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jz/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 995, in _process_result
    **ctx.params)
  File "/home/jz/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/jz/.platformio/penv/local/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jz/.platformio/penv/local/lib/python2.7/site-packages/platformio/__main__.py", line 80, in process_result
    maintenance.on_platformio_end(ctx, result)
  File "/home/jz/.platformio/penv/local/lib/python2.7/site-packages/platformio/maintenance.py", line 52, in on_platformio_end
    check_platformio_upgrade()
  File "/home/jz/.platformio/penv/local/lib/python2.7/site-packages/platformio/maintenance.py", line 247, in check_platformio_upgrade
    update_core_packages(silent=True)
  File "/home/jz/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/core.py", line 95, in update_core_packages
    pm.update(name, requirements, only_check=only_check)
  File "/home/jz/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/core.py", line 56, in update
    result = PackageManager.update(self, *args, **kwargs)
  File "/home/jz/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/package.py", line 772, in update
    self.uninstall(pkg_dir, after_update=True)
  File "/home/jz/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/package.py", line 713, in uninstall
    util.rmtree_(pkg_dir)
  File "/home/jz/.platformio/penv/local/lib/python2.7/site-packages/platformio/util.py", line 779, in rmtree_
    return rmtree(path, onerror=_onerror)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/home/jz/.platformio/penv/local/lib/python2.7/site-packages/platformio/util.py", line 777, in _onerror
    raise e
OSError: [Errno 2] No such file or directory: '/home/jz/.platformio/packages/contrib-pysite/twisted/words/__init__.py'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by ivankravets** [comment] 2018-06-20 18:03
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1662

**Closed by ivankravets** 2018-06-20 18:03 UTC
