### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by ymasur** [platformio/platformio-atom-ide#2077] opened 2018-09-21 19:05 UTC
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.30.0
PIO IDE: v2.2.2
System: Windows_NT, 10.0.17134, x64

# Exception
```
Traceback (most recent call last):
  File "main.py", line 16, in init main
  File "cmd_debug.py", line 24, in init cmd_debug
  File "C:\Users\Masur\.platformio\packages\contrib-pysite\twisted\internet\stdio.py", line 30, in <module>
    from twisted.internet import _win32stdio
  File "C:\Users\Masur\.platformio\packages\contrib-pysite\twisted\internet\_win32stdio.py", line 9, in <module>
    import win32api
ImportError: DLL load failed: %1 n'est pas une application Win32 valide.

```

**Comment by ivankravets** [comment] 2018-10-10 10:45
Duplicate of https://github.com/platformio/platformio-vscode-ide/issues/176

**Closed by ivankravets** 2018-10-10 10:45 UTC
