### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by chifailai2** [platformio/platformio-atom-ide#1963] opened 2018-06-30 02:31 UTC
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.0
PIO IDE: v2.1.7
System: Windows_NT, 10.0.16299, x64

# Exception
```
Cloning into 'C:\Users\Ken Lai\Desktop\homekit-master\homekit-master\blindkit\raex-remote\.piolibdeps\_tmp_installing-qt6nqo-package'...
error: unable to create file tests/Arduino/sketches/serial_gw_no_transport_hard_signing_whitelisting_full_debug/serial_gw_no_transport_hard_signing_whitelisting_full_debug.ino: Filename too long
error: unable to create file tests/Arduino/sketches/serial_gw_no_transport_soft_signing_whitelisting_full_debug/serial_gw_no_transport_soft_signing_whitelisting_full_debug.ino: Filename too long
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

Error: VCS: Could not process command ['git', 'clone', '--recursive', '--depth', '1', 'https://github.com/mysensors/MySensors', 'C:\\Users\\Ken Lai\\Desktop\\homekit-master\\homekit-master\\blindkit\\raex-remote\\.piolibdeps\\_tmp_installing-qt6nqo-package']

```

**Comment by ivankravets** [comment] 2018-07-17 13:53
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1964

**Closed by ivankravets** 2018-07-17 13:53 UTC
