### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by Casimodo** [platformio/platformio-atom-ide#1975] opened 2018-07-03 09:59 UTC
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.0
PIO IDE: v2.1.7
System: Windows_NT, 10.0.16299, x64

# Exception
```
'platformio' n'est pas reconnu en tant que commande interne
ou externe, un programme ex�cutable ou un fichier de commandes.
Error: spawn platformio ENOENT
```

**Comment by ivankravets** [comment] 2018-07-08 16:08
Could you reproduce this issue after restart of Atom?

**Comment by ivankravets** [comment] 2018-07-17 13:55
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1243

**Closed by ivankravets** 2018-07-17 13:55 UTC
