### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by davestroud** [platformio/platformio-atom-ide#596] opened 2017-06-08 16:06 UTC
PIP: Could not import setuptools which is required to install from a source distribution.
Traceback (most recent call last):
  File "/Users/davidstroud/.platformio/penv/lib/python2.7/site-packages/pip/req/req_install.py", line 387, in setup_py
    import setuptools  # noqa
  File "/Users/davidstroud/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 10, in <module>
    from six.moves import filter, map
ImportError: No module named six.moves

**Comment by ivankravets** [comment] 2017-06-27 22:14
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/653

**Closed by ivankravets** 2017-06-27 22:14 UTC
