### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by 2DRobotics** [platformio/platformio-atom-ide#1423] opened 2018-01-23 11:00 UTC
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\DINH DAO\.platformio\.cache\tmp-3448XRVuAB6VKwk5\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\DINH DAO\.platformio\.cache\tmp-3448XRVuAB6VKwk5\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\DINH DAO\.platformio\.cache\tmp-3448XRVuAB6VKwk5\virtualenv-14.0.6\virtualenv.py", line 904, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "C:\Users\DINH DAO\.platformio\.cache\tmp-3448XRVuAB6VKwk5\virtualenv-14.0.6\virtualenv.py", line 1197, in install_python
    shutil.copyfile(executable, py_executable)
  File "C:\Python27\Lib\shutil.py", line 97, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: 'C:\\Users\\DINHDA~1\\PLATFO~1\\penv\\Scripts\\python.exe'

**Comment by ivankravets** [comment] 2018-01-30 12:18
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1407

**Closed by ivankravets** 2018-01-30 12:18 UTC
