### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir 'atom://about'

### ISSUE THREAD

**Issue by notnilk** [platformio/platformio-atom-ide#86] opened 2016-03-27 19:42 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.0
**System**: elementary OS
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package, v1.1.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir 'atom://about'

```
At fs.js:813

Error: ENOENT: no such file or directory, scandir 'atom://about'
    at Error (native)
    at Object.fs.readdirSync (fs.js:813:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:454:28)
    at Object.ensureProjectsInited (/home/klin/.atom/packages/platformio-ide/lib/maintenance.js:53:29)
    at /home/klin/.atom/packages/platformio-ide/lib/main.js:202:19
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.removePath (/usr/share/atom/resources/app.asar/src/project.js:281:22)
    at TreeView.module.exports.TreeView.removeProjectFolder (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:1127:31)
    at space-pen-div.atom.commands.add.tree-view:remove-project-folder (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:349:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1019:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (/usr/share/atom/resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (/usr/share/atom/resources/atom.asar/renderer/api/lib/remote.js:143:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/usr/share/atom/resources/app.asar/src/context-menu-manager.js:172:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (/usr/share/atom/resources/app.asar/src/window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -7:34.3.0 platformio-ide-terminal:new (textarea.)
     -0:00.7.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "platformio-ide": {}
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.4.5
atom-material-ui, v1.2.10
autocomplete-clang, v0.8.9
build, v0.58.0
language-ini, v1.15.0
linter, v1.11.4
linter-gcc, v0.6.8
platformio-aia, v0.0.5
platformio-ide, v1.1.0
platformio-ide-terminal, v2.0.3
tool-bar, v0.4.0

# Dev
No dev packages
```

**Comment by orgkhnargh** [comment] 2016-03-27 19:45
Duplicate of #80. Fix will arrive with version 1.1.1.

**Closed by orgkhnargh** 2016-03-27 19:45 UTC
