### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by Francisco420** [platformio/platformio-atom-ide#1649] opened 2018-03-17 22:32 UTC
PIP: Error: spawn /Users/franciscofonseca 1/.platformio/penv/bin/pip ENOENT

**Comment by ivankravets** [comment] 2018-06-20 18:43
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1243

**Closed by ivankravets** 2018-06-20 18:43 UTC
