### ISSUE TITLE
PIP: Error: spawn /Volumes/Macintosh HD/Users/(Username)/.platformio/penv/bin/pip ENOENT - Help

### ISSUE THREAD

**Issue by lanky8804** [platformio/platformio-atom-ide#1528] opened 2018-02-18 12:44 UTC
Getting this error:
PIP: Error: spawn /Volumes/Macintosh HD/Users/(Username)/.platformio/penv/bin/pip ENOENT

Have surfed internet and tried various solutions with no fix, have removed everything including hidden folder and completed fresh install and still same error.

Running High Sierra.

Anyone able to help??

**Comment by ivankravets** [comment] 2018-06-20 18:44
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1243

**Closed by ivankravets** 2018-06-20 18:44 UTC
