### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by Alexvrs** [platformio/platformio-atom-ide#952] opened 2017-09-16 18:04 UTC
Error: Traceback (most recent call last):
  File "/Users/Alexvrs/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py", line 120, in main
    cli(None, None, None)
  File "/Users/Alexvrs/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Alexvrs/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/Alexvrs/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Alexvrs/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Alexvrs/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/Alexvrs/.platformio/penv/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/Alexvrs/.platformio/penv/lib/python2.7/site-packages/platformio/commands/init.py", line 102, in cli
    pg = ProjectGenerator(project_dir, ide, env_name)
  File "/Users/Alexvrs/.platformio/penv/lib/python2.7/site-packages/platformio/ide/projectgenerator.py", line 39, in __init__
    self._gather_tplvars()
  File "/Users/Alexvrs/.platformio/penv/lib/python2.7/site-packages/platformio/ide/projectgenerator.py", line 152, in _gather_tplvars
    self._tplvars.update(self.get_project_build_data())
  File "/Users/Alexvrs/.platformio/penv/lib/python2.7/site-packages/platformio/util.py", line 135, in __call__
    value = self.func(*args)
  File "/Users/Alexvrs/.platformio/penv/lib/python2.7/site-packages/platformio/ide/projectgenerator.py", line 74, in get_project_build_data
    target=["idedata"])
  File "/Users/Alexvrs/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/Alexvrs/.platformio/penv/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/Alexvrs/.platformio/penv/lib/python2.7/site-packages/platformio/commands/run.py", line 109, in cli
    result = (envname, ep.process())
  File "/Users/Alexvrs/.platformio/penv/lib/python2.7/site-packages/platformio/commands/run.py", line 193, in process
    result = self._run()
  File "/Users/Alexvrs/.platformio/penv/lib/python2.7/site-packages/platformio/commands/run.py", line 284, in _run
    self.verbose)
  File "/Users/Alexvrs/.platformio/penv/lib/python2.7/site-packages/platformio/commands/run.py", line 307, in _autoinstall_libdeps
    ctx.invoke(cmd_lib_install, libraries=[lib], silent=not verbose)
  File "/Users/Alexvrs/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/Alexvrs/.platformio/penv/lib/python2.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/Alexvrs/.platformio/penv/lib/python2.7/site-packages/platformio/commands/lib.py", line 100, in lib_install
    lm.install(library, silent=silent, interactive=interactive)
  File "/Users/Alexvrs/.platformio/penv/lib/python2.7/site-packages/platformio/managers/lib.py", line 252, in install
    trigger_event)
  File "/Users/Alexvrs/.platformio/penv/lib/python2.7/site-packages/platformio/managers/package.py", line 630, in install
    pkg_dir = self._install_from_piorepo(name, requirements)
  File "/Users/Alexvrs/.platformio/penv/lib/python2.7/site-packages/platformio/managers/lib.py", line 231, in _install_from_piorepo
    dl_data['url'], requirements)
  File "/Users/Alexvrs/.platformio/penv/lib/python2.7/site-packages/platformio/managers/package.py", line 363, in _install_from_url
    dlpath = self.download(url, tmp_dir, sha1)
  File "/Users/Alexvrs/.platformio/penv/lib/python2.7/site-packages/platformio/managers/package.py", line 173, in download
    fd = FileDownloader(url, dest_dir)
  File "/Users/Alexvrs/.platformio/penv/lib/python2.7/site-packages/platformio/downloader.py", line 56, in __init__
    self.set_destination(join(dest_dir, self._fname))
  File "/Users/Alexvrs/.platformio/penv/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 38: ordinal not in range(128)

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by ivankravets** [comment] 2017-10-17 13:58
Duplicate of #812

**Closed by ivankravets** 2017-10-17 13:58 UTC
