### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by elishae38** [platformio/platformio-atom-ide#843] opened 2017-08-15 03:40 UTC
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\wong\.platformio\.cache-ide\tmp-108888KUzZgo3yQ2o\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\wong\.platformio\.cache-ide\tmp-108888KUzZgo3yQ2o\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\wong\.platformio\.cache-ide\tmp-108888KUzZgo3yQ2o\virtualenv-14.0.6\virtualenv.py", line 924, in create_environment
    download=download,
  File "C:\Users\wong\.platformio\.cache-ide\tmp-108888KUzZgo3yQ2o\virtualenv-14.0.6\virtualenv.py", line 877, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "C:\Users\wong\.platformio\.cache-ide\tmp-108888KUzZgo3yQ2o\virtualenv-14.0.6\virtualenv.py", line 783, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command C:\Users\wong\.platf...v\Scripts\python.exe -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 2

**Comment by elishae38** [comment] 2017-08-15 03:41
Virtualenv Create: Traceback (most recent call last):
File "C:\Users\wong.platformio.cache-ide\tmp-108888KUzZgo3yQ2o\virtualenv-14.0.6\virtualenv.py", line 2304, in 
main()
File "C:\Users\wong.platformio.cache-ide\tmp-108888KUzZgo3yQ2o\virtualenv-14.0.6\virtualenv.py", line 705, in main
symlink=options.symlink)
File "C:\Users\wong.platformio.cache-ide\tmp-108888KUzZgo3yQ2o\virtualenv-14.0.6\virtualenv.py", line 924, in create_environment
download=download,
File "C:\Users\wong.platformio.cache-ide\tmp-108888KUzZgo3yQ2o\virtualenv-14.0.6\virtualenv.py", line 877, in install_wheel
call_subprocess(cmd, show_stdout=False, extra_env=env)
File "C:\Users\wong.platformio.cache-ide\tmp-108888KUzZgo3yQ2o\virtualenv-14.0.6\virtualenv.py", line 783, in call_subprocess
% (cmd_desc, proc.returncode))
OSError: Command C:\Users\wong.platf...v\Scripts\python.exe -c "import sys, pip; sys...d"] + sys.argv[1:]))" setuptools pip wheel failed with error code 2

**Comment by ivankravets** [comment] 2017-10-17 15:34
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/703

**Closed by ivankravets** 2017-10-17 15:34 UTC

**Comment by ivankravets** [comment] 2017-10-17 15:39
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

What is your Windows OS version? Locale?
