### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by JensKapmeyer** [platformio/platformio-atom-ide#2005] opened 2018-07-11 22:35 UTC
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.1
PIO IDE: v2.1.7
System: Windows_NT, 6.1.7601, x64

# Exception
```
Der Befehl "platformio" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Error: spawn platformio ENOENT
```

**Comment by ivankravets** [comment] 2018-07-17 13:55
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1243

**Closed by ivankravets** 2018-07-17 13:55 UTC
