### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by ykevin** [platformio/platformio-atom-ide#1831] opened 2018-05-11 01:32 UTC
PIP: ϵͳ�Ҳ���ָ����·����
Error: spawn C:\Users\riki\.platformio\penv\Scripts\pip ENOENT

**Comment by ivankravets** [comment] 2018-06-20 18:42
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1243

**Closed by ivankravets** 2018-06-20 18:42 UTC
