### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by stefanbode** [platformio/platformio-atom-ide#1376] opened 2018-01-11 17:16 UTC
Error: Could not install 'toolchain-xtensa' with version requirements '~1.40802.0' for your system 'windows_x86'.
More details: http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment] 2018-01-11 20:35
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1238

Please try solution 2 or 3

**Closed by ivankravets** 2018-01-11 20:35 UTC
