### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by akhilmagotra** [platformio/platformio-atom-ide#1029] opened 2017-10-14 17:09 UTC
Error: Status 'PlatformIO: Rebuilding C/C++ Project Index for /Users/akhil/Downloads/Sonoff-Tasmota-development' is already set
    at Registry.statusAdd (/Users/akhil/.atom/packages/busy-signal/lib/registry.js:50:13)
    at /Users/akhil/.atom/packages/busy-signal/lib/registry.js:31:12
    at Function.module.exports.Emitter.simpleDispatch (/private/var/folders/nh/732m3t3x73l_c1bgzhj0mx4c0000gn/T/AppTranslocation/896800EF-2609-4A8D-8452-FDC41725027D/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/private/var/folders/nh/732m3t3x73l_c1bgzhj0mx4c0000gn/T/AppTranslocation/896800EF-2609-4A8D-8452-FDC41725027D/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Provider.add (/Users/akhil/.atom/packages/busy-signal/lib/provider.js:21:18)
    at beginBusy (/Users/akhil/.atom/packages/platformio-ide/lib/services/busy.js:25:20)
    at ProjectIndexer.<anonymous> (/Users/akhil/.atom/packages/platformio-ide/lib/project/indexer.js:158:7)
    at Generator.next (<anonymous>)
    at step (/Users/akhil/.atom/packages/platformio-ide/lib/project/indexer.js:11:273)
    at /Users/akhil/.atom/packages/platformio-ide/lib/project/indexer.js:11:443
    at ProjectIndexer.<anonymous> (/Users/akhil/.atom/packages/platformio-ide/lib/project/indexer.js:11:99)

**Comment by ivankravets** [comment] 2017-10-17 12:21
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1013

**Closed by ivankravets** 2017-10-17 12:21 UTC
