### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by mihailShumilov** [platformio/platformio-atom-ide#1330] opened 2017-12-31 12:28 UTC
Error: [Sun Dec 31 14:26:53 2017] Processing nucleo_f446re (platform: ststm32; board: nucleo_f446re; framework: mbed)
--------------------------------------------------------------------------------
PackageManager: Installing toolchain-gccarmnoneeabi @ >=1.60301.0
Downloading...
Unpacking...
Verbose mode can be enabled via `-v, --verbose` option
IOError: [Errno 2] No such file or directory: '/Users/godson/.platformio/packages/_tmp_installing-IiCVOq-package/platformio/variants_remap.json':
File "/Users/godson/.platformio/penv/lib/python2.7/site-packages/platformio/builder/main.py", line 158:
env.SConscript("$BUILD_SCRIPT")
File "/Users/godson/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py", line 541:
return _SConscript(self.fs, *files, **subst_kw)
File "/Users/godson/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py", line 250:
exec _file_ in call_stack[-1].globals
File "/Users/godson/.platformio/platforms/ststm32/builder/main.py", line 181:
target_elf = env.BuildProgram()
File "/Users/godson/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py", line 224:
return self.method(*nargs, **kwargs)
File "/Users/godson/.platformio/penv/lib/python2.7/site-packages/platformio/builder/tools/platformio.py", line 58:
env.BuildFrameworks(env.get("PIOFRAMEWORK"))
File "/Users/godson/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py", line 224:
return self.method(*nargs, **kwargs)
File "/Users/godson/.platformio/penv/lib/python2.7/site-packages/platformio/builder/tools/platformio.py", line 260:
SConscript(env.GetFrameworkScript(f))
File "/Users/godson/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py", line 604:
return method(*args, **kw)
File "/Users/godson/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py", line 541:
return _SConscript(self.fs, *files, **subst_kw)
File "/Users/godson/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py", line 250:
exec _file_ in call_stack[-1].globals
File "/Users/godson/.platformio/platforms/ststm32/builder/frameworks/mbed/mbed.py", line 93:
join(FRAMEWORK_DIR, "platformio", "variants_remap.json"))
File "/Users/godson/.platformio/penv/lib/python2.7/site-packages/platformio/util.py", line 189:
with open(file_path, "r") as f:
========================== [ERROR] Took 66.41 seconds ==========================

**Comment by ivankravets** [comment] 2018-01-06 11:34
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1329

**Closed by ivankravets** 2018-01-06 11:34 UTC
