### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by usatenko** [platformio/platformio-atom-ide#1062] opened 2017-10-22 20:00 UTC
Virtualenv Create: Traceback (most recent call last):
  File "/home/au/.platformio/.cache/tmp-27531g07t8NyTXLP5/virtualenv-14.0.6/virtualenv.py", line 2304, in <module>
    main()
  File "/home/au/.platformio/.cache/tmp-27531g07t8NyTXLP5/virtualenv-14.0.6/virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "/home/au/.platformio/.cache/tmp-27531g07t8NyTXLP5/virtualenv-14.0.6/virtualenv.py", line 904, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/home/au/.platformio/penv/lib/python2.7/posixpath.py", line 360, in abspath
    if not isabs(path):
  File "/home/au/.platformio/penv/lib/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'

Happens on every start of atom.
Tried removing penv folder.
~/.platformio/.cache$ pip -V
pip 9.0.1 from /home/au/.local/lib/python2.7/site-packages (python 2.7)

**Comment by ivankravets** [comment] 2017-11-06 15:26
Please provide an output from a system Terminal
```
echo $PATH
echo $PYTHONPATH
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment] 2017-11-06 15:31
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1063

**Closed by ivankravets** 2017-11-06 15:31 UTC
