### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by shiohiyoko** [platformio/platformio-atom-ide#1639] opened 2018-03-15 12:35 UTC
Traceback (most recent call last):
  File "C:\Users\Yuya315\.platformio\penv\Scripts\platformio-script.py", line 6, in <module>
  File "c:\users\yuya315\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 3147, in <module>
    @_call_aside
  File "c:\users\yuya315\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 3131, in _call_aside
    f(*args, **kwargs)
  File "c:\users\yuya315\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 3160, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\users\yuya315\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "c:\users\yuya315\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\users\yuya315\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'platformio==3.5.3a1' distribution was not found and is required by the application

**Comment by ivankravets** [comment] 2018-06-21 09:41
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1304

**Closed by ivankravets** 2018-06-21 09:41 UTC
