### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by liubo-chongqing** [platformio/platformio-atom-ide#1765] opened 2018-04-16 09:51 UTC
Error: Failed to download file https://pypi.python.org/packages/source/v/virtualenv/virtualenv-14.0.6.tar.gz: Error: EPERM: operation not permitted, open 'C:\.platformio\.cache\virtualenv.tar.gz'
    at _callee$ (C:\Users\刘波\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:2679:19)
    at tryCatch (C:\Users\刘波\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:836:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\刘波\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1070:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\刘波\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:888:21)
    at step (C:\Users\刘波\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:2781:191)
    at C:\Users\刘波\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:2781:402

**Comment by ivankravets** [comment] 2018-04-19 20:51
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1674

**Closed by ivankravets** 2018-04-19 20:51 UTC
