### ISSUE TITLE
Platform command failed: platform install linux_arm@1.4.4

### ISSUE THREAD

**Issue by ladidadida** [platformio/platformio-atom-ide#729] opened 2017-07-14 17:45 UTC
I was facing a problem when installing PlatformIO on a freshly installed Atom 1.18.0. I tried installing the Platform Linux ARM for cross developing for a RaspberryPi. I tried it on my two machines, a Laptop (i686) running Ubuntu Gnome 17.04, and a stationary Computer (x86_64) running the same OS. 

I also tried installing the older package 1.3.0.

The error output for 1.4.4 on my x86_64 machine is:

Error: Error: Could not find a version that satisfies the requirement '~1.40802.0' for your system 'linux_x86_64'

    at /home/stefan/.atom/packages/platformio-ide/lib/platform/helpers.js:61:25
    at onExit (/home/stefan/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/home/stefan/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/opt/atom/resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (/opt/atom/resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

Just for proof: uname -rm => 4.10.0-26-generic x86_64

**Comment by ivankravets** [comment] 2017-08-04 18:22
Duplicate of https://github.com/platformio/platform-linux_arm/issues/2

**Closed by ivankravets** 2017-08-04 18:22 UTC
