### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by Arshad1024** [platformio/platformio-atom-ide#972] opened 2017-09-22 15:36 UTC
Virtualenv Create:   File "C:\Users\Arshad\AppData\Local\Programs\Python\Python36\Lib\site.py", line 177
    file=sys.stderr)
        ^
SyntaxError: invalid syntax

**Comment by ivankravets** [comment] 2017-10-17 20:28
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/922

**Closed by ivankravets** 2017-10-17 20:28 UTC
