### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by actus7** [platformio/platformio-atom-ide#2020] opened 2018-07-17 01:52 UTC
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.2
PIO IDE: v2.1.7
System: Windows_NT, 10.0.17134, x64

# Exception
```
'platformio' n�o � reconhecido como um comando interno
ou externo, um programa oper�vel ou um arquivo em lotes.
Error: spawn platformio ENOENT
```

**Comment by ivankravets** [comment] 2018-07-17 13:55
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1243

**Closed by ivankravets** 2018-07-17 13:55 UTC
