### ISSUE TITLE
Problem has been occured while installing PlatformIO IDE.

### ISSUE THREAD

**Issue by tchisaka** [platformio/platformio-atom-ide#1391] opened 2018-01-14 23:06 UTC
Error: Cloning https://github.com/platformio/platformio-atom-ide.git failed
Installing modules done
Cannot read property 'getReferenceTarget' of null

    at C:\Users\takamasa\.atom\packages\platformio-ide\lib\installer\ide.js:66:84
    at Generator.throw (<anonymous>)
    at step (C:\Users\takamasa\.atom\packages\platformio-ide\lib\installer\ide.js:89:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment] 2018-01-16 18:40
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1394

**Closed by ivankravets** 2018-01-16 18:40 UTC
