### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by Freakshowdevil** [platformio/platformio-atom-ide#2186] opened 2019-04-19 08:13 UTC
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.36.0
PIO IDE: v2.3.1
System: Windows_NT, 10.0.17763, x64

# Exception
```
Error: Error: Detected unknown package 'contrib-pysite'

    at C:\Users\victo\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:15270
    at ChildProcess.h (C:\Users\victo\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:5904)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at ChildProcess.cp.emit (C:\Users\victo\.atom\packages\platformio-ide\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

**Comment by ivankravets** [comment] 2019-04-19 09:01
Duplicate of https://github.com/platformio/platformio-core/issues/2341

**Closed by ivankravets** 2019-04-19 09:01 UTC
