### ISSUE TITLE
Problem has been occured while installing PlatformIO IDE.

### ISSUE THREAD

**Issue by pzaepfel** [platformio/platformio-atom-ide#1483] opened 2018-02-04 20:21 UTC
Error: Uninstalling platformio-ide failed
Failed to delete platformio-ide: ENOENT: no such file or directory, rmdir 'C:\Users\pzaep\.atom\packages\platformio-ide\lib'

    at C:\Users\pzaep\.atom\packages\platformio-ide\lib\installer\ide.js:66:84
    at Generator.throw (<anonymous>)
    at step (C:\Users\pzaep\.atom\packages\platformio-ide\lib\installer\ide.js:89:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment] 2018-02-05 23:37
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1394

**Closed by ivankravets** 2018-02-05 23:37 UTC
