### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/Desktop/github test'

### ISSUE THREAD

**Issue by hussamalbahadli** [platformio/platformio-atom-ide#1905] opened 2018-06-12 11:09 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Deepin 15.5
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.1.4

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/home/hussam/Desktop/github test'

```
At fs.js:961

Error: ENOENT: no such file or directory, lstat '/home/hussam/Desktop/github test'
    at fs.lstatSync (fs.js:961:11)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
    at Proxy.realpathSync (fs.js:1641:21)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:321:29)
    at /packages/platformio-ide/lib/project/helpers.js:32:25
    at getActivePioProject (/packages/platformio-ide/lib/project/helpers.js:36:6)
    at Object.highlightActiveProject (/packages/platformio-ide/lib/maintenance.js:133:13)
    at doHighlight (/packages/platformio-ide/lib/main.js:247:43)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at stoppedChangingActivePaneItemTimeout.setTimeout (/usr/share/atom/resources/app/src/workspace.js:493:26)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.32.5 
atom-eclipse-syntax 0.0.6 
autocomplete-clang 0.11.4 
autumn-highlighter-syntax 1.13.0 
blackboard 1.0.2 
blackboard-dark-mod 0.2.0 
build 0.70.0 
busy-signal 1.4.3 
city-lights-syntax 1.1.8 
city-lights-ui 1.3.3 
file-icons 2.1.21 
intentions 1.1.5 
jackhammer-syntax 1.1.0 
language-ini 1.20.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
material-ui 1.0.10 
monokai-blackboard 0.3.0 
platformio-ide 2.1.4 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.8.1 
redui-jm-syntax 1.4.0 
styri-syntax 0.2.0 
tool-bar 1.1.7 
```

**Comment by ivankravets** [comment] 2018-06-20 18:39
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1472

**Closed by ivankravets** 2018-06-20 18:39 UTC
