### ISSUE TITLE
Problem occured while upgrading PlatformIO IDE

### ISSUE THREAD

**Issue by kimfrellsen** [platformio/platformio-atom-ide#1373] opened 2018-01-11 08:29 UTC
Error: The system cannot find the path specified.
Error: spawn C:\Users\frellsen01\AppData\Local\atom\app-1.23.3\resources\app\apm\node_modules\atom-package-manager\bin\apm.cmd ENOENT
    at file:///C:/Users/frellsen01/.atom/packages/platformio-ide/lib/installer/ide.js:59:9
    at Generator.throw (<anonymous>)
    at step (file:///C:/Users/frellsen01/.atom/packages/platformio-ide/lib/installer/ide.js:176:2)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment] 2018-01-11 12:16
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1334

**Closed by ivankravets** 2018-01-11 12:16 UTC
