### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by palaciodepego** [platformio/platformio-atom-ide#1439] opened 2018-01-27 08:23 UTC
Error: Could not install 'toolchain-xtensa32' with version requirements '~2.50200.0' for your system 'windows_amd64'.
More details: http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment] 2018-01-27 22:37
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1393

**Closed by ivankravets** 2018-01-27 22:37 UTC
