### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by Dyjiro** [platformio/platformio-atom-ide#1465] opened 2018-01-31 20:48 UTC
Error: [01/31/18 13:48:07] Processing megaatmega2560 (platform: atmelavr; board: megaatmega2560; framework: arduino)

SCons import failed. Unable to find engine files in:
C:\Users\K\AppData\Roaming\SPB_Data\.platformio\packages\tool-scons@2.20501.3\script\..\engine
C:\Users\K\AppData\Roaming\SPB_Data\.platformio\packages\tool-scons@2.20501.3\script\scons-local-2.5.1
C:\Users\K\AppData\Roaming\SPB_Data\.platformio\packages\tool-scons@2.20501.3\script\scons-local
c:\users\k\appdata\roaming\spb_data\.platformio\penv\scons-2.5.1
c:\users\k\appdata\roaming\spb_data\.platformio\penv\Lib\site-packages\scons-2.5.1
c:\users\k\appdata\roaming\spb_data\.platformio\penv\scons
c:\users\k\appdata\roaming\spb_data\.platformio\penv\Lib\site-packages\scons
Traceback (most recent call last):
File "C:\Users\K\AppData\Roaming\SPB_Data\.platformio\packages\tool-scons@2.20501.3\script\scons", line 190, in <module>
ImportError: No module named SCons.Script
 [ERROR] Took 0.26 seconds

**Comment by ivankravets** [comment] 2018-02-17 16:35
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1433

**Closed by ivankravets** 2018-02-17 16:35 UTC
