### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by vianaismaelreis** [platformio/platformio-atom-ide#899] opened 2017-09-02 19:53 UTC
Traceback (most recent call last):
File "C:\Users\Ismael\.platformio\packages\_tmp_installing-gsspqu-package\script\scons", line 190, in <module>
import SCons.Script
ImportError: No module named SCons.Script

 [ERROR] Took 0.85 seconds

**Comment by ivankravets** [comment] 2017-09-06 11:40
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/826

**Closed by ivankravets** 2017-09-06 11:40 UTC
