### ISSUE TITLE
Platform command failed: platform install linux_arm

### ISSUE THREAD

**Issue by justicemd5** [platformio/platformio-atom-ide#375] opened 2017-04-15 12:26 UTC
Error: Error: Could not find a version that satisfies the requirement '~1.40802.0' for your system 'linux_x86_64'

    at /home/mp/.atom/packages/platformio-ide/lib/platform/helpers.js:61:25
    at onExit (/home/mp/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/home/mp/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:299:11)
    at ChildProcess.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:329:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment] 2017-04-30 21:30
Duplicate of https://github.com/platformio/platform-linux_arm/issues/2

**Closed by ivankravets** 2017-04-30 21:30 UTC
Labels: duplicate
