### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by ilhampe** [platformio/platformio-atom-ide#1544] opened 2018-02-23 06:54 UTC
Error: Could not install 'espressif8266' with version requirements '*' for your system 'darwin_x86_64'.

Please try this solution -> http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment] 2018-06-20 18:47
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1171

**Closed by ivankravets** 2018-06-20 18:47 UTC
