### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by navyatippa** [platformio/platformio-atom-ide#1461] opened 2018-01-31 06:52 UTC
Error: [01/31/18 11:55:31] Processing esp32doit-devkit-v1 (platform: espressif32; board: esp32doit-devkit-v1; framework: arduino)

SCons import failed. Unable to find engine files in:
C:\Users\Naveen_atl\.platformio\packages\tool-scons\script\..\engine
C:\Users\Naveen_atl\.platformio\packages\tool-scons\script\scons-local-2.5.1
C:\Users\Naveen_atl\.platformio\packages\tool-scons\script\scons-local
c:\users\naveen_atl\.platformio\penv\scons-2.5.1
c:\users\naveen_atl\.platformio\penv\Lib\site-packages\scons-2.5.1
c:\users\naveen_atl\.platformio\penv\scons
c:\users\naveen_atl\.platformio\penv\Lib\site-packages\scons
Traceback (most recent call last):
File "C:\Users\Naveen_atl\.platformio\packages\tool-scons\script\scons", line 190, in <module>
import SCons.Script
File "C:\Users\Naveen_atl\.platformio\packages\tool-scons\script\..\engine\SCons\__init__.py", line 43, in <module>
import SCons.compat
ImportError: No module named compat
 [ERROR] Took 0.94 seconds

**Comment by navyatippa** [comment] 2018-01-31 06:53
what is the issue?
how to resolve help me

**Comment by ivankravets** [comment] 2018-02-17 16:20
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1512

**Closed by ivankravets** 2018-02-17 16:20 UTC
