### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by kristsm** [platformio/platformio-atom-ide#1342] opened 2018-01-04 06:47 UTC
Error: Could not install 'toolchain-xtensa32' with version requirements '~2.50200.0' for your system 'windows_amd64'.
 If you use Antivirus, it can block PlatformIO Package Manager. Try to disable it for a while.

**Comment by ivankravets** [comment] 2018-01-10 20:13
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1171

**Closed by ivankravets** 2018-01-10 20:13 UTC
