### ISSUE TITLE
Add option to *not* generate "lib" + travis files/folders

### ISSUE THREAD

**Issue by ctron** [platformio/platformio-atom-ide#1242] opened 2017-12-06 09:15 UTC
Every time I add an existing PIO project to the Atom editor it adds:
* lib/*
* .gitignore
* .travis.yml

Deleting them doesn't work as they get re-created the next time I make a change in the `platformio.ini` file.

**Comment by ivankravets** [comment] 2017-12-15 17:45
Duplicate of https://github.com/platformio/platformio-core/issues/446

**Closed by ivankravets** 2017-12-15 17:45 UTC
