### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by jygatech** [platformio/platformio-atom-ide#987] opened 2017-09-25 18:47 UTC
Error: Error: Failed to download file examples.tar.gz
    at ProjectExamplesStage.<anonymous> (file:///C:/Users/Andre/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at Generator.throw (<anonymous>)
    at step (C:\Users\Andre\.atom\packages\platformio-ide\lib\installer\stages\project-examples.js:13:273)

**Comment by ivankravets** [comment] 2017-10-17 12:25
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/934

**Closed by ivankravets** 2017-10-17 12:25 UTC
