### ISSUE TITLE
Uncaught Error: Could not start PIO Home server: Error: spawn platformio ENOENT

### ISSUE THREAD

**Issue by vitaltr** [platformio/platformio-atom-ide#1295] opened 2017-12-21 11:58 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.0.0-rc.4

### Stack Trace

Uncaught Error: Could not start PIO Home server: Error: spawn platformio ENOENT

```
At C:\Users\x\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1571

Error: Could not start PIO Home server: Error: spawn platformio ENOENT
    at /packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1571:23
    at onExit (/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:499:5)
    at /packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:481:7)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at ChildProcess.cp.emit (/packages/platformio-ide/node_modules/cross-spawn/lib/enoent.js:40:29)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.15 
autocomplete-clang 0.11.4 
build 0.69.0 
busy-signal 1.4.3 
file-icons 2.1.15 
intentions 1.1.5 
language-ini 1.19.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.6.10 
platformio-ide 2.0.0-rc.4 
platformio-ide-debugger 1.2.4 
platformio-ide-terminal 2.7.0 
tool-bar 1.1.0 
```

**Comment by ivankravets** [comment] 2017-12-22 10:10
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1243

**Closed by ivankravets** 2017-12-22 10:10 UTC
