### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by duypv** [platformio/platformio-atom-ide#704] opened 2017-07-07 02:54 UTC
Virtualenv Create: Traceback (most recent call last):
  File "/Users/duy/.platformio/.cache-ide/tmp-3989OBGj04STnZxk/virtualenv-14.0.6/virtualenv.py", line 2304, in <module>

    main()
  File "/Users/duy/.platformio/.cache-ide/tmp-3989OBGj04STnZxk/virtualenv-14.0.6/virtualenv.py", line 705, in main

    symlink=options.symlink)

  File "/Users/duy/.platformio/.cache-ide/tmp-3989OBGj04STnZxk/virtualenv-14.0.6/virtualenv.py", line 904, in create_environment

    site_packages=site_packages, clear=clear, symlink=symlink))

  File "/Users/duy/.platformio/penv/lib/python2.7/posixpath.py", line 360, in abspath

    if not isabs(path):
  File "/Users/duy/.platformio/penv/lib/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')

AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by ivankravets** [comment] 2017-08-04 17:21
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/681

**Closed by ivankravets** 2017-08-04 17:21 UTC
