### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by JEOVADJ** [platformio/platformio-atom-ide#1331] opened 2017-12-31 21:04 UTC
Traceback (most recent call last):
  File "C:\Users\Jeova\.platformio\penv\Scripts\platformio-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 3017, in <module>
    @_call_aside
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 659, in _build_master
    ws.require(__requires__)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 853, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'platformio==3.5.1a1' distribution was not found and is required by the application

**Comment by ivankravets** [comment] 2018-01-06 11:35
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1304

**Closed by ivankravets** 2018-01-06 11:35 UTC
