### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by Sanada4real** [platformio/platformio-atom-ide#2072] opened 2018-09-17 02:41 UTC
Error: Failed to download file https://github.com/platformio/platformio/archive/develop.zip: 
    at _callee$ (C:\Users\victo\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:2654:19)
    at tryCatch (C:\Users\victo\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:832:40)
    at Generator.invoke [as _invoke] (C:\Users\victo\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1066:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\victo\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:884:21)
    at step (C:\Users\victo\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:2756:191)
    at C:\Users\victo\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:2756:361

**Comment by ivankravets** [comment] 2018-09-21 16:58
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/2065

**Closed by ivankravets** 2018-09-21 16:58 UTC
