### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/Documents/PlatformIO/Projects/Auto_Au...

### ISSUE THREAD

**Issue by federico1998** [platformio/platformio-atom-ide#1898] opened 2018-06-09 14:33 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Ubuntu 16.04.4
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.1.4

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/home/federico98/Documents/PlatformIO/Projects/Auto_Autonomo'

```
At fs.js:961

Error: ENOENT: no such file or directory, lstat '/home/federico98/Documents/PlatformIO/Projects/Auto_Autonomo'
    at fs.lstatSync (fs.js:961:11)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
    at Proxy.realpathSync (fs.js:1641:21)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:321:29)
    at /packages/platformio-ide/lib/maintenance.js:139:39
    at Array.forEach (native)
    at Object.highlightActiveProject (/packages/platformio-ide/lib/maintenance.js:135:8)
    at doHighlight (/packages/platformio-ide/lib/main.js:247:43)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Project.setPaths (/usr/share/atom/resources/app/src/project.js:336:24)
    at RootDragAndDropHandler.module.exports.RootDragAndDropHandler.onDrop (/usr/share/atom/resources/app/node_modules/tree-view/lib/root-drag-and-drop.js:194:37)
    at RootDragAndDropHandler.onDrop (/usr/share/atom/resources/app/node_modules/tree-view/lib/root-drag-and-drop.js:3:65)
```

### Commands

```
  2x -8:08.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  4x -3:47.5.0 tree-view:move (span.name.icon.icon-file-directory)
     -3:26.6.0 tree-view:remove (span.name.icon.icon-file-directory)
     -2:34.9.0 platformio-ide:target:build (div.tool-panel.tree-view)
  3x -2:01.3.0 tree-view:remove (span.name.icon.icon-file-directory)
     -0:45.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
autocomplete-clang 0.11.4 
build 0.70.0 
busy-signal 1.4.3 
file-icons 2.1.21 
intentions 1.1.5 
language-ini 1.20.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
platformio-ide 2.1.4 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.8.1 
tool-bar 1.1.7 
```

**Comment by ivankravets** [comment] 2018-06-20 18:39
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1472

**Closed by ivankravets** 2018-06-20 18:39 UTC
