### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by Zoldex** [platformio/platformio-atom-ide#1509] opened 2018-02-11 20:25 UTC
Traceback (most recent call last):
  File "C:\Users\sergi\.platformio\penv\Scripts\platformio-script.py", line 11, in <module>
    load_entry_point('platformio==3.5.2b2', 'console_scripts', 'platformio')()
  File "c:\users\sergi\.platformio\penv\lib\site-packages\platformio\__main__.py", line 126, in main
    error_str += str(e)
  File "c:\users\sergi\.platformio\penv\lib\site-packages\platformio\exception.py", line 23, in __str__
    return Exception.__str__(self)
UnicodeEncodeError: 'ascii' codec can't encode character u'\ufffd' in position 314: ordinal not in range(128)

**Comment by ivankravets** [comment] 2018-02-17 16:32
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1228

**Closed by ivankravets** 2018-02-17 16:32 UTC
