### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by adrian622oke** [platformio/platformio-atom-ide#258] opened 2017-03-09 17:38 UTC
Error: Error: ENOENT: no such file or directory, open 'C:\Users\adria\.atom\packages\platformio-ide\.cache\examples.tar.gz'

**Comment by ivankravets** [comment] 2017-03-09 20:04
Could you reproduce this issue after Atom restart?

**Comment by ivankravets** [comment] 2017-03-10 11:27
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/254

**Closed by ivankravets** 2017-03-10 11:27 UTC
Labels: help wanted
