### ISSUE TITLE
InstallationManager: Error: unexpected end of file

### ISSUE THREAD

**Issue by twaider** [platformio/platformio-atom-ide#344] opened 2017-04-07 14:21 UTC
Error: Error: unexpected end of file
    at ProjectExamplesStage.<anonymous> (file:///C:/Users/twaider/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at throw (<anonymous>)
    at step (C:\Users\twaider\.atom\packages\platformio-ide\lib\installer\stages\project-examples.js:13:273)

**Comment by ivankravets** [comment] 2017-05-06 12:58
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/284

**Closed by ivankravets** 2017-05-06 12:58 UTC
Labels: bug, duplicate
