### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by 18073117401** [platformio/platformio-atom-ide#850] opened 2017-08-17 15:14 UTC
Traceback (most recent call last):
File "C:\Users\Administrator\.platformio\packages\tool-scons\script\scons", line 190, in <module>

import SCons.Script
File "C:\Users\Administrator\.platformio\packages\tool-scons\script\..\engine\SCons\__init__.py", line 43, in <module>
import SCons.compat
ImportError: No module named compat

 [ERROR] Took 0.36 seconds

**Comment by perfessor101** [comment] 2017-09-01 20:12
reinstalled ... installed via python ... updated anything and everything ... pythonIO hasn't been working for me in months

**Comment by ivankravets** [comment] 2017-09-06 11:40
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/826

**Closed by ivankravets** 2017-09-06 11:40 UTC
