### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by WhizzCat** [platformio/platformio-atom-ide#1735] opened 2018-04-08 16:17 UTC
PIP: sh: module: line 1: syntax error: unexpected end of file
sh: error importing function definition for `module'
sh: scl: line 1: syntax error: unexpected end of file
sh: error importing function definition for `scl'
Could not import setuptools which is required to install from a source distribution.
sh: module: line 1: syntax error: unexpected end of file
sh: error importing function definition for `module'
sh: scl: line 1: syntax error: unexpected end of file
sh: error importing function definition for `scl'

I've did a fresh installation of Fedora 27 and Atom. When installing PIO I get this error from Install PIO core.

I've seen a lot of things relating to this. Pip says setuptools is already installed. Python version is 2.7 in case that matters.

Anyone having any idea how to solve this? If you need more info, I'd be happy to oblige :)

-edit after skipping the error, PIO menu shows up, but I cannot build anything. Comes up with the same error when I try pio run in the terminal.

**Comment by ivankravets** [comment] 2018-06-20 18:50
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1729

**Closed by ivankravets** 2018-06-20 18:50 UTC
