### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by DodiGrabowski** [platformio/platformio-atom-ide#1717] opened 2018-04-04 18:57 UTC
Error: Traceback (most recent call last):
  File "/home/dodi/.platformio/penv/local/lib/python2.7/site-packages/platformio/__main__.py", line 120, in main
    cli(None, None, None)
  File "/home/dodi/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/dodi/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/dodi/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dodi/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 995, in _process_result
    **ctx.params)
  File "/home/dodi/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/dodi/.platformio/penv/local/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dodi/.platformio/penv/local/lib/python2.7/site-packages/platformio/__main__.py", line 80, in process_result
    maintenance.on_platformio_end(ctx, result)
  File "/home/dodi/.platformio/penv/local/lib/python2.7/site-packages/platformio/maintenance.py", line 52, in on_platformio_end
    check_platformio_upgrade()
  File "/home/dodi/.platformio/penv/local/lib/python2.7/site-packages/platformio/maintenance.py", line 242, in check_platformio_upgrade
    app.set_state_item("last_check", last_check)
  File "/home/dodi/.platformio/penv/local/lib/python2.7/site-packages/platformio/app.py", line 300, in set_state_item
    data[name] = value
  File "/home/dodi/.platformio/penv/local/lib/python2.7/site-packages/platformio/app.py", line 117, in __exit__
    self._unlock_state_file()
  File "/home/dodi/.platformio/penv/local/lib/python2.7/site-packages/platformio/app.py", line 135, in _unlock_state_file
    self._lockfile.release()
  File "/home/dodi/.platformio/penv/local/lib/python2.7/site-packages/lockfile/linklockfile.py", line 57, in release
    raise NotLocked("%s is not locked" % self.path)
NotLocked: /home/dodi/.platformio/appstate.json is not locked

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by ivankravets** [comment] 2018-06-21 09:40
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1707

**Closed by ivankravets** 2018-06-21 09:40 UTC
