### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '$ATOM_HOME/keymap.cson'

### ISSUE THREAD

**Issue by psamim** [platformio/platformio-atom-ide#1679] opened 2018-03-24 22:35 UTC
1. Install fresh Atom (without prior Atom configuration)
2. Install platformio
3. Go to "Open Your Keymap"

**Atom**: 1.25.0 x64
**Electron**: 1.8.4
**OS**: "Arch Linux"
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.1.3

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/home/samim/.atom/keymap.cson'

```
At fs.js:1669

Error: ENOENT: no such file or directory, lstat '/home/samim/.atom/keymap.cson'
    at Proxy.realpathSync (fs.js:1669:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:320:29)
    at /packages/platformio-ide/lib/project/helpers.js:32:25
    at getActivePioProject (/packages/platformio-ide/lib/project/helpers.js:36:6)
    at Object.highlightActiveProject (/packages/platformio-ide/lib/maintenance.js:133:13)
    at doHighlight (/packages/platformio-ide/lib/main.js:245:43)
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:141:28)
    at stoppedChangingActivePaneItemTimeout.setTimeout (/usr/lib/atom/src/workspace.js:477:20)
```

### Commands

```
     -0:20.8.0 core:move-down (div.tool-panel.tree-view)
     -0:20.4.0 tree-view:collapse-directory (div.tool-panel.tree-view)
     -0:20.1.0 tree-view:expand-item (div.tool-panel.tree-view)
  3x -0:19.5.0 core:move-down (div.tool-panel.tree-view)
     -0:17.5.0 window:reset-font-size (div.tool-panel.tree-view)
  2x -0:17 core:move-down (div.tool-panel.tree-view)
     -0:08.4.0 tree-view:unfocus (div.tool-panel.tree-view)
     -0:08.0 intentions:highlight (input.hidden-input)
     -0:07.9.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:06.7.0 editor:consolidate-selections (input.hidden-input)
     -0:06.7.0 core:cancel (input.hidden-input)
     -0:06.5.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -0:06.1.0 intentions:highlight (input.hidden-input)
     -0:05.6.0 command-palette:toggle (input.hidden-input)
     -0:04.0 core:confirm (input.hidden-input)
     -0:04.0 application:open-your-keymap (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.9.4 
autocomplete-clang 0.11.4 
build 0.70.0 
busy-signal 1.4.3 
file-icons 2.1.18 
ide-flowtype 0.22.1 
intentions 1.1.5 
language-ini 1.19.0 
linter 2.2.0 
linter-eslint 8.4.1 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
platformio-ide 2.1.3 
platformio-ide-debugger 1.2.5 
platformio-ide-terminal 2.8.1 
tool-bar 1.1.7 
vim-mode-plus 1.31.1 
```

**Comment by ivankravets** [comment] 2018-06-20 18:39
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1472

**Closed by ivankravets** 2018-06-20 18:39 UTC
