### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by piebat** [platformio/platformio-atom-ide#1443] opened 2018-01-27 10:17 UTC
Error: Could not install 'toolchain-xtensa32' with version requirements '~2.50200.0' for your system 'windows_amd64'.
More details: http://bit.ly/faq-package-manager

But by another end, seems it installed and work.

**Comment by ivankravets** [comment] 2018-01-27 22:33
Have you tried solutions from http://bit.ly/faq-package-manager?

**Comment by ivankravets** [comment] 2018-01-27 22:37
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1393

**Closed by ivankravets** 2018-01-27 22:37 UTC
Labels: help wanted
