### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by wjm0621** [platformio/platformio-atom-ide#503] opened 2017-05-25 13:43 UTC
C:\Users\AI_Lab\.platformio\packages\tool-scons\script\..\engine\SCons\Environment.py:1303: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
val = [x for x in val if x not in dk]

UnicodeDecodeError: 'utf8' codec can't decode byte 0xc1 in position 24: invalid start byte:
File "C:\Users\AI_Lab\.platformio\penv\lib\site-packages\platformio\builder\main.py", line 169:
print "\n%s\n" % json.dumps(env.DumpIDEData())
File "C:\Users\AI_Lab\.platformio\python27\Lib\json\__init__.py", line 244:
return _default_encoder.encode(obj)
File "C:\Users\AI_Lab\.platformio\python27\Lib\json\encoder.py", line 207:
chunks = self.iterencode(o, _one_shot=True)
File "C:\Users\AI_Lab\.platformio\python27\Lib\json\encoder.py", line 270:
return _iterencode(o, 0)
 [ERROR] Took 14.60 seconds

**Comment by ivankravets** [comment] 2017-05-27 10:53
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/512

**Closed by ivankravets** 2017-05-27 10:53 UTC
