### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by ricain59** [platformio/platformio-atom-ide#1973] opened 2018-07-02 22:20 UTC
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.0
PIO IDE: v2.1.7
System: Windows_NT, 6.1.7601, x64

# Exception
```
PIP: Command "python setup.py egg_info" failed with error code 1 in c:\users\ricain\.platformio\.cache\tmp-9816gcbsg1degk3f\pip-req-build-3loxos\

```

**Comment by Henkeh** [comment] 2018-07-15 12:38
I have seen this error as well during my struggles to get PIO installed. Possible solution can be found in my post in:
https://github.com/platformio/platformio-atom-ide/issues/1950

**Comment by ivankravets** [comment] 2018-07-19 15:07
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1950

**Closed by ivankravets** 2018-07-19 15:07 UTC
