### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by amoonre17** [platformio/platformio-atom-ide#1285] opened 2017-12-19 10:18 UTC
PIP:   Failed building wheel for netifaces
Command "/Users/tanyopeter/.platformio/penv/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/k0/_63htz8j18bbqy7s7j5dr5j40000gn/T/pip-build-vy6HP1/netifaces/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/k0/_63htz8j18bbqy7s7j5dr5j40000gn/T/pip-AJQizB-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/tanyopeter/.platformio/penv/include/site/python2.7/netifaces" failed with error code 1 in /private/var/folders/k0/_63htz8j18bbqy7s7j5dr5j40000gn/T/pip-build-vy6HP1/netifaces/

**Comment by ivankravets** [comment] 2017-12-19 10:45
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1282

**Closed by ivankravets** 2017-12-19 10:45 UTC
