### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by thubalek** [platformio/platformio-atom-ide#1416] opened 2018-01-21 11:29 UTC
Error: Error: ENOENT: no such file or directory, open '/home/tom/.atom/packages/platformio-ide/.cache/examples.tar.gz'

**Comment by ivankravets** [comment] 2018-01-30 12:15
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1327

**Closed by ivankravets** 2018-01-30 12:15 UTC
