### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by danielbibit** [platformio/platformio-atom-ide#971] opened 2017-09-22 15:14 UTC
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\danie\.platformio\.cache\tmp-7604syo13dpcc8aj\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\danie\.platformio\.cache\tmp-7604syo13dpcc8aj\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\danie\.platformio\.cache\tmp-7604syo13dpcc8aj\virtualenv-14.0.6\virtualenv.py", line 924, in create_environment
    download=download,
  File "C:\Users\danie\.platformio\.cache\tmp-7604syo13dpcc8aj\virtualenv-14.0.6\virtualenv.py", line 877, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "C:\Users\danie\.platformio\.cache\tmp-7604syo13dpcc8aj\virtualenv-14.0.6\virtualenv.py", line 743, in call_subprocess
    cwd=cwd, env=env)
  File "C:\Python27\Lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\Lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 5] Access is denied

**Comment by ivankravets** [comment] 2017-10-17 18:13
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/815

**Comment by ivankravets** [comment] 2017-10-17 18:14
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Closed by ivankravets** 2017-10-17 18:13 UTC
