### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by vince-br-549** [platformio/platformio-atom-ide#1365] opened 2018-01-10 19:18 UTC
it is installed on my Linux system.

Error: Can not find Python Interpreter
    at PlatformIOCoreStage._callee8$ (/home/vince/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2423:23)
    at tryCatch (/home/vince/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:787:40)
    at Generator.invoke [as _invoke] (/home/vince/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1021:22)
    at Generator.prototype.(anonymous function) [as next] (/home/vince/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:839:21)
    at step (/home/vince/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1792:191)
    at /home/vince/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1792:361

**Comment by ivankravets** [comment] 2018-01-10 19:34
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1364

**Closed by ivankravets** 2018-01-10 19:34 UTC
