### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by madefordeveloping** [platformio/platformio-atom-ide#1521] opened 2018-02-15 18:03 UTC
Error: [02/15/18 19:00:51] Processing nanoatmega328 (platform: atmelavr; board: nanoatmega328; framework: arduino)

SCons import failed. Unable to find engine files in:
C:\Users\topli\.platformio\packages\tool-scons\script\..\engine
C:\Users\topli\.platformio\packages\tool-scons\script\scons-local-2.5.1
C:\Users\topli\.platformio\packages\tool-scons\script\scons-local
c:\users\topli\.platformio\penv\scons-2.5.1
c:\users\topli\.platformio\penv\Lib\site-packages\scons-2.5.1
c:\users\topli\.platformio\penv\scons
c:\users\topli\.platformio\penv\Lib\site-packages\scons
Traceback (most recent call last):
File "C:\Users\topli\.platformio\packages\tool-scons\script\scons", line 190, in <module>
import SCons.Script
File "C:\Users\topli\.platformio\packages\tool-scons\script\..\engine\SCons\__init__.py", line 43, in <module>
import SCons.compat
ImportError: No module named compat
 [ERROR] Took 0.48 seconds

**Comment by ivankravets** [comment] 2018-02-17 16:21
Duplicate of #1512

**Closed by ivankravets** 2018-02-17 16:21 UTC
