### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by peeratpop** [platformio/platformio-atom-ide#810] opened 2017-08-05 16:37 UTC
C:\Users\ASUS\.platformio\packages\tool-scons\script\..\engine\SCons\Environment.py:1303: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
val = [x for x in val if x not in dk]

C:\Users\ASUS\.platformio\penv\lib\site-packages\platformio\builder\tools\piolib.py:562: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
if path not in self.envorigin.get("CPPPATH", []):

UnicodeDecodeError: Non-ASCII characters found in build environment
See explanation in FAQ > Troubleshooting > Building
http://docs.platformio.org/page/faq.html

 [ERROR] Took 2.02 seconds

**Comment by ivankravets** [comment] 2017-09-06 11:55
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/768

**Closed by ivankravets** 2017-09-06 11:55 UTC
