### ISSUE TITLE
Arch Linux: platformio: command not found (from Platformio IDE) 

### ISSUE THREAD

**Issue by stelgenhof** [platformio/platformio-atom-ide#301] opened 2017-03-30 11:18 UTC
### Configuration
Arch Linux

**PlatformIO Version** (`platformio --version`):
3.3.0

### Description of problem
When running the command "Upgrade PlatformIO Core" from the PlatformIO menu, I get the error: platformio: command not found.

This only occurred after upgrading to version 3.3.0. Before that I didn't have any issues running this option.

From the PIO IDE Terminal the output is:

`/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/sacha/.config/composer/vendor/bin`

Please refer to issue: https://github.com/platformio/platformio-core/issues/924

**Comment by ivankravets** [comment] 2017-04-30 20:59
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/333

**Closed by ivankravets** 2017-04-30 20:59 UTC
Labels: bug, duplicate
