### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by Bergerac56** [platformio/platformio-atom-ide#1021] opened 2017-10-10 09:58 UTC
Error: Status 'PlatformIO: Rebuilding C/C++ Project Index for C:\Users\olivi\Desktop\Marlin-bugfix-2.0.x' is already set
    at Registry.statusAdd (file:///C:/Users/olivi/.atom/packages/busy-signal/lib/registry.js:50:13)
    at file:///C:/Users/olivi/.atom/packages/busy-signal/lib/registry.js:31:12
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\olivi\AppData\Local\atom\app-1.21.0\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\olivi\AppData\Local\atom\app-1.21.0\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at Provider.add (file:///C:/Users/olivi/.atom/packages/busy-signal/lib/provider.js:21:18)
    at beginBusy (file:///C:/Users/olivi/.atom/packages/platformio-ide/lib/services/busy.js:25:20)
    at ProjectIndexer.<anonymous> (file:///C:/Users/olivi/.atom/packages/platformio-ide/lib/project/indexer.js:158:7)
    at Generator.next (<anonymous>)
    at step (C:\Users\olivi\.atom\packages\platformio-ide\lib\project\indexer.js:11:273)
    at C:\Users\olivi\.atom\packages\platformio-ide\lib\project\indexer.js:11:443
    at ProjectIndexer.<anonymous> (C:\Users\olivi\.atom\packages\platformio-ide\lib\project\indexer.js:11:99)

**Comment by ivankravets** [comment] 2017-10-17 12:21
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1013

**Closed by ivankravets** 2017-10-17 12:21 UTC
