### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by bwijerat** [platformio/platformio-atom-ide#1471] opened 2018-02-02 02:41 UTC
Error: Could not install 'toolchain-gccarmnoneeabi' with version requirements '>=1.40803.0,<1.40805.0' for your system 'windows_amd64'.
More details: http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment] 2018-02-17 16:12
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1171

**Closed by ivankravets** 2018-02-17 16:12 UTC
