### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by Davidsg33k** [platformio/platformio-atom-ide#1919] opened 2018-06-17 08:43 UTC
Virtualenv Create:   File "C:\Python34\Lib\site.py", line 176
    file=sys.stderr)
        ^
SyntaxError: invalid syntax

**Comment by ivankravets** [comment] 2018-06-20 18:05
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/922

**Closed by ivankravets** 2018-06-20 18:05 UTC
