### ISSUE TITLE
InstallationManager. 

### ISSUE THREAD

**Issue by RevelRob** [platformio/platformio-atom-ide#1617] opened 2018-03-09 19:36 UTC
PIP: Error: spawn /Volumes/Hard Disk Drive/Users/RobTesta/.platformio/penv/bin/pip ENOENT

Here are my outputs from:
```
echo $PATH
echo $PYTHONPATH
python --version
pip --version
pip list
```
```
Roberts-iMac:~ RobT$ echo $PATH
/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Volumes/Hard Disk Drive/Users/RobT/Library/Android/sdk/platform-tools
Roberts-iMac:~ RobT$ echo $PYTHONPATH

Roberts-iMac:~ RobT$ python --version
Python 2.7.14
Roberts-iMac:~ RobT$ pip --version
pip 9.0.1 from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (python 2.7)
Roberts-iMac:~ RobT$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
broadlink (0.6)
pip (9.0.1)
pycrypto (2.6.1)
setuptools (28.8.0)
simplejson (3.13.2)
```

Pretty weird that I don't have an output for ```echo $PYTHONPATH```.

Thanks for any help!

**Comment by ivankravets** [comment] 2018-06-20 18:44
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1243

**Closed by ivankravets** 2018-06-20 18:44 UTC
