### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by thbui** [platformio/platformio-atom-ide#816] opened 2017-08-06 15:59 UTC
Cannot find the configuration file for your board! Please read instructions here C:\Users\Tuan\.platformio\packages\framework-mbed\platformio\README.txt

 [ERROR] Took 0.96 seconds 
Trying to create a project for the multitech mdot 411

**Comment by ivankravets** [comment] 2017-10-17 14:01
Duplicate of https://github.com/platformio/platform-ststm32/issues/63

**Closed by ivankravets** 2017-10-17 14:01 UTC
