### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/Documents\PlatformIO\Projects\LCD_pru...

### ISSUE THREAD

**Issue by rjpo** [platformio/platformio-atom-ide#2017] opened 2018-07-16 01:19 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Unknown Windows version
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.1.7

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Ricardo\Documents\PlatformIO\Projects\LCD_prueba\lib\LCD_Functions.h'

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat 'C:\Users\Ricardo\Documents\PlatformIO\Projects\LCD_prueba\lib\LCD_Functions.h'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:320:29)
    at /packages/platformio-ide/lib/project/helpers.js:32:25
    at getActivePioProject (/packages/platformio-ide/lib/project/helpers.js:36:6)
    at Object.highlightActiveProject (/packages/platformio-ide/lib/maintenance.js:75:13)
    at doHighlight (/packages/platformio-ide/lib/main.js:247:43)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at stoppedChangingActivePaneItemTimeout.setTimeout (~/AppData/Local/atom/app-1.28.2/resources/app/src/workspace.js:493:26)
```

### Commands

```
     -2:05.0 core:cut (input.hidden-input)
     -2:03.0 platformio-ide:target:build (input.hidden-input)
     -2:03.0 platformio-ide:target:build-C:\Users\Ricardo\Documents\PlatformIO\Projects\LCD_prueba (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  3x -1:53.8.0 intentions:highlight (input.hidden-input)
     -1:53.2.0 core:paste (input.hidden-input)
     -1:51.6.0 platformio-ide:target:build (input.hidden-input)
     -1:51.6.0 platformio-ide:target:build-C:\Users\Ricardo\Documents\PlatformIO\Projects\LCD_prueba (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:30 intentions:highlight (input.hidden-input)
     -1:29.7.0 core:copy (input.hidden-input)
     -1:26.8.0 docblockr:parse-enter (input.hidden-input)
     -1:26.8.0 editor:newline (input.hidden-input)
     -1:26.7.0 intentions:highlight (input.hidden-input)
     -1:26.5.0 core:paste (input.hidden-input)
  9x -1:24.3.0 intentions:highlight (input.hidden-input)
     -1:23.6.0 core:undo (input.hidden-input)
     -0:49.5.0 tree-view:show-in-file-manager (span.name.icon.c-icon.medium-purple)
```

### Non-Core Packages

```
autocomplete-clang 0.11.5 
build 0.70.0 
busy-signal 1.4.3 
docblockr 0.13.7 
file-icons 2.1.22 
intentions 1.1.5 
language-ini 1.20.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
platformio-ide 2.1.7 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.8.3 
tool-bar 1.1.7 
```

**Comment by ivankravets** [comment] 2018-07-19 15:03
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1472

**Closed by ivankravets** 2018-07-19 15:03 UTC
