### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by nekkolliakos** [platformio/platformio-atom-ide#1398] opened 2018-01-16 22:55 UTC
Error: Could not install 'tool-scons' with version requirements '~3.20501.2' for your system 'windows_x86'.
More details: http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment] 2018-01-27 22:36
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1393

**Closed by ivankravets** 2018-01-27 22:36 UTC
