### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by pezinek** [platformio/platformio-atom-ide#1025] opened 2017-10-12 18:59 UTC
this happened after creating brand new project for arduino uno, adding following dependency to platformio.ini, and trying to build

lib_deps =
    https://github.com/JoaoLopesF/SPFD5408

Error: Status 'PlatformIO: Rebuilding C/C++ Project Index for /home/pzahradn/Documents/PlatformIO/Projects/171012-205003-uno' is already set
    at Registry.statusAdd (/home/pzahradn/.atom/packages/busy-signal/lib/registry.js:50:13)
    at /home/pzahradn/.atom/packages/busy-signal/lib/registry.js:31:12
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Provider.add (/home/pzahradn/.atom/packages/busy-signal/lib/provider.js:21:18)
    at beginBusy (/home/pzahradn/.atom/packages/platformio-ide/lib/services/busy.js:25:20)
    at ProjectIndexer.<anonymous> (/home/pzahradn/.atom/packages/platformio-ide/lib/project/indexer.js:158:7)
    at next (<anonymous>)
    at step (/home/pzahradn/.atom/packages/platformio-ide/lib/project/indexer.js:11:273)
    at /home/pzahradn/.atom/packages/platformio-ide/lib/project/indexer.js:11:443
    at ProjectIndexer.<anonymous> (/home/pzahradn/.atom/packages/platformio-ide/lib/project/indexer.js:11:99)

**Comment by ivankravets** [comment] 2017-10-17 12:21
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1013

**Closed by ivankravets** 2017-10-17 12:21 UTC
