### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/@CWagner23:RBE2002code'

### ISSUE THREAD

**Issue by JosuContrer** [platformio/platformio-atom-ide#1724] opened 2018-04-07 03:06 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.12.6
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.1.3

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/@CWagner23:RBE2002code'

```
At fs.js:961

Error: ENOENT: no such file or directory, lstat '/@CWagner23:RBE2002code'
    at fs.lstatSync (fs.js:961:11)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
    at Proxy.realpathSync (fs.js:1641:21)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:321:29)
    at /packages/platformio-ide/lib/project/helpers.js:32:25
    at getActivePioProject (/packages/platformio-ide/lib/project/helpers.js:36:6)
    at Object.highlightActiveProject (/packages/platformio-ide/lib/maintenance.js:133:13)
    at doHighlight (/packages/platformio-ide/lib/main.js:245:43)
    at Function.module.exports.Emitter.simpleDispatch (/private/var/folders/mt/cgm7nxb95n51jf5w0d__kz300000gn/T/AppTranslocation/56976BD9-320D-428A-8876-68BC38F2366C/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/private/var/folders/mt/cgm7nxb95n51jf5w0d__kz300000gn/T/AppTranslocation/56976BD9-320D-428A-8876-68BC38F2366C/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at stoppedChangingActivePaneItemTimeout.setTimeout (/private/var/folders/mt/cgm7nxb95n51jf5w0d__kz300000gn/T/AppTranslocation/56976BD9-320D-428A-8876-68BC38F2366C/d/Atom.app/Contents/Resources/app/src/workspace.js:491:26)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-clang 0.11.4 
build 0.70.0 
busy-signal 1.4.3 
docblockr 0.13.7 
file-icons 2.1.17 
git-plus 7.10.2 
intentions 1.1.5 
language-ini 1.19.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
platformio-ide 2.1.3 
platformio-ide-debugger 1.2.5 
platformio-ide-terminal 2.8.1 
teletype 0.12.0 
tool-bar 1.1.6 
```

**Comment by ivankravets** [comment] 2018-06-20 18:39
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1472

**Closed by ivankravets** 2018-06-20 18:39 UTC
