### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by rites1978** [platformio/platformio-atom-ide#1068] opened 2017-10-23 13:59 UTC
Error: Status 'PlatformIO: Rebuilding C/C++ Project Index for /Users/Riteshlal/Desktop/Projects/Sonoff-Tasmota-development' is already set
    at Registry.statusAdd (/Users/Riteshlal/.atom/packages/busy-signal/lib/registry.js:50:13)
    at /Users/Riteshlal/.atom/packages/busy-signal/lib/registry.js:31:12
    at Function.module.exports.Emitter.simpleDispatch (/private/var/folders/x7/w0r87_sd0kj9dtlkqr0wm5sw0000gn/T/AppTranslocation/D6F29678-A54B-499E-BB06-0082D17485CD/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/private/var/folders/x7/w0r87_sd0kj9dtlkqr0wm5sw0000gn/T/AppTranslocation/D6F29678-A54B-499E-BB06-0082D17485CD/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Provider.add (/Users/Riteshlal/.atom/packages/busy-signal/lib/provider.js:21:18)
    at beginBusy (/Users/Riteshlal/.atom/packages/platformio-ide/lib/services/busy.js:25:20)
    at ProjectIndexer.<anonymous> (/Users/Riteshlal/.atom/packages/platformio-ide/lib/project/indexer.js:158:7)
    at Generator.next (<anonymous>)
    at step (/Users/Riteshlal/.atom/packages/platformio-ide/lib/project/indexer.js:11:273)
    at /Users/Riteshlal/.atom/packages/platformio-ide/lib/project/indexer.js:11:443
    at ProjectIndexer.<anonymous> (/Users/Riteshlal/.atom/packages/platformio-ide/lib/project/indexer.js:11:99)

**Comment by ivankravets** [comment] 2017-11-04 13:09
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1013

**Closed by ivankravets** 2017-11-04 13:09 UTC
