### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by Pandora-jshimpf** [platformio/platformio-atom-ide#1817] opened 2018-05-05 09:45 UTC
PIP: Error: spawn /Users/jim/.platformio/penv/bin/pip ENOENT on OSX 10.13.4 Installing platformio-ide

**Comment by ivankravets** [comment] 2018-06-20 18:42
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1243

**Closed by ivankravets** 2018-06-20 18:42 UTC
