### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by ionutantone** [platformio/platformio-atom-ide#1776] opened 2018-04-19 10:28 UTC
Error: Failed to download file https://pypi.python.org/packages/source/v/virtualenv/virtualenv-14.0.6.tar.gz: Error: tunneling socket could not be established, statusCode=407
    at _callee$ (C:\Users\aantone\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:2679:19)
    at tryCatch (C:\Users\aantone\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:836:40)
    at Generator.invoke [as _invoke] (C:\Users\aantone\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1070:22)
    at Generator.prototype.(anonymous function) [as throw] (C:\Users\aantone\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:888:21)
    at step (C:\Users\aantone\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:2781:191)
    at C:\Users\aantone\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:2781:402
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by ivankravets** [comment] 2018-04-19 20:51
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1674

**Closed by ivankravets** 2018-04-19 20:51 UTC
