### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by PaytonShaw** [platformio/platformio-atom-ide#1363] opened 2018-01-10 15:24 UTC
Virtualenv Create: Traceback (most recent call last):
  File "/Users/Payton/.platformio/.cache/tmp-71864A22SbeA3ebP/virtualenv-14.0.6/virtualenv.py", line 2304, in <module>
    main()
  File "/Users/Payton/.platformio/.cache/tmp-71864A22SbeA3ebP/virtualenv-14.0.6/virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "/Users/Payton/.platformio/.cache/tmp-71864A22SbeA3ebP/virtualenv-14.0.6/virtualenv.py", line 924, in create_environment
    download=download,
  File "/Users/Payton/.platformio/.cache/tmp-71864A22SbeA3ebP/virtualenv-14.0.6/virtualenv.py", line 877, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "/Users/Payton/.platformio/.cache/tmp-71864A22SbeA3ebP/virtualenv-14.0.6/virtualenv.py", line 783, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/Payton/.platformio/penv/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 2

**Comment by ivankravets** [comment] 2018-01-10 20:12
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1245

Can you reproduce this issue with the latest version of PlatformIO IDE 2.0.0-rc.6?

**Closed by ivankravets** 2018-01-10 20:12 UTC
