### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by ihortarasuk** [platformio/platformio-atom-ide#874] opened 2017-08-24 16:28 UTC
C:\.platformio\packages\tool-scons\script\..\engine\SCons\Environment.py:1303: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
val = [x for x in val if x not in dk]

UnicodeDecodeError: Non-ASCII characters found in build environment
See explanation in FAQ > Troubleshooting > Building
http://docs.platformio.org/page/faq.html

 [ERROR] Took 4.06 seconds

**Comment by ihortarasuk** [comment] 2017-08-24 16:30
Ок ошибка оказалась в том что кириллица в пути создания директории проекта.

**Comment by ivankravets** [comment] 2017-09-06 11:55
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/768

**Closed by ivankravets** 2017-09-06 11:55 UTC
