### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by perfessor101** [platformio/platformio-atom-ide#863] opened 2017-08-21 15:36 UTC
Traceback (most recent call last):
File "C:\Users\bobbys\.platformio\packages\installing-fixl8u-package\script\scons", line 190, in <module>
import SCons.Script
File "C:\Users\bobbys\.platformio\packages\installing-fixl8u-package\script\..\engine\SCons\__init__.py", line 43, in <module>
ImportError: No module named compat

 [ERROR] Took 2.49 seconds 

trying to compile this 

/* Hello World Example

   This example code is in the Public Domain (or CC0 licensed, at your option.)

   Unless required by applicable law or agreed to in writing, this
   software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
   CONDITIONS OF ANY KIND, either express or implied.
*/
#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_system.h"
#include "esp_spi_flash.h"

void app_main()
{
    printf("Hello world!\n");

    /* Print chip information */
    esp_chip_info_t chip_info;
    esp_chip_info(&chip_info);
    printf("This is ESP32 chip with %d CPU cores, WiFi%s%s, ",
            chip_info.cores,
            (chip_info.features & CHIP_FEATURE_BT) ? "/BT" : "",
            (chip_info.features & CHIP_FEATURE_BLE) ? "/BLE" : "");

    printf("silicon revision %d, ", chip_info.revision);

    printf("%dMB %s flash\n", spi_flash_get_chip_size() / (1024 * 1024),
            (chip_info.features & CHIP_FEATURE_EMB_FLASH) ? "embedded" : "external");

    for (int i = 10; i >= 0; i--) {
        printf("Restarting in %d seconds...\n", i);
        vTaskDelay(1000 / portTICK_PERIOD_MS);
    }
    printf("Restarting now.\n");
    fflush(stdout);
    esp_restart();
}

I've reinstalled and wiped out atom and platformio twice ... 

not sure how to fix

Thanks for your time,
Bobby

**Comment by ivankravets** [comment] 2017-09-06 11:40
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/826

**Closed by ivankravets** 2017-09-06 11:40 UTC
