### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by demonreeper** [platformio/platformio-atom-ide#1622] opened 2018-03-10 23:10 UTC
PIP: 'C:\Users\user\.platformio\penv\Scripts\pip' is not recognized as an internal or external command,
operable program or batch file.
Error: spawn C:\Users\user\.platformio\penv\Scripts\pip ENOENT

**Comment by ivankravets** [comment] 2018-06-20 18:43
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1243

**Closed by ivankravets** 2018-06-20 18:43 UTC
