### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by Littrow** [platformio/platformio-atom-ide#663] opened 2017-06-26 07:21 UTC
UnicodeDecodeError: Non-ASCII characters found in build environment
See explanation in FAQ > Troubleshooting > Building
http://docs.platformio.org/page/faq.html

 [ERROR] Took 0.75 seconds

**Comment by ivankravets** [comment] 2017-06-27 17:24
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/658

**Closed by ivankravets** 2017-06-27 17:24 UTC

**Comment by Littrow** [comment] 2017-06-27 17:53
Thanks, everybody alright.
