### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by DodiGrabowski** [platformio/platformio-atom-ide#1716] opened 2018-04-04 17:34 UTC
Error: Traceback (most recent call last):
  File "/home/dodi/.platformio/penv/local/lib/python2.7/site-packages/platformio/__main__.py", line 120, in main
    cli(None, None, None)
  File "/home/dodi/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/dodi/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/dodi/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 1024, in invoke
    Command.invoke(self, ctx)
  File "/home/dodi/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dodi/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/dodi/.platformio/penv/local/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dodi/.platformio/penv/local/lib/python2.7/site-packages/platformio/__main__.py", line 74, in cli
    maintenance.on_platformio_start(ctx, force, caller)
  File "/home/dodi/.platformio/penv/local/lib/python2.7/site-packages/platformio/maintenance.py", line 44, in on_platformio_start
    after_upgrade(ctx)
  File "/home/dodi/.platformio/penv/local/lib/python2.7/site-packages/platformio/maintenance.py", line 189, in after_upgrade
    app.clean_cache()
  File "/home/dodi/.platformio/penv/local/lib/python2.7/site-packages/platformio/app.py", line 271, in clean_cache
    with ContentCache() as cc:
  File "/home/dodi/.platformio/penv/local/lib/python2.7/site-packages/platformio/app.py", line 149, in __enter__
    self.delete()
  File "/home/dodi/.platformio/penv/local/lib/python2.7/site-packages/platformio/app.py", line 244, in delete
    if time() < int(expire) and isfile(path) and \
ValueError: invalid literal for int() with base 10: ''

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by ivankravets** [comment] 2018-06-21 09:33
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1707

**Closed by ivankravets** 2018-06-21 09:33 UTC
