### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by nurbsn** [platformio/platformio-atom-ide#990] opened 2017-09-26 19:19 UTC
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\nurbs\.platformio\.cache\tmp-102808byheEZHTfEC\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\nurbs\.platformio\.cache\tmp-102808byheEZHTfEC\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\nurbs\.platformio\.cache\tmp-102808byheEZHTfEC\virtualenv-14.0.6\virtualenv.py", line 924, in create_environment
    download=download,
  File "C:\Users\nurbs\.platformio\.cache\tmp-102808byheEZHTfEC\virtualenv-14.0.6\virtualenv.py", line 877, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "C:\Users\nurbs\.platformio\.cache\tmp-102808byheEZHTfEC\virtualenv-14.0.6\virtualenv.py", line 747, in call_subprocess
    "Error %s while executing command %s" % (e, cmd_desc))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xea in position 27: ordinal not in range(128)

**Comment by ivankravets** [comment] 2017-10-17 13:58
Duplicate of #812

**Closed by ivankravets** 2017-10-17 13:58 UTC
