### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by LWorm** [platformio/platformio-atom-ide#1404] opened 2018-01-19 18:23 UTC
Error: Could not install 'framework-arduinoteensy' with version requirements '~1.140.0' for your system 'windows_amd64'.
More details: http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment] 2018-01-27 22:36
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1393

**Closed by ivankravets** 2018-01-27 22:36 UTC
