### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by manaioussema** [platformio/platformio-atom-ide#1496] opened 2018-02-08 10:55 UTC
Error: Could not install 'framework-arduinoavr' with version requirements '~1.10620.2' for your system 'windows_x86'.

Please try this solution -> http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment] 2018-02-17 16:13
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1171

**Closed by ivankravets** 2018-02-17 16:13 UTC
