### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by denise-amiga** [platformio/platformio-atom-ide#660] opened 2017-06-26 07:00 UTC
Error: Could not install 'toolchain-atmelavr' with version requirements '~1.40902.0' for your system 'windows_x86'.
If you use Antivirus, it can block PlatformIO Package Manager. Try to disable it for a while.

**Comment by ivankravets** [comment] 2017-06-27 17:25
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/658

**Closed by ivankravets** 2017-06-27 17:25 UTC
