### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by denise-amiga** [platformio/platformio-atom-ide#662] opened 2017-06-26 07:01 UTC
Traceback (most recent call last):
  File "C:\Users\Denise\.platformio\penv\Scripts\platformio-script.py", line 11, in <module>
    load_entry_point('platformio==3.4.0rc1', 'console_scripts', 'platformio')()
  File "c:\users\denise\.platformio\penv\lib\site-packages\platformio\__main__.py", line 107, in main
    maintenance.on_platformio_exception(e)
  File "c:\users\denise\.platformio\penv\lib\site-packages\platformio\maintenance.py", line 87, in on_platformio_exception
    telemetry.on_exception(e)
  File "c:\users\denise\.platformio\penv\lib\site-packages\platformio\telemetry.py", line 319, in on_exception
    mp.send("exception")
  File "c:\users\denise\.platformio\penv\lib\site-packages\platformio\telemetry.py", line 142, in send
    if not app.get_setting("enable_telemetry"):
  File "c:\users\denise\.platformio\penv\lib\site-packages\platformio\app.py", line 306, in get_setting
    with State() as data:
  File "c:\users\denise\.platformio\penv\lib\site-packages\platformio\app.py", line 90, in __enter__
    self._state = util.load_json(self.path)
  File "c:\users\denise\.platformio\penv\lib\site-packages\platformio\util.py", line 178, in load_json
    "Could not load broken JSON: %s" % file_path)
platformio.exception.PlatformioException: Could not load broken JSON: C:\Users\Denise\.platformio\appstate.json

**Comment by ivankravets** [comment] 2017-06-27 17:24
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/658

**Closed by ivankravets** 2017-06-27 17:24 UTC
