### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by mdanetzky** [platformio/platformio-atom-ide#1263] opened 2017-12-13 14:48 UTC
Virtualenv Create: Traceback (most recent call last):
  File "/Users/matthias/.platformio/.cache/tmp-3372ozjoM2Y3D7wC/virtualenv-14.0.6/virtualenv.py", line 2304, in <module>
    main()
  File "/Users/matthias/.platformio/.cache/tmp-3372ozjoM2Y3D7wC/virtualenv-14.0.6/virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "/Users/matthias/.platformio/.cache/tmp-3372ozjoM2Y3D7wC/virtualenv-14.0.6/virtualenv.py", line 904, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/Users/matthias/.platformio/penv/lib/python2.7/posixpath.py", line 360, in abspath
    if not isabs(path):
  File "/Users/matthias/.platformio/penv/lib/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by ivankravets** [comment] 2017-12-14 00:06
Please provide an output from a system Terminal
```
echo $PATH
echo $PYTHONPATH
python --version
pip --version
pip list
```

**Comment by mdanetzky** [comment] 2017-12-14 06:30
echo $PATH
/usr/local/opt/libxml2/bin:/usr/local/opt/python/libexec/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/matthias/n/bin

echo $PYTHONPATH


python --version
Python 2.7.10

pip --version
-bash: pip: command not found

matthias$ pip list
-bash: pip: command not found

**Comment by ivankravets** [comment] 2017-12-14 11:10
> /usr/local/opt/python

Do you have a custom Python in a system?

**Comment by mdanetzky** [comment] 2017-12-14 11:43
I just reinstalled OSX Sierra after botched update of High Sierra

**Comment by ivankravets** [comment] 2017-12-14 12:23
Could you provide TeamViewer session to debug this issue? me@ikravets.com

**Comment by ivankravets** [comment] 2017-12-15 19:08
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1240

**Closed by ivankravets** 2017-12-15 19:08 UTC
Labels: help wanted
