### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by pmoscetta** [platformio/platformio-atom-ide#2063] opened 2018-08-27 09:37 UTC
PIP:   Could not find a version that satisfies the requirement bottle<0.13 (from platformio==3.6.0) (from versions: )
No matching distribution found for bottle<0.13 (from platformio==3.6.0)

**Comment by ivankravets** [comment] 2018-08-28 12:18
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1926

**Closed by ivankravets** 2018-08-28 12:18 UTC
