### ISSUE TITLE
Uncaught Error: Could not start PIO Home server: Error: Could not install 'tool-pioplus' with ver...

### ISSUE THREAD

**Issue by larsronnie** [platformio/platformio-atom-ide#1414] opened 2018-01-21 10:12 UTC
[Enter steps to reproduce:]

1. Installed Atom, Platform IO IDE and LLVM (Clang)
2. Restarted Atom and the issue came up.

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.0.0-rc.7

### Stack Trace

Uncaught Error: Could not start PIO Home server: Error: Could not install 'tool-pioplus' with version requirements '>=0.13.3,<2' for your system 'windows_amd64'.
More details: http://bit.ly/faq-package-manager

```
At C:\Users\Ronnie.Magnusson\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1615

Error: Could not start PIO Home server: Error: Could not install 'tool-pioplus' with version requirements '>=0.13.3,<2' for your system 'windows_amd64'.
More details: http://bit.ly/faq-package-manager

    at /packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1615:23
    at ChildProcess.onExit (/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:537:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (/packages/platformio-ide/node_modules/cross-spawn/lib/enoent.js:40:29)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-clang 0.11.4 
build 0.70.0 
busy-signal 1.4.3 
file-icons 2.1.16 
intentions 1.1.5 
language-ini 1.19.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.6.10 
platformio-ide 2.0.0-rc.7 
platformio-ide-debugger 1.2.5 
platformio-ide-terminal 2.8.0 
tool-bar 1.1.4 
```

**Comment by ivankravets** [comment] 2018-01-27 22:37
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1393

**Closed by ivankravets** 2018-01-27 22:37 UTC
