### ISSUE TITLE
WindowsError: [Error 5] Access is denied

### ISSUE THREAD

**Issue by kurniawan77** [platformio/platformio-atom-ide#1238] opened 2017-12-05 14:49 UTC
# Solutions

Please try one of these solutions:

- http://docs.platformio.org/en/latest/faq.html#package-manager

------

Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\Irwan\.platformio\.cache\tmp-1002803NtiOXzfOzu\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\Irwan\.platformio\.cache\tmp-1002803NtiOXzfOzu\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\Irwan\.platformio\.cache\tmp-1002803NtiOXzfOzu\virtualenv-14.0.6\virtualenv.py", line 924, in create_environment
    download=download,
  File "C:\Users\Irwan\.platformio\.cache\tmp-1002803NtiOXzfOzu\virtualenv-14.0.6\virtualenv.py", line 877, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "C:\Users\Irwan\.platformio\.cache\tmp-1002803NtiOXzfOzu\virtualenv-14.0.6\virtualenv.py", line 743, in call_subprocess
    cwd=cwd, env=env)
  File "C:\Users\Irwan\.platformio\python27\Lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Users\Irwan\.platformio\python27\Lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 5] Access is denied

**Comment by ivankravets** [comment] 2017-12-15 18:44
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment] 2017-12-16 19:53
@mosescomp @kurniawan77 
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment] 2018-01-10 17:55
@mosescomp @kurniawan77 @DocSlump @kochalois
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by kurniawan77** [comment] 2018-01-10 20:02
I reinstalled everything... got it working again

**Comment by ivankravets** [comment] 2018-01-10 22:51
@mosescomp @DocSlump @kochalois @Jakim121
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

Also, try to disable antivirus for a while and restart IDE.

**Comment by Jakim121** [comment] 2018-01-10 23:59
I disabled antivirus for a while, it is fixed.

**Comment by mosescomp** [comment] 2018-01-11 01:38
I let PlatformIO send the error report to you.  I believe that it was a ‘hiccup’. 

Now that I have been using it a while and have gotten ALL of the updates, it appears to be working flawlessly.

Thank you for creating an absolutely fantastic product.  It is a pleasure to use, and by the way, super fast!

On the MacBook I couldn’t get scroll back to work in the terminal window - until I connected a mouse, fine now!  Hmm, maybe I would have encountered the same problem on the PC also, if I hadn’t had a mouse connected to it.

Thank you!
Mike Moses

**Comment by ivankravets** [comment] 2018-01-11 20:36
I added all solutions for this issue to our FAQ: http://docs.platformio.org/en/latest/faq.html#package-manager

**Comment by ivankravets** [comment] 2018-06-20 18:51
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1171

**Closed** 2018-06-20 18:54 UTC
Labels: help wanted
