### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by boolutus** [platformio/platformio-atom-ide#1895] opened 2018-06-07 09:07 UTC
Traceback (most recent call last):
  File "C:\Users\patrick\.platformio\penv\Scripts\platformio-script.py", line 11, in <module>
    load_entry_point('platformio==3.6.0a1', 'console_scripts', 'platformio')()
  File "c:\users\patrick\.platformio\penv\lib\site-packages\platformio\__main__.py", line 126, in main
    error_str += str(e)
  File "c:\users\patrick\.platformio\penv\lib\site-packages\platformio\exception.py", line 23, in __str__
    return Exception.__str__(self)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 53-58: ordinal not in range(128)

**Comment by ivankravets** [comment] 2018-06-20 19:18
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1228

**Closed by ivankravets** 2018-06-20 19:18 UTC
