### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by Egaro555** [platformio/platformio-atom-ide#1338] opened 2018-01-03 16:53 UTC
Virtualenv Create: Traceback (most recent call last):
  File "E:\Users\hugues_\.platformio\.cache\tmp-11552Nve84G6kwooE\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "E:\Users\hugues_\.platformio\.cache\tmp-11552Nve84G6kwooE\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "E:\Users\hugues_\.platformio\.cache\tmp-11552Nve84G6kwooE\virtualenv-14.0.6\virtualenv.py", line 924, in create_environment
    download=download,
  File "E:\Users\hugues_\.platformio\.cache\tmp-11552Nve84G6kwooE\virtualenv-14.0.6\virtualenv.py", line 877, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "E:\Users\hugues_\.platformio\.cache\tmp-11552Nve84G6kwooE\virtualenv-14.0.6\virtualenv.py", line 783, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command E:\Users\hugues_\.pl...v\Scripts\python.exe -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 2

**Comment by ivankravets** [comment] 2018-01-06 11:39
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1243

**Closed by ivankravets** 2018-01-06 11:39 UTC
