### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by esron** [platformio/platformio-atom-ide#954] opened 2017-09-16 21:03 UTC
KeyError: 'BOARD':
File "C:\Users\gacci\.platformio\penv\lib\site-packages\platformio\builder\main.py", line 170:
print "\n%s\n" % json.dumps(env.DumpIDEData())
File "C:\Users\gacci\.platformio\packages\tool-scons\script\..\engine\SCons\Environment.py", line 224:
return self.method(*nargs, **kwargs)
File "C:\Users\gacci\.platformio\penv\lib\site-packages\platformio\builder\tools\pioide.py", line 78:
dump_defines(env),
File "C:\Users\gacci\.platformio\penv\lib\site-packages\platformio\builder\tools\pioide.py", line 65:
"__AVR_%s__" % env.BoardConfig().get("build.mcu").upper()
File "C:\Users\gacci\.platformio\packages\tool-scons\script\..\engine\SCons\Environment.py", line 224:
return self.method(*nargs, **kwargs)
File "C:\Users\gacci\.platformio\penv\lib\site-packages\platformio\builder\tools\pioplatform.py", line 44:
config = p.board_config(board if board else env['BOARD'])
File "C:\Users\gacci\.platformio\packages\tool-scons\script\..\engine\SCons\Environment.py", line 410:
return self._dict[key]
 [ERROR] Took 1.32 seconds

**Comment by ivankravets** [comment] 2017-10-17 18:17
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/953

**Closed by ivankravets** 2017-10-17 18:17 UTC
