### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by maratkhasanov** [platformio/platformio-atom-ide#1616] opened 2018-03-09 18:13 UTC
Can't install PlatformIO

Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\marat\.platformio\.cache\tmp-3892x0aDL8Uv7r1q\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\marat\.platformio\.cache\tmp-3892x0aDL8Uv7r1q\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\marat\.platformio\.cache\tmp-3892x0aDL8Uv7r1q\virtualenv-14.0.6\virtualenv.py", line 924, in create_environment
    download=download,
  File "C:\Users\marat\.platformio\.cache\tmp-3892x0aDL8Uv7r1q\virtualenv-14.0.6\virtualenv.py", line 877, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "C:\Users\marat\.platformio\.cache\tmp-3892x0aDL8Uv7r1q\virtualenv-14.0.6\virtualenv.py", line 743, in call_subprocess
    cwd=cwd, env=env)
  File "C:\Users\marat\.platformio\python27\Lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Users\marat\.platformio\python27\Lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 5] 

in SquirrelSetup.log:

2018-03-09 21:28:20> ApplyReleasesImpl: File 'C:\Users\marat\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\Snipping Tool.lnk' could not be converted into a valid ShellLink: System.IO.FileNotFoundException: Could not find a file. (exeption HRESULT: 0x80070002)

**Comment by ivankravets** [comment] 2018-06-20 18:57
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1191

**Closed by ivankravets** 2018-06-20 18:57 UTC
