### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by HyVong007** [platformio/platformio-atom-ide#1499] opened 2018-02-08 18:34 UTC
PIP:   Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00000000061067B8>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))': /platformio/platformio/archive/develop.zip
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000006106898>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))': /platformio/platformio/archive/develop.zip
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000006106978>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))': /platformio/platformio/archive/develop.zip
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000006106A58>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))': /platformio/platformio/archive/develop.zip
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000006106B38>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))': /platformio/platformio/archive/develop.zip
Exception:
Traceback (most recent call last):
  File "c:\users\tam\.platformio\penv\lib\site-packages\pip\basecommand.py", line 209, in main
    status = self.run(options, args)
  File "c:\users\tam\.platformio\penv\lib\site-packages\pip\commands\install.py", line 310, in run
    wb.build(autobuilding=True)
  File "c:\users\tam\.platformio\penv\lib\site-packages\pip\wheel.py", line 747, in build
    self.requirement_set.prepare_files(self.finder)
  File "c:\users\tam\.platformio\penv\lib\site-packages\pip\req\req_set.py", line 359, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\users\tam\.platformio\penv\lib\site-packages\pip\req\req_set.py", line 576, in _prepare_file
    session=self.session, hashes=hashes)
  File "c:\users\tam\.platformio\penv\lib\site-packages\pip\download.py", line 809, in unpack_url
    hashes=hashes
  File "c:\users\tam\.platformio\penv\lib\site-packages\pip\download.py", line 648, in unpack_http_url
    hashes)
  File "c:\users\tam\.platformio\penv\lib\site-packages\pip\download.py", line 841, in _download_http_url
    stream=True,
  File "c:\users\tam\.platformio\penv\lib\site-packages\pip\_vendor\requests\sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\tam\.platformio\penv\lib\site-packages\pip\download.py", line 377, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "c:\users\tam\.platformio\penv\lib\site-packages\pip\_vendor\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\tam\.platformio\penv\lib\site-packages\pip\_vendor\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\tam\.platformio\penv\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "c:\users\tam\.platformio\penv\lib\site-packages\pip\_vendor\requests\adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /platformio/platformio/archive/develop.zip (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000006106BE0>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',)))

**Comment by ivankravets** [comment] 2018-02-17 16:38
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1502

**Closed by ivankravets** 2018-02-17 16:38 UTC
