### ISSUE TITLE
Instalation PlatformIO stuck on Atom dependencies forever

### ISSUE THREAD

**Issue by dejanBpetrovic** [platformio/platformio-atom-ide#2061] opened 2018-08-23 22:46 UTC
I try to perform installation of platformio-ide on Atom but in both time installation held on exact same spot and looping forever as you can see on picture. Is there any solution?
Platform is Win7/64bit  
![platformio](https://user-images.githubusercontent.com/18539504/44555782-232d2080-a737-11e8-9539-61e9665523c9.png)

**Comment by ivankravets** [comment] 2018-08-24 21:16
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/2059

**Closed by ivankravets** 2018-08-24 21:16 UTC
