### ISSUE TITLE
InstallationManager: Error: Failed to download fil

### ISSUE THREAD

**Issue by yguel** [platformio/platformio-atom-ide#2108] opened 2018-11-26 16:45 UTC
Error: Failed to download file https://github.com/platformio/platformio/archive/develop.zip: 
    at _callee$ (/home/manu/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2668:19)
    at tryCatch (/home/manu/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:836:40)
    at Generator.invoke [as _invoke] (/home/manu/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1070:22)
    at Generator.prototype.(anonymous function) [as next] (/home/manu/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:888:21)
    at step (/home/manu/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2770:191)
    at /home/manu/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2770:361

**Comment by ivankravets** [comment] 2018-11-29 22:22
Could you update to the latest 2.3.0 version? Does it work now?

**Comment by ivankravets** [comment] 2018-11-29 23:40
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/2105

**Closed by ivankravets** 2018-11-29 23:40 UTC
