### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/Documents\PlatformIO\Projects\180213-...

### ISSUE THREAD

**Issue by HaNij** [platformio/platformio-atom-ide#1514] opened 2018-02-13 09:05 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 ia32
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.0.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Savinov\Documents\PlatformIO\Projects\180213-131544-nanoatmega328\src\sketch_dec03a.ino.cpp'

```
At fs.js:902

Error: ENOENT: no such file or directory, lstat 'C:\Users\Savinov\Documents\PlatformIO\Projects\180213-131544-nanoatmega328\src\sketch_dec03a.ino.cpp'
    at fs.lstatSync (fs.js:902:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
    at Proxy.realpathSync (fs.js:1542:21)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:321:29)
    at /packages/platformio-ide/lib/project/helpers.js:32:25
    at getActivePioProject (/packages/platformio-ide/lib/project/helpers.js:36:6)
    at /packages/platformio-ide/lib/main.js:170:19)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.23.3/resources/app/src/command-registry.js:388:36)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.23.3/resources/app/src/command-registry.js:273:23)
    at executeCallback (/packages/tool-bar/lib/tool-bar-button-view.js:135:19)
    at ToolBarButtonView._onClick (/packages/tool-bar/lib/tool-bar-button-view.js:97:7)
```

### Commands

```
     -7:47.1.0 platformio-ide:target:debug (div.tool-panel.tree-view)
     -7:47 platformio-ide:target:debug-C:\Users\Savinov\Documents\PlatformIO\Projects\180213-131544-nanoatmega328 (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -6:15.3.0 platformio-ide:target:build (input.hidden-input)
     -6:15.3.0 platformio-ide:target:build-C:\Users\Savinov\Documents\PlatformIO\Projects\180213-131544-nanoatmega328 (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -5:06.7.0 platformio-ide-debugger:toggle-breakpoint (input.hidden-input)
     -4:54.3.0 platformio-ide:target:debug (input.hidden-input)
     -4:54.2.0 platformio-ide:target:debug-C:\Users\Savinov\Documents\PlatformIO\Projects\180213-131544-nanoatmega328 (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
 62x -2:56.1.0 core:backspace (input.hidden-input)
     -2:37.9.0 core:confirm (input.hidden-input)
     -1:52.8.0 platformio-ide:target:debug (input.hidden-input)
     -1:52.8.0 platformio-ide:target:debug-C:\Users\Savinov\Documents\PlatformIO\Projects\180213-131544-nanoatmega328 (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:00.1.0 platformio-ide:maintenance.rebuild-index (input.hidden-input)
     -0:11.5.0 platformio-ide:target:debug (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-clang 0.11.4 
build 0.70.0 
busy-signal 1.4.3 
file-icons 2.1.16 
intentions 1.1.5 
language-ini 1.19.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.6.10 
platformio-ide 2.0.1 
platformio-ide-debugger 1.2.5 
platformio-ide-terminal 2.8.0 
tool-bar 1.1.6 
```

**Comment by ivankravets** [comment] 2018-02-17 16:29
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1472

**Closed by ivankravets** 2018-02-17 16:29 UTC
