### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by Muffelpuffel** [platformio/platformio-atom-ide#1402] opened 2018-01-19 10:58 UTC
If you use Antivirus, it can block PlatformIO Installer. Try to disable it for a while.

Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\Altec\.platformio\.cache\tmp-2528SodPI9Xm0Oxx\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\Altec\.platformio\.cache\tmp-2528SodPI9Xm0Oxx\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\Altec\.platformio\.cache\tmp-2528SodPI9Xm0Oxx\virtualenv-14.0.6\virtualenv.py", line 924, in create_environment
    download=download,
  File "C:\Users\Altec\.platformio\.cache\tmp-2528SodPI9Xm0Oxx\virtualenv-14.0.6\virtualenv.py", line 877, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "C:\Users\Altec\.platformio\.cache\tmp-2528SodPI9Xm0Oxx\virtualenv-14.0.6\virtualenv.py", line 743, in call_subprocess
    cwd=cwd, env=env)
  File "C:\Users\Altec\.platformio\python27\Lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Users\Altec\.platformio\python27\Lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 5] Zugriff verweigert

**Comment by ivankravets** [comment] 2018-01-30 12:04
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1238

**Closed by ivankravets** 2018-01-30 12:04 UTC
