### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by samarano** [platformio/platformio-atom-ide#1853] opened 2018-05-22 09:40 UTC
Error: [05/22/18 12:39:40] Processing lpc1768 (platform: nxplpc; board: lpc1768; framework: mbed)

Verbose mode can be enabled via `-v, --verbose` option
PLATFORM: NXP LPC > NXP mbed LPC1768
SYSTEM: LPC1768 96MHz 64KB RAM (512KB Flash)
DEBUG: CURRENT(cmsis-dap) ON-BOARD(cmsis-dap) EXTERNAL(blackmagic, jlink)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(light)
Collected 37 compatible libraries
Scanning dependencies...
Error: Could not find `ualloc` dependency for `mbed-drivers` library
 [ERROR] Took 2.88 seconds

**Comment by ivankravets** [comment] 2018-06-20 20:57
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1356

Please upgrade PIO Core via `pio upgrade --dev`.

**Closed by ivankravets** 2018-06-20 20:57 UTC
