### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by StarrLucky** [platformio/platformio-atom-ide#1712] opened 2018-04-02 20:27 UTC
Traceback (most recent call last):
  File "C:\Users\fxnds\.platformio\penv\Scripts\platformio-script.py", line 6, in <module>
  File "c:\users\fxnds\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 3195, in <module>
    @_call_aside
  File "c:\users\fxnds\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 3179, in _call_aside
    f(*args, **kwargs)
  File "c:\users\fxnds\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 3208, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\users\fxnds\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 681, in _build_master
    ws.require(__requires__)
  File "c:\users\fxnds\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 999, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\users\fxnds\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 885, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'platformio==3.5.3a8' distribution was not found and is required by the application

**Comment by ivankravets** [comment] 2018-06-21 09:41
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1304

**Closed by ivankravets** 2018-06-21 09:41 UTC
