### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by ngentil** [platformio/platformio-atom-ide#838] opened 2017-08-13 11:47 UTC
Traceback (most recent call last):
File "/home/nathan/.platformio/packages/tool-scons/script/scons", line 190, in <module>
import SCons.Script
ImportError: No module named SCons.Script

========================== [ERROR] Took 0.29 seconds ==========================

**Comment by ivankravets** [comment] 2017-09-06 11:40
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/826

**Closed by ivankravets** 2017-09-06 11:40 UTC
