### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by jrlortiz** [platformio/platformio-atom-ide#1284] opened 2017-12-19 03:45 UTC
PIP:   Failed building wheel for netifaces
Command "/home/openhabuser/.platformio/penv/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-hMAznH/netifaces/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-pLO_hb-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/openhabuser/.platformio/penv/include/site/python2.7/netifaces" failed with error code 1 in /tmp/pip-build-hMAznH/netifaces/

**Comment by ivankravets** [comment] 2017-12-19 09:28
What is your OS?

**Comment by ivankravets** [comment] 2017-12-19 10:44
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1282

**Closed by ivankravets** 2017-12-19 10:44 UTC
