### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by essera** [platformio/platformio-atom-ide#1348] opened 2018-01-05 20:24 UTC
Traceback (most recent call last):
  File "c:\users\andreas\.platformio\penv\lib\site.py", line 703, in <module>
    main()
  File "c:\users\andreas\.platformio\penv\lib\site.py", line 692, in main
    aliasmbcs()
  File "c:\users\andreas\.platformio\penv\lib\site.py", line 515, in aliasmbcs
    import locale, codecs
  File "c:\users\andreas\.platformio\penv\lib\locale.py", line 17, in <module>
    import functools
ImportError: No module named functools

**Comment by ivankravets** [comment] 2018-01-06 11:43
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/797

**Comment by ivankravets** [comment] 2018-01-06 11:44
Please uninstall all Pythons from a system using System > Control Panel > Uninstall Pythons.
Restart DE.

**Closed by ivankravets** 2018-01-06 11:43 UTC
