### ISSUE TITLE
Problem has beenn occured while uprading PlatformIO IDE.

### ISSUE THREAD

**Issue by mbariola** [platformio/platformio-atom-ide#306] opened 2017-03-31 10:09 UTC
Error: events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: EBUSY: resource busy or locked, open 'C:\Users\Max\AppData\Local\Temp\atom-git-package-clone-117231-5280-1qp3quz\node_modules\lodash-es\_equalObjects.js'
    at Error (native)

    at utils.runAPMCommand.busyTitle (file:///C:/Users/Max/.atom/packages/platformio-ide/lib/installer/ide.js:111:13)
    at onExit (file:///C:/Users/Max/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (file:///C:/Users/Max/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (C:\Users\Max\AppData\Local\atom\app-1.15.0\resources\app.asar\src\buffered-process.js:322:11)
    at ChildProcess.<anonymous> (C:\Users\Max\AppData\Local\atom\app-1.15.0\resources\app.asar\src\buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment] 2017-04-30 20:59
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/294

**Closed by ivankravets** 2017-04-30 20:59 UTC
Labels: duplicate
