### ISSUE TITLE
InstallationManager: AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by graffiti4u** [platformio/platformio-atom-ide#700] opened 2017-07-06 11:17 UTC
Virtualenv Create: Traceback (most recent call last):
  File "/Users/graffiti/.platformio/.cache-ide/tmp-31136vFvR2jOoPvwI/virtualenv-14.0.6/virtualenv.py", line 2304, in <module>
    main()
  File "/Users/graffiti/.platformio/.cache-ide/tmp-31136vFvR2jOoPvwI/virtualenv-14.0.6/virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "/Users/graffiti/.platformio/.cache-ide/tmp-31136vFvR2jOoPvwI/virtualenv-14.0.6/virtualenv.py", line 904, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/Users/graffiti/.platformio/penv/lib/python2.7/posixpath.py", line 360, in abspath
    if not isabs(path):
  File "/Users/graffiti/.platformio/penv/lib/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by ivankravets** [comment] 2017-08-04 17:20
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/681

**Closed by ivankravets** 2017-08-04 17:20 UTC
Labels: duplicate
