### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by garyinbg** [platformio/platformio-atom-ide#1684] opened 2018-03-26 08:43 UTC
Error: Could not install 'toolchain-atmelavr' with version requirements '~1.40902.0' for your system 'windows_x86'.

Please try this solution -> http://bit.ly/faq-package-manager

Then This popped up

Error: [03/26/18 11:42:20] Processing uno (platform: atmelavr; board: uno; framework: arduino)

Verbose mode can be enabled via `-v, --verbose` option
PLATFORM: Atmel AVR > Arduino Uno
SYSTEM: ATMEGA328P 16MHz 2KB RAM (31.50KB Flash)
TypeError: coercing to Unicode: need string or buffer, NoneType found:
File "C:\Users\Gary\.platformio\penv\lib\site-packages\platformio\builder\main.py", line 162:
env.SConscript("$BUILD_SCRIPT")
File "C:\Users\Gary\.platformio\packages\tool-scons\script\..\engine\SCons\Script\SConscript.py", line 541:
return _SConscript(self.fs, *files, **subst_kw)
File "C:\Users\Gary\.platformio\packages\tool-scons\script\..\engine\SCons\Script\SConscript.py", line 250:
exec _file_ in call_stack[-1].globals
File "C:\Users\Gary\.platformio\platforms\atmelavr\builder\main.py", line 224:
target_elf = env.BuildProgram()
File "C:\Users\Gary\.platformio\packages\tool-scons\script\..\engine\SCons\Environment.py", line 224:
return self.method(*nargs, **kwargs)
File "C:\Users\Gary\.platformio\penv\lib\site-packages\platformio\builder\tools\platformio.py", line 70:
env.BuildFrameworks(env.get("PIOFRAMEWORK"))
File "C:\Users\Gary\.platformio\packages\tool-scons\script\..\engine\SCons\Environment.py", line 224:
return self.method(*nargs, **kwargs)
File "C:\Users\Gary\.platformio\penv\lib\site-packages\platformio\builder\tools\platformio.py", line 285:
SConscript(env.GetFrameworkScript(f))
File "C:\Users\Gary\.platformio\packages\tool-scons\script\..\engine\SCons\Script\SConscript.py", line 604:
return method(*args, **kw)
File "C:\Users\Gary\.platformio\packages\tool-scons\script\..\engine\SCons\Script\SConscript.py", line 541:
return _SConscript(self.fs, *files, **subst_kw)
File "C:\Users\Gary\.platformio\packages\tool-scons\script\..\engine\SCons\Script\SConscript.py", line 250:
exec _file_ in call_stack[-1].globals
File "C:\Users\Gary\.platformio\platforms\atmelavr\builder\frameworks\arduino.py", line 34:
assert isdir(FRAMEWORK_DIR)
 [ERROR] Took 1.97 seconds 

Report a problem

**Comment by ivankravets** [comment] 2018-06-20 18:47
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1171

**Closed by ivankravets** 2018-06-20 18:47 UTC
