### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by diving91** [platformio/platformio-atom-ide#376] opened 2017-04-15 12:57 UTC
Virtualenv Download: Traceback (most recent call last):
  File "D:\Users\HERV~1\AppData\Local\Temp\tmp-1216QKnzYoor5t93\virtualenv-15.1.0\virtualenv.py", line 2328, in <module>
    main()
  File "D:\Users\HERV~1\AppData\Local\Temp\tmp-1216QKnzYoor5t93\virtualenv-15.1.0\virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "D:\Users\HERV~1\AppData\Local\Temp\tmp-1216QKnzYoor5t93\virtualenv-15.1.0\virtualenv.py", line 925, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "D:\Users\HERV~1\AppData\Local\Temp\tmp-1216QKnzYoor5t93\virtualenv-15.1.0\virtualenv.py", line 1148, in install_python
    writefile(join(site_dir, 'orig-prefix.txt'), prefix)
  File "D:\Users\HERV~1\AppData\Local\Temp\tmp-1216QKnzYoor5t93\virtualenv-15.1.0\virtualenv.py", line 368, in writefile
    if c != content.encode("utf-8"):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 13: ordinal not in range(128)

**Comment by ivankravets** [comment] 2017-04-30 21:33
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/321

**Closed by ivankravets** 2017-04-30 21:33 UTC
Labels: duplicate
