### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/Documents\GitHub\ESPEasy\src\ESPEasy....

### ISSUE THREAD

**Issue by ThatchSS** [platformio/platformio-atom-ide#1911] opened 2018-06-15 14:31 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.1.4

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\thatc\Documents\GitHub\ESPEasy\src\ESPEasy.ino.cpp'

```
At fs.js:961

Error: ENOENT: no such file or directory, lstat 'C:\Users\thatc\Documents\GitHub\ESPEasy\src\ESPEasy.ino.cpp'
    at fs.lstatSync (fs.js:961:11)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
    at Proxy.realpathSync (fs.js:1641:21)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:321:29)
    at /packages/platformio-ide/lib/project/helpers.js:32:25
    at getActivePioProject (/packages/platformio-ide/lib/project/helpers.js:36:6)
    at Object.highlightActiveProject (/packages/platformio-ide/lib/maintenance.js:133:13)
    at doHighlight (/packages/platformio-ide/lib/main.js:247:43)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at stoppedChangingActivePaneItemTimeout.setTimeout (~/AppData/Local/atom/app-1.27.2/resources/app/src/workspace.js:493:26)
```

### Commands

```
     -0:05.8.0 symbols-view:go-to-declaration (span.syntax--entity.syntax--name.syntax--function.syntax--c)
```

### Non-Core Packages

```
autocomplete-clang 0.11.4 
build 0.70.0 
busy-signal 1.4.3 
file-icons 2.1.21 
intentions 1.1.5 
language-ini 1.20.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
platformio-ide 2.1.4 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.8.1 
tool-bar 1.1.7 
```

**Comment by ivankravets** [comment] 2018-06-20 18:39
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1472

**Closed by ivankravets** 2018-06-20 18:39 UTC
