### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by esron** [platformio/platformio-atom-ide#976] opened 2017-09-22 19:33 UTC
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\gacci\.platformio\.cache\tmp-10700IcLCXyA7SrDl\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\gacci\.platformio\.cache\tmp-10700IcLCXyA7SrDl\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\gacci\.platformio\.cache\tmp-10700IcLCXyA7SrDl\virtualenv-14.0.6\virtualenv.py", line 924, in create_environment
    download=download,
  File "C:\Users\gacci\.platformio\.cache\tmp-10700IcLCXyA7SrDl\virtualenv-14.0.6\virtualenv.py", line 877, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "C:\Users\gacci\.platformio\.cache\tmp-10700IcLCXyA7SrDl\virtualenv-14.0.6\virtualenv.py", line 743, in call_subprocess
    cwd=cwd, env=env)
  File "C:\Users\gacci\.platformio\python27\Lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Users\gacci\.platformio\python27\Lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 5] Acesso negado

**Comment by ivankravets** [comment] 2017-10-17 20:28
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/975

**Closed by ivankravets** 2017-10-17 20:28 UTC
