### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by spaxxomatic** [platformio/platformio-atom-ide#2031] opened 2018-07-21 15:08 UTC
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.22.1
PIO IDE: v2.1.11
System: Windows_NT, 10.0.17134, ia32

# Exception
```
Error: Could not create PIO Core Virtual Environment. Please create it manually -> http://bit.ly/pio-core-virtualenv
    at t.<anonymous> (C:\Users\luci\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1:28854)
    at P (C:\Users\luci\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1:15208)
    at Generator._invoke (C:\Users\luci\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1:14996)
    at Generator.e.(anonymous function) [as throw] (C:\Users\luci\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1:15387)
    at n (C:\Users\luci\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1:21494)
    at C:\Users\luci\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1:21613
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by ivankravets** [comment] 2018-07-26 18:13
Duplicate of https://github.com/platformio/platformio-vscode-ide/issues/154

**Closed by ivankravets** 2018-07-26 18:13 UTC
