### ISSUE TITLE
Error: Could not install package

### ISSUE THREAD

**Issue by xfce** [platformio/platformio-atom-ide#1235] opened 2017-12-05 11:57 UTC
Error: Could not install 'toolchain-xtensa' with version requirements '~1.40802.0' for your system 'windows_amd64'.
If you use Antivirus, it can block PlatformIO Package Manager. Try to disable it for a while.

**Comment by ivankravets** [comment] 2017-12-15 18:48
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment] 2017-12-15 19:07
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1171

**Closed by ivankravets** 2017-12-15 19:07 UTC
Labels: help wanted
