### ISSUE TITLE
InstallationManager - "PIP:"

### ISSUE THREAD

**Issue by M-VdM** [platformio/platformio-atom-ide#1704] opened 2018-03-31 16:16 UTC
PIP:   Could not find a version that satisfies the requirement bottle<0.13 (from platformio==3.5.3a7) (from versions: )
No matching distribution found for bottle<0.13 (from platformio==3.5.3a7)
-------
Just performed a clean install of Mac OS X et al.
**sudo easy_install pip** installed a more recent version of **pip** ...

### Configuration
**Operating system**:  Mac OS X El Capitan _(10.11.6)_
**HDD**:  HFS+  _(Case-sensitive, Journaled)_
**platformio-ide**:  _2.1.3_

### Additional info
**Mac OS X Firewall** = Disabled
$ **echo $PATH**
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
$ **clang --version**
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
$ **python --version**
Python 2.7.10
$ **pip --version**
pip 10.0.0b1 from /Library/Python/2.7/site-packages/pip-10.0.0b1-py2.7.egg/pip (python 2.7)
$ **pip list**
```
Package                                Version 
-------------------------------------- --------
altgraph                               0.10.2  
bdist-mpkg                             0.5.0   
bonjour-py                             0.3     
macholib                               1.5.1   
matplotlib                             1.3.1   
modulegraph                            0.10.4  
numpy                                  1.8.0rc1
pip                                    10.0.0b1
py2app                                 0.7.3   
pyobjc-core                            2.5.1   
pyobjc-framework-Accounts              2.5.1   
pyobjc-framework-AddressBook           2.5.1   
pyobjc-framework-AppleScriptKit        2.5.1   
pyobjc-framework-AppleScriptObjC       2.5.1   
pyobjc-framework-Automator             2.5.1   
pyobjc-framework-CFNetwork             2.5.1   
pyobjc-framework-Cocoa                 2.5.1   
pyobjc-framework-Collaboration         2.5.1   
pyobjc-framework-CoreData              2.5.1   
pyobjc-framework-CoreLocation          2.5.1   
pyobjc-framework-CoreText              2.5.1   
pyobjc-framework-DictionaryServices    2.5.1   
pyobjc-framework-EventKit              2.5.1   
pyobjc-framework-ExceptionHandling     2.5.1   
pyobjc-framework-FSEvents              2.5.1   
pyobjc-framework-InputMethodKit        2.5.1   
pyobjc-framework-InstallerPlugins      2.5.1   
pyobjc-framework-InstantMessage        2.5.1   
pyobjc-framework-LatentSemanticMapping 2.5.1   
pyobjc-framework-LaunchServices        2.5.1   
pyobjc-framework-Message               2.5.1   
pyobjc-framework-OpenDirectory         2.5.1   
pyobjc-framework-PreferencePanes       2.5.1   
pyobjc-framework-PubSub                2.5.1   
pyobjc-framework-QTKit                 2.5.1   
pyobjc-framework-Quartz                2.5.1   
pyobjc-framework-ScreenSaver           2.5.1   
pyobjc-framework-ScriptingBridge       2.5.1   
pyobjc-framework-SearchKit             2.5.1   
pyobjc-framework-ServiceManagement     2.5.1   
pyobjc-framework-Social                2.5.1   
pyobjc-framework-SyncServices          2.5.1   
pyobjc-framework-SystemConfiguration   2.5.1   
pyobjc-framework-WebKit                2.5.1   
pyOpenSSL                              0.13.1  
pyparsing                              2.0.1   
python-dateutil                        1.5     
pytz                                   2013.7  
scipy                                  0.13.0b1
setuptools                             1.1.6   
six                                    1.4.1   
xattr                                  0.6.4   
zope.interface                         4.1.1 
```

**Comment by ivankravets** [comment] 2018-04-09 05:00
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1592

**Closed by ivankravets** 2018-04-09 05:00 UTC
