### ISSUE TITLE
Error: Could not install package

### ISSUE THREAD

**Issue by thiaguim18** [platformio/platformio-atom-ide#1262] opened 2017-12-13 04:19 UTC
Error: Could not install 'framework-arduinoavr' with version requirements '~1.10620.0' for your system 'windows_amd64'.
If you use Antivirus, it can block PlatformIO Package Manager. Try to disable it for a while.

**Comment by ivankravets** [comment] 2017-12-15 17:26
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment] 2017-12-15 19:07
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1171

**Closed by ivankravets** 2017-12-15 19:07 UTC
Labels: help wanted
