### ISSUE TITLE
InstallationManager (windows)

### ISSUE THREAD

**Issue by egn-dev** [platformio/platformio-atom-ide#414] opened 2017-04-27 23:14 UTC
Virtualenv Download: Traceback (most recent call last):
  File "C:/Users/admin/.platformio/penv/lib/python2.7/site.py", line 703, in <module>
    main()
  File "C:/Users/admin/.platformio/penv/lib/python2.7/site.py", line 692, in main
    aliasmbcs()
  File "C:/Users/admin/.platformio/penv/lib/python2.7/site.py", line 515, in aliasmbcs
    import locale, codecs
  File "C:\Users\admin\.platformio\penv\lib\python2.7/locale.py", line 17, in <module>
    import functools
ImportError: No module named functools

OS: Windows 10 b1607 x64
Python: 3.6.1 x64 in "C:\Program Files\Python36" (no Python 2.x installations)
Atom: 1.16.0 x64
LLVM: 4.0.0 x64 in "C:\Program Files\LLVM"

**Comment by ivankravets** [comment] 2017-05-01 11:35
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/337

**Closed by ivankravets** 2017-05-01 11:35 UTC
Labels: bug, duplicate
