### ISSUE TITLE
Uncaught Error: Could not start PIO Home server: Traceback (most recent call last):  File "~/.p...

### ISSUE THREAD

**Issue by edbrunton** [platformio/platformio-atom-ide#1392] opened 2018-01-15 19:33 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Education
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.0.0-rc.7

### Stack Trace

Uncaught Error: Could not start PIO Home server: Traceback (most recent call last):
  File "C:\Users\edbru\.platformio\penv\Scripts\platformio-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\users\edbru\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 3147, in <module>
    @_call_aside
  File "c:\users\edbru\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 3131, in _call_aside
    f(*args, **kwargs)
  File "c:\users\edbru\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 3160, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\users\edbru\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "c:\users\edbru\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\users\edbru\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'platformio==3.5.1a6' distribution was not found and is required by the application

```
At C:\Users\edbru\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1612

Error: Could not start PIO Home server: Traceback (most recent call last):
  File "C:\Users\edbru\.platformio\penv\Scripts\platformio-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\users\edbru\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 3147, in <module>
    @_call_aside
  File "c:\users\edbru\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 3131, in _call_aside
    f(*args, **kwargs)
  File "c:\users\edbru\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 3160, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\users\edbru\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "c:\users\edbru\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\users\edbru\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'platformio==3.5.1a6' distribution was not found and is required by the application

    at /packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1612:23
    at ChildProcess.onExit (/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:534:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (/packages/platformio-ide/node_modules/cross-spawn/lib/enoent.js:40:29)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-clang 0.11.4 
build 0.70.0 
busy-signal 1.4.3 
file-icons 2.1.15 
intentions 1.1.5 
language-ini 1.19.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.6.10 
platformio-ide 2.0.0-rc.7 
platformio-ide-debugger 1.2.5 
platformio-ide-terminal 2.8.0 
tool-bar 1.1.4 
```

**Comment by ivankravets** [comment] 2018-01-16 18:33
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1304

**Closed by ivankravets** 2018-01-16 18:33 UTC
