### ISSUE TITLE
Gr eiainErr oe0pnce Itrutwttmoto P0) Error. and broken character

### ISSUE THREAD

**Issue by wjm0621** [platformio/platformio-atom-ide#560] opened 2017-06-03 09:37 UTC
![esp error](https://cloud.githubusercontent.com/assets/4524843/26752454/08c10218-488b-11e7-9d47-5ccefce3284c.png)

I'm Using Sparkfun ESP32 Thing. and sending websocket message.
At the shown image, I met Gr eiainErr oe0pnce Itrutwttmoto P0) Error....

It is not always raised. just somtime shown.
I can't find this at google.

What is this Error means??

And some character is broken. (broken character is English character)
At shown image, code line 146. It will print "TCP handshaking with Server Connected. "
But below the Code, at word "handshaking", 'k', 'n' are broke.
How can i fix this problem??

**Comment by ivankravets** [comment] 2017-06-03 11:32
Duplicate of https://github.com/platformio/platform-espressif32/issues/23

**Comment by ImanolGo** [comment] 2017-06-18 09:51
Were you able to solve it? I have exactly the same issue!

**Comment by wjm0621** [comment] 2017-06-18 12:04
I Can't solve it yet..

**Comment by ImanolGo** [comment] 2017-06-20 20:42
I change the board and that solved the issue.

**Comment by ivankravets** [comment] 2017-06-20 21:24
@ImanolGo what was your previous board?

**Comment by ImanolGo** [comment] 2017-06-21 15:55
My previous board was the Sparkfun ESP32 Thing.

Now I changed to the  HIMALAYA ESP32 Dev Board.

**Comment by ivankravets** [comment] 2017-06-27 23:04
Is this a bug with a board?

**Comment by ImanolGo** [comment] 2017-06-28 07:48
Maybe. I tried it in two different Sparkfun ESP32 Thing boards, both with the same results.

**Comment by ivankravets** [comment] 2017-06-28 09:42
Does it work with Arduino IDE serial port monitor?

**Closed** 2017-06-28 10:39 UTC
