### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by Phr3d13** [platformio/platformio-atom-ide#1874] opened 2018-05-29 09:33 UTC
If you use Antivirus, it can block PlatformIO Installer. Try to disable it for a while.

Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\Phr3d13\.platformio\.cache\tmp-13600HCbSHRsYL7A8\virtualenv-15.2.0\virtualenv.py", line 2349, in <module>
    main()
  File "C:\Users\Phr3d13\.platformio\.cache\tmp-13600HCbSHRsYL7A8\virtualenv-15.2.0\virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "C:\Users\Phr3d13\.platformio\.cache\tmp-13600HCbSHRsYL7A8\virtualenv-15.2.0\virtualenv.py", line 953, in create_environment
    download=download,
  File "C:\Users\Phr3d13\.platformio\.cache\tmp-13600HCbSHRsYL7A8\virtualenv-15.2.0\virtualenv.py", line 904, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "C:\Users\Phr3d13\.platformio\.cache\tmp-13600HCbSHRsYL7A8\virtualenv-15.2.0\virtualenv.py", line 752, in call_subprocess
    cwd=cwd, env=env)
  File "C:\Python27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 5] Access is denied

**Comment by ivankravets** [comment] 2018-06-20 18:57
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1191

**Closed by ivankravets** 2018-06-20 18:57 UTC
