### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by Joob1965** [platformio/platformio-atom-ide#1768] opened 2018-04-17 17:38 UTC
Cloning into 'C:\Users\Joach\OneDrive\Desktop\espurna-e6e9f9d6d4bd16005446e08b98d47c6cd254ad16\code\.piolibdeps\_tmp_installing-m2tqeo-package'...
Cloning into 'C:\Users\Joach\OneDrive\Desktop\espurna-e6e9f9d6d4bd16005446e08b98d47c6cd254ad16\code\.piolibdeps\_tmp_installing-9jgacy-package'...
Cloning into 'C:\Users\Joach\OneDrive\Desktop\espurna-e6e9f9d6d4bd16005446e08b98d47c6cd254ad16\code\.piolibdeps\_tmp_installing-yowny9-package'...
Cloning into 'C:\Users\Joach\OneDrive\Desktop\espurna-e6e9f9d6d4bd16005446e08b98d47c6cd254ad16\code\.piolibdeps\_tmp_installing-gfwzd8-package'...
Cloning into 'C:\Users\Joach\OneDrive\Desktop\espurna-e6e9f9d6d4bd16005446e08b98d47c6cd254ad16\code\.piolibdeps\_tmp_installing-gvyvxd-package'...
Note: checking out '9e9edca2313b757eed2a55e55716cb7debd87383'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Cloning into 'C:\Users\Joach\OneDrive\Desktop\espurna-e6e9f9d6d4bd16005446e08b98d47c6cd254ad16\code\.piolibdeps\_tmp_installing-l6dugl-package'...
warning: Could not find remote branch 1.0.1 to clone.
fatal: Remote branch 1.0.1 not found in upstream origin
Error: Traceback (most recent call last):
  File "c:\users\joach\.platformio\penv\lib\site-packages\platformio\__main__.py", line 120, in main
    cli(None, None, None)
  File "c:\users\joach\.platformio\penv\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\joach\.platformio\penv\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\users\joach\.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\joach\.platformio\penv\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\joach\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\users\joach\.platformio\penv\lib\site-packages\click\decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\joach\.platformio\penv\lib\site-packages\platformio\commands\init.py", line 102, in cli
    pg = ProjectGenerator(project_dir, ide, env_name)
  File "c:\users\joach\.platformio\penv\lib\site-packages\platformio\ide\projectgenerator.py", line 35, in __init__
    self._gather_tplvars()
  File "c:\users\joach\.platformio\penv\lib\site-packages\platformio\ide\projectgenerator.py", line 151, in _gather_tplvars
    self._tplvars.update(self.get_project_build_data())
  File "c:\users\joach\.platformio\penv\lib\site-packages\platformio\ide\projectgenerator.py", line 75, in get_project_build_data
    raise result.exception
WindowsError: [Error 5] Zugriff verweigert: 'C:\\Users\\Joach\\OneDrive\\Desktop\\espurna-e6e9f9d6d4bd16005446e08b98d47c6cd254ad16\\code\\.piolibdeps\\_tmp_installing-l6dugl-package'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by ivankravets** [comment] 2018-06-20 18:47
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1171

**Closed by ivankravets** 2018-06-20 18:47 UTC
