### ISSUE TITLE
Problem occured while upgrading PlatformIO IDE

### ISSUE THREAD

**Issue by tassheloff** [platformio/platformio-atom-ide#1470] opened 2018-02-01 22:16 UTC
Error: Cannot read property 'getReferenceTarget' of null

    at file:///C:/Users/fabio/.atom/packages/platformio-ide/lib/installer/ide.js:59:9
    at Generator.throw (<anonymous>)
    at step (file:///C:/Users/fabio/.atom/packages/platformio-ide/lib/installer/ide.js:176:2)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by reloxx13** [comment] 2018-02-04 19:01
+1 same here

**Comment by ivankravets** [comment] 2018-02-05 23:37
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1394

**Closed by ivankravets** 2018-02-05 23:37 UTC
