### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by burtonscomputers** [platformio/platformio-atom-ide#1358] opened 2018-01-08 22:24 UTC
Virtualenv Create: Traceback (most recent call last):
  File "/home/glenn/.platformio/.cache/tmp-13723F7EA7YKUaiE4/virtualenv-14.0.6/virtualenv.py", line 21, in <module>
    import logging
  File "/usr/lib/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref

**Comment by ivankravets** [comment] 2018-01-10 12:27
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1298

See https://community.platformio.org/t/cant-get-pio-to-work-home-doesnt-want-to-load/2755/15?u=ivankravets

**Closed by ivankravets** 2018-01-10 12:27 UTC
