### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by vstoms** [platformio/platformio-atom-ide#1887] opened 2018-06-05 16:29 UTC
Error: [API] Could not connect to PlatformIO API Service. Please try later.

Looks like that the the whole site is down.

**Comment by ivankravets** [comment] 2018-06-05 18:54
Duplicate of https://github.com/platformio/platformio-core/issues/1658

**Closed by ivankravets** 2018-06-05 18:54 UTC
