### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by frankleonrose** [platformio/platformio-atom-ide#709] opened 2017-07-07 11:58 UTC
Problem upgrading to PlatformIO IDE beta from 1.7.3.
```
Virtualenv Create: Traceback (most recent call last):
  File "/Users/frank/.platformio/.cache-ide/tmp-80440pFYc70Gvyw4W/virtualenv-14.0.6/virtualenv.py", line 2304, in <module>

    main()
  File "/Users/frank/.platformio/.cache-ide/tmp-80440pFYc70Gvyw4W/virtualenv-14.0.6/virtualenv.py", line 705, in main

    symlink=options.symlink)
  File "/Users/frank/.platformio/.cache-ide/tmp-80440pFYc70Gvyw4W/virtualenv-14.0.6/virtualenv.py", line 904, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/Users/frank/.platformio/penv/bin/../lib/python2.7/posixpath.py", line 360, in abspath
    if not isabs(path):
  File "/Users/frank/.platformio/penv/bin/../lib/python2.7/posixpath.py", line 54, in isabs

    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by ivankravets** [comment] 2017-08-04 17:21
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/681

**Closed by ivankravets** 2017-08-04 17:21 UTC
Labels: duplicate
