### ISSUE TITLE
When a filesystem path is passed in within lib_deps in platformio.ini, the index rebuilding loops

### ISSUE THREAD

**Issue by jasiek** [platformio/platformio-atom-ide#213] opened 2017-02-07 21:00 UTC
How to reproduce?

In your platformio.ini file, add a reference to a dependent library, that resides elsewhere on the filesystem, for example:

```
[env:nodemcuv2]
platform = espressif8266
framework = arduino
board = nodemcuv2
lib_deps =
  ArduinoJson
  DHT sensor library
  Adafruit Unified Sensor
  Adafruit BMP085 Library
  https://github.com/jasiek/Adafruit_HTU21DF_Library.git
  /Users/jps/github/metering
```

After saving that file the IDE appears to constantly re-index the project, alternating between the two dialogs attached below.
![screen shot 2017-02-07 at 20 59 47](https://cloud.githubusercontent.com/assets/37550/22711266/6d0a65f2-ed78-11e6-8d7b-5160fde09d41.png)

**Comment by ivankravets** [comment] 2017-02-07 21:04
Temporary solution is to move `/Users/jps/github/metering` to 
```
lib_extra_dirs = /Users/jps/github
```

**Comment by ivankravets** [comment] 2017-02-21 15:33
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/179

**Closed by ivankravets** 2017-02-21 15:33 UTC
Labels: bug
