### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by szmolnar** [platformio/platformio-atom-ide#1425] opened 2018-01-23 17:52 UTC
Error: Could not install 'framework-arduinoespressif32' with version requirements '~1.3.2' for your system 'darwin_x86_64'.
More details: http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment] 2018-01-27 22:37
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1393

**Closed by ivankravets** 2018-01-27 22:37 UTC
