### ISSUE TITLE
Platform command failed: platform install linux_arm

### ISSUE THREAD

**Issue by scientronic92** [platformio/platformio-atom-ide#328] opened 2017-04-03 13:17 UTC
Error: Error: Could not find a version that satisfies the requirement '~1.40802.0' for your system 'windows_amd64'

    at file:///C:/Users/Omer/.atom/packages/platformio-ide/lib/platform/helpers.js:61:25
    at onExit (file:///C:/Users/Omer/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (file:///C:/Users/Omer/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (C:\Users\Omer\AppData\Local\atom\app-1.15.0\resources\app.asar\src\buffered-process.js:322:11)
    at ChildProcess.<anonymous> (C:\Users\Omer\AppData\Local\atom\app-1.15.0\resources\app.asar\src\buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment] 2017-04-30 21:29
Duplicate of https://github.com/platformio/platform-linux_arm/issues/2

**Closed by ivankravets** 2017-04-30 21:29 UTC
Labels: duplicate
