### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by Joob1965** [platformio/platformio-atom-ide#1610] opened 2018-03-08 19:12 UTC
Virtualenv Create:   File "C:\Users\Joach\AppData\Local\Programs\Python\Python36\lib\site.py", line 177
    file=sys.stderr)
        ^
SyntaxError: invalid syntax

**Comment by ivankravets** [comment] 2018-06-20 18:05
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/922

**Closed by ivankravets** 2018-06-20 18:05 UTC
