### ISSUE TITLE
Problem occured while upgrading PlatformIO IDE

### ISSUE THREAD

**Issue by ejngnng** [platformio/platformio-atom-ide#1789] opened 2018-04-23 04:08 UTC
Error: 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.5 | win32 | x64
gyp http GET https://atom.io/download/electron/v1.7.11/iojs-v1.7.11.tar.gz
gyp http 200 https://atom.io/download/electron/v1.7.11/iojs-v1.7.11.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: ENOENT: no such file or directory, lstat 'C:\Users\ninja\.atom\.node-gyp\.node-gyp\iojs-1.7.11\deps\v8\include\v8.h'
gyp ERR! stack     at Error (native)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Users\\ninja\\AppData\\Local\\atom\\app-1.25.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\ninja\\AppData\\Local\\atom\\app-1.25.1\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install" "--runtime=electron" "--target=1.7.11" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd C:\Users\ninja\.atom
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

    at file:///C:/Users/ninja/.atom/packages/platformio-ide/lib/installer/ide.js:59:9
    at Generator.throw (<anonymous>)
    at step (file:///C:/Users/ninja/.atom/packages/platformio-ide/lib/installer/ide.js:176:2)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by ivankravets** [comment] 2018-06-20 18:39
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1472

**Closed by ivankravets** 2018-06-20 18:39 UTC
