### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by hacordero** [platformio/platformio-atom-ide#2022] opened 2018-07-17 17:24 UTC
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.1
PIO IDE: v2.1.8
System: Windows_NT, 10.0.17134, x64

# Exception
```
"platformio" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
Error: spawn platformio ENOENT
```

**Comment by ivankravets** [comment] 2018-07-18 13:04
Could you reproduce this issue after IDE restart?

**Comment by ivankravets** [comment] 2018-07-19 15:21
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1243

**Closed by ivankravets** 2018-07-19 15:21 UTC
