### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by PeteVino** [platformio/platformio-atom-ide#1781] opened 2018-04-20 05:26 UTC
Error: Could not install 'framework-arduinoespressif8266' with version requirements '~1.20400.0' for your system 'windows_x86'.

Please try this solution -> http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment] 2018-06-20 18:46
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1171

**Closed by ivankravets** 2018-06-20 18:46 UTC
