### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/CloudStation\Smart home system Domino...

### ISSUE THREAD

**Issue by studentstudio** [platformio/platformio-atom-ide#2000] opened 2018-07-11 16:18 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.1 x64
**Electron**: 2.0.4
**OS**: Unknown Windows version
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.1.7

### Stack Trace

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat 'C:\Users\MSI\CloudStation\Smart home system Domino\Projekty\Oven\Code\src'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:320:29)
    at /packages/platformio-ide/lib/project/helpers.js:32:25
    at getActivePioProject (/packages/platformio-ide/lib/project/helpers.js:36:6)
    at Object.highlightActiveProject (/packages/platformio-ide/lib/maintenance.js:75:13)
    at doHighlight (/packages/platformio-ide/lib/main.js:247:43)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.28.1/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.28.1/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at stoppedChangingActivePaneItemTimeout.setTimeout (~/AppData/Local/atom/app-1.28.1/resources/app/src/workspace.js:493:26)
```

### Commands

```
     -3:11.9.0 intentions:highlight (input.hidden-input)
     -3:11.8.0 editor:delete-to-end-of-word (input.hidden-input)
     -3:10.6.0 intentions:highlight (input.hidden-input)
     -3:10.3.0 core:undo (input.hidden-input)
     -3:09.5.0 intentions:highlight (input.hidden-input)
  2x -3:09.2.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -3:07.4.0 intentions:highlight (input.hidden-input)
     -3:07.2.0 editor:delete-line (input.hidden-input)
  3x -3:06.3.0 intentions:highlight (input.hidden-input)
     -3:05.7.0 core:save (input.hidden-input)
     -3:02.8.0 platformio-ide:target:build (input.hidden-input)
     -3:02.8.0 platformio-ide:target:build-C:\Users\MSI\CloudStation\Smart home system Domino\Projekty\Oven\Code (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:49.5.0 tree-view:move (div.tool-panel.tree-view)
     -2:47.3.0 core:confirm (input.hidden-input)
     -2:43.8.0 platformio-ide:target:build (div.tool-panel.tree-view)
     -2:43.8.0 platformio-ide:target:build-C:\Users\MSI\CloudStation\Smart home system Domino\Projekty\Oven\Code (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
autocomplete-clang 0.11.5 
build 0.70.0 
busy-signal 1.4.3 
file-icons 2.1.22 
intentions 1.1.5 
language-ini 1.20.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
platformio-ide 2.1.7 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.8.3 
tool-bar 1.1.7 
```

**Comment by ivankravets** [comment] 2018-07-19 15:03
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1472

**Closed by ivankravets** 2018-07-19 15:03 UTC
