### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by mrdomiciano** [platformio/platformio-atom-ide#400] opened 2017-04-22 23:01 UTC
Virtualenv Download:   File "C:\Apps\Python36-32\lib\site.py", line 177
    file=sys.stderr)
        ^
SyntaxError: invalid syntax

**Comment by ivankravets** [comment] 2017-04-30 22:10
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/367

**Closed by ivankravets** 2017-04-30 22:10 UTC
Labels: duplicate
