### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by Philxw** [platformio/platformio-atom-ide#2012] opened 2018-07-14 10:08 UTC
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.2
PIO IDE: v2.1.7
System: Windows_NT, 10.0.16299, x64

# Exception
```
Traceback (most recent call last):
  File "main.py", line 16, in init main
  File "cmd_debug.py", line 24, in init cmd_debug
  File "C:\Users\meerk\.platformio\packages\contrib-pysite\twisted\__init__.py", line 11, in <module>
    from twisted._version import __version__ as version
  File "C:\Users\meerk\.platformio\packages\contrib-pysite\twisted\_version.py", line 8, in <module>
    from incremental import Version
ImportError: No module named incremental

```

**Comment by ivankravets** [comment] 2018-07-17 13:40
Duplicate of https://github.com/platformio/platformio-vscode-ide/issues/165

**Closed by ivankravets** 2018-07-17 13:40 UTC
