### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by syk543277780** [platformio/platformio-atom-ide#2041] opened 2018-07-24 23:43 UTC
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.2
PIO IDE: v2.1.7
System: Windows_NT, 10.0.16299, x64

# Exception
```
Please manually remove file `C:\Users\yongkang.song\.platformio\packages\tool-pioplus\pioplus.exe`
Please manually remove file `C:\Users\yongkang.song\.platformio\packages\tool-pioplus\pioplus.exe`
Error: Could not install 'tool-pioplus' with version requirements '^1.4.0' for your system 'windows_amd64'.

Please try this solution -> http://bit.ly/faq-package-manager

```

**Comment by ivankravets** [comment] 2018-07-26 17:58
Duplicate of https://github.com/platformio/platformio-vscode-ide/issues/131

**Closed by ivankravets** 2018-07-26 17:58 UTC
