### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by gallaxymv6** [platformio/platformio-atom-ide#1647] opened 2018-03-17 08:16 UTC
PIP: Error: spawn /Volumes/mac OS HDD/Users/klaus/.platformio/penv/bin/pip ENOENT

**Comment by ivankravets** [comment] 2018-06-20 18:43
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1243

**Closed by ivankravets** 2018-06-20 18:43 UTC
