### ISSUE TITLE
Problem has beenn occured while uprading PlatformIO IDE.

### ISSUE THREAD

**Issue by prasenjit09** [platformio/platformio-atom-ide#351] opened 2017-04-10 04:51 UTC
Error: Cannot read property 'getReferenceTarget' of null

    at utils.runAPMCommand (ide.js:111:13)
    at onExit (utils.js:92:7)
    at exit (utils.js:102:21)
    at triggerExitCallback (C:\Users\PRASENJIT\AppData\Local\atom\app-1.16.0-beta0\resources\app.asar\src\buffered-process.js:265:9)
    at ChildProcess.process.on.code (C:\Users\PRASENJIT\AppData\Local\atom\app-1.16.0-beta0\resources\app.asar\src\buffered-process.js:295:9)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment] 2017-04-30 21:00
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/294

**Closed by ivankravets** 2017-04-30 21:00 UTC
Labels: duplicate
