### ISSUE TITLE
 Could not install package

### ISSUE THREAD

**Issue by BabarRehman** [platformio/platformio-atom-ide#1239] opened 2017-12-05 16:15 UTC
Error: Could not install 'toolchain-xtensa32' with version requirements '~2.50200.0' for your system 'windows_amd64'.
If you use Antivirus, it can block PlatformIO Package Manager. Try to disable it for a while.

**Comment by ivankravets** [comment] 2017-12-15 18:44
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment] 2017-12-15 19:07
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1171

**Closed by ivankravets** 2017-12-15 19:07 UTC
Labels: help wanted
