### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.27.1\@otacon...

### ISSUE THREAD

**Issue by mz2212** [platformio/platformio-atom-ide#1856] opened 2018-05-23 03:50 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.1 x64
**Electron**: 1.7.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.1.4

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\mikey\AppData\Local\atom\app-1.27.1\@otacon239:180522-200204-featheresp32'

```
At fs.js:961

Error: ENOENT: no such file or directory, lstat 'C:\Users\mikey\AppData\Local\atom\app-1.27.1\@otacon239:180522-200204-featheresp32'
    at fs.lstatSync (fs.js:961:11)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
    at Proxy.realpathSync (fs.js:1641:21)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:321:29)
    at /packages/platformio-ide/lib/project/helpers.js:32:25
    at getActivePioProject (/packages/platformio-ide/lib/project/helpers.js:36:6)
    at Object.highlightActiveProject (/packages/platformio-ide/lib/maintenance.js:133:13)
    at doHighlight (/packages/platformio-ide/lib/main.js:247:43)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.27.1/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.27.1/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at stoppedChangingActivePaneItemTimeout.setTimeout (~/AppData/Local/atom/app-1.27.1/resources/app/src/workspace.js:493:26)
```

### Commands

```
     -9:25.8.0 intentions:highlight (input.hidden-input)
     -9:25.7.0 core:save (input.hidden-input)
     -9:24.5.0 build:refresh-targets (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.teletype-Authenticated.teletype-Guest)
     -9:10.4.0 platformio-ide:target:upload (input.hidden-input)
     -9:10.4.0 platformio-ide:target:upload-C:\Users\mikey\Documents\Arduino\OLEDSysMon\ESP8266 (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.teletype-Authenticated.teletype-Guest)
     -8:11 core:copy (span.syntax--keyword.syntax--other.syntax--definition.syntax--ini)
     -1:09.2.0 core:backspace (input.hidden-input)
     -0:55 editor:newline (input.hidden-input)
  2x -0:49.3.0 core:backspace (input.hidden-input)
     -0:39.5.0 editor:newline (input.hidden-input)
     -0:35.6.0 core:backspace (input.hidden-input)
     -0:09.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-clang 0.11.4 
build 0.70.0 
busy-signal 1.4.3 
file-icons 2.1.21 
intentions 1.1.5 
language-ini 1.20.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
platformio-ide 2.1.4 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.8.1 
teletype 0.13.2 
tool-bar 1.1.7 
```

Using atom teletype with a friend, and every time I edit a file in his editor, it does this.

**Comment by ivankravets** [comment] 2018-06-20 18:39
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1472

**Closed by ivankravets** 2018-06-20 18:39 UTC
