### ISSUE TITLE
Arduino.h not found - Building Arduino as ESP32 ESP-IDF component using PlatformIO + Atom

### ISSUE THREAD

**Issue by anilanilb** [platformio/platformio-atom-ide#615] opened 2017-06-12 20:01 UTC
Hi,
Copying issue from https://github.com/platformio/platform-espressif32/issues/24 to platformio-atom-ide.

Currently I am building Arduino as ESP32 ESP-IDF component using PlatformIO + Atom. The Platform.ini file details are as below:
[env:esp32dev]
platform = espressif32
framework = espidf
board = esp32dev

According to the docs https://github.com/espressif/arduino-esp3217 (section: Using as ESP-IDF component) the ESP-IDF Framework can have Arduino as component (and this works with ESP-IDF using make flash). Trying the same with PlatformIO, but compiler throws an error that Arduino.h cannot be found.

Is this an issue or do I need to make some changes which I am not aware of? hope somebody can help here.

------------- Log Start -----------------
Processing esp32dev (platform: espressif32; lib_ldf_mode: deep; board: esp32dev; framework: espidf)

Verbose mode can be enabled via -v, --verbose option
Collected 0 compatible libraries
Looking for dependencies...
Project does not have dependencies
Compiling .pioenvs\esp32dev\src\main.o

Generating partitions .pioenvs\esp32dev\partitions_table.bin
Generating LD script .pioenvs\esp32dev\esp32_out.ld
Compiling .pioenvs\esp32dev\bootloader\bootloader_start.o
Compiling .pioenvs\esp32dev\bootloaderSupport\src\bootloader_flash.o
Compiling .pioenvs\esp32dev\bootloaderSupport\src\bootloader_random.o
Compiling .pioenvs\esp32dev\bootloaderSupport\src\efuse.o
Compiling .pioenvs\esp32dev\bootloaderSupport\src\esp_image_format.o
Compiling .pioenvs\esp32dev\bootloaderSupport\src\flash_encrypt.o
Compiling .pioenvs\esp32dev\bootloaderSupport\src\flash_partitions.o
src\main.c:8:52: fatal error: components/arduino/cores/esp32/Arduino.h: No such file or directory
compilation terminated.
*** [.pioenvs\esp32dev\src\main.o] Error 1
------------- Log End ------------------

Regards,
Andy

**Comment by ivankravets** [comment] 2017-06-27 22:48
Duplicate of https://github.com/platformio/platform-espressif32/issues/24

**Closed by ivankravets** 2017-06-27 22:48 UTC
