### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by silmaril42** [platformio/platformio-atom-ide#1600] opened 2018-03-06 19:53 UTC
Error: spawn platformio ENOENT

This error occured when I tried to install the library "DHT" by Mark Ruys.

**Comment by ivankravets** [comment] 2018-06-20 18:44
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1243

**Closed by ivankravets** 2018-06-20 18:44 UTC
