### ISSUE TITLE
InstallationManager: Error: invalid tar file

### ISSUE THREAD

**Issue by chris-zen** [platformio/platformio-atom-ide#348] opened 2017-04-09 18:13 UTC
Error: Error: invalid tar file
    at ProjectExamplesStage.<anonymous> (/Users/chris/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at throw (<anonymous>)
    at step (/Users/chris/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:13:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment] 2017-05-06 12:51
Could try upgrading to PIO IDE 2.0 Beta 3? Does it work now?

**Comment by ivankravets** [comment] 2017-05-06 12:58
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/284

**Closed by ivankravets** 2017-05-06 12:58 UTC
Labels: duplicate
