### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by longearshortail** [platformio/platformio-atom-ide#2011] opened 2018-07-13 08:01 UTC
# Description of problem
When I upload bin into the 8266 chip, it's appeared.

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.1
PIO IDE: v2.1.7
System: Windows_NT, 6.1.7601, x64

# Exception
```
'platformio' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
Error: spawn platformio ENOENT
```

**Comment by ivankravets** [comment] 2018-07-17 13:55
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1243

**Closed by ivankravets** 2018-07-17 13:55 UTC
