### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by electricidea** [platformio/platformio-atom-ide#1678] opened 2018-03-24 20:49 UTC
Error: [03/24/18 21:47:11] Processing adafruit_feather_m0_express (platform: atmelsam; board: adafruit_feather_m0_express; framework: arduino)

PackageManager: Installing framework-arduinosam @ ~2.10618.1
Downloading...
Unpacking...
Verbose mode can be enabled via `-v, --verbose` option
PLATFORM: Atmel SAM > Adafruit Feather M0 Express
SYSTEM: SAMD21G18A 48MHz 32KB RAM (256KB Flash)
DEBUG: CURRENT(atmel-ice) EXTERNAL(atmel-ice, blackmagic, jlink)
TypeError: coercing to Unicode: need string or buffer, NoneType found:
File "C:\users\hague\.platformio\penv\lib\site-packages\platformio\builder\main.py", line 162:
env.SConscript("$BUILD_SCRIPT")
File "C:\Users\Hague\.platformio\packages\tool-scons\script\..\engine\SCons\Script\SConscript.py", line 541:
return _SConscript(self.fs, *files, **subst_kw)
File "C:\Users\Hague\.platformio\packages\tool-scons\script\..\engine\SCons\Script\SConscript.py", line 250:
exec _file_ in call_stack[-1].globals
File "C:\users\hague\.platformio\platforms\atmelsam\builder\main.py", line 162:
target_elf = env.BuildProgram()
File "C:\Users\Hague\.platformio\packages\tool-scons\script\..\engine\SCons\Environment.py", line 224:
return self.method(*nargs, **kwargs)
File "C:\users\hague\.platformio\penv\lib\site-packages\platformio\builder\tools\platformio.py", line 70:
env.BuildFrameworks(env.get("PIOFRAMEWORK"))
File "C:\Users\Hague\.platformio\packages\tool-scons\script\..\engine\SCons\Environment.py", line 224:
return self.method(*nargs, **kwargs)
File "C:\users\hague\.platformio\penv\lib\site-packages\platformio\builder\tools\platformio.py", line 285:
SConscript(env.GetFrameworkScript(f))
File "C:\Users\Hague\.platformio\packages\tool-scons\script\..\engine\SCons\Script\SConscript.py", line 604:
return method(*args, **kw)
File "C:\Users\Hague\.platformio\packages\tool-scons\script\..\engine\SCons\Script\SConscript.py", line 541:
return _SConscript(self.fs, *files, **subst_kw)
File "C:\Users\Hague\.platformio\packages\tool-scons\script\..\engine\SCons\Script\SConscript.py", line 250:
exec _file_ in call_stack[-1].globals
File "C:\users\hague\.platformio\platforms\atmelsam\builder\frameworks\arduino.py", line 33:
assert isdir(FRAMEWORK_DIR)
 [ERROR] Took 84.81 seconds

**Comment by ivankravets** [comment] 2018-06-21 09:59
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1171

**Closed by ivankravets** 2018-06-21 09:59 UTC
