### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by HBeserra** [platformio/platformio-atom-ide#942] opened 2017-09-13 21:23 UTC
Error: Error: Failed to download file https://github.com/platformio/platformio-examples/tarball/master: 
    at ProjectExamplesStage.<anonymous> (file:///C:/Users/herbe/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at throw (<anonymous>)
    at step (C:\Users\herbe\.atom\packages\platformio-ide\lib\installer\stages\project-examples.js:13:273)

**Comment by ivankravets** [comment] 2017-10-17 12:25
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/934

**Closed by ivankravets** 2017-10-17 12:25 UTC
