### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by ujjwaal** [platformio/platformio-atom-ide#1269] opened 2017-12-15 17:24 UTC
Error: Could not install 'atmelavr' with version requirements '*' for your system 'linux_x86_64'.
If you use Antivirus, it can block PlatformIO Package Manager. Try to disable it for a while.

**Comment by ivankravets** [comment] 2017-12-15 17:25
Please provide an output from a system Terminal
```
echo $PATH
echo $PYTHONPATH
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment] 2017-12-15 19:05
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1262

**Closed by ivankravets** 2017-12-15 19:05 UTC
Labels: help wanted
