### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by NatureProtect** [platformio/platformio-atom-ide#1019] opened 2017-10-09 14:40 UTC
PIP: Exception:
Traceback (most recent call last):
  File "C:\.platformio\penv\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\.platformio\penv\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "C:\.platformio\penv\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "C:\.platformio\penv\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\.platformio\penv\lib\site-packages\pip\req\req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "C:\.platformio\penv\lib\site-packages\pip\download.py", line 821, in unpack_url
    hashes=hashes
  File "C:\.platformio\penv\lib\site-packages\pip\download.py", line 659, in unpack_http_url
    hashes)
  File "C:\.platformio\penv\lib\site-packages\pip\download.py", line 880, in _download_http_url
    file_path = os.path.join(temp_dir, filename)
  File "C:\.platformio\penv\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcd in position 7: ordinal not in range(128)

**Comment by ivankravets** [comment] 2017-10-17 13:58
Duplicate of #812

**Closed by ivankravets** 2017-10-17 13:58 UTC
