### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by cjdg** [platformio/platformio-atom-ide#973] opened 2017-09-22 16:38 UTC
Error: Error: Failed to download file examples.tar.gz
  at ProjectExamplesStage.<anonymous> (/home/cjdg/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:201:15)
  at Generator.throw (<anonymous>:null:null)
  at step (/home/cjdg/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:13:273)

**Comment by ivankravets** [comment] 2017-10-17 12:25
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/934

**Closed by ivankravets** 2017-10-17 12:25 UTC
