### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by outlawza** [platformio/platformio-atom-ide#1727] opened 2018-04-07 13:48 UTC
Error: Error: Failed to download file examples.tar.gz
    at ProjectExamplesStage.<anonymous> (/home/twade/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at Generator.throw (<anonymous>)
    at step (/home/twade/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:13:273)

**Comment by ivankravets** [comment] 2018-04-21 11:45
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1366

**Closed by ivankravets** 2018-04-21 11:45 UTC
