### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by zekageri** [platformio/platformio-atom-ide#1854] opened 2018-05-22 09:51 UTC
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\Hitec\.platformio\.cache\tmp-8100XqYdUMFRGqUw\virtualenv-15.2.0\virtualenv.py", line 2349, in <module>
    main()
  File "C:\Users\Hitec\.platformio\.cache\tmp-8100XqYdUMFRGqUw\virtualenv-15.2.0\virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "C:\Users\Hitec\.platformio\.cache\tmp-8100XqYdUMFRGqUw\virtualenv-15.2.0\virtualenv.py", line 953, in create_environment
    download=download,
  File "C:\Users\Hitec\.platformio\.cache\tmp-8100XqYdUMFRGqUw\virtualenv-15.2.0\virtualenv.py", line 904, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "C:\Users\Hitec\.platformio\.cache\tmp-8100XqYdUMFRGqUw\virtualenv-15.2.0\virtualenv.py", line 756, in call_subprocess
    "Error %s while executing command %s" % (e, cmd_desc))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 22: ordinal not in range(128)

**Comment by ivankravets** [comment] 2018-06-20 18:53
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1276

**Closed** 2018-06-20 18:53 UTC
