### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by mcfarlde** [platformio/platformio-atom-ide#1036] opened 2017-10-15 22:27 UTC
Error: Status 'PlatformIO: Rebuilding C/C++ Project Index for /Users/derek/Downloads/Sonoff-Tasmota-master' is already set
    at Registry.statusAdd (/Users/derek/.atom/packages/busy-signal/lib/registry.js:50:13)
    at /Users/derek/.atom/packages/busy-signal/lib/registry.js:31:12
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Provider.add (/Users/derek/.atom/packages/busy-signal/lib/provider.js:21:18)
    at beginBusy (/Users/derek/.atom/packages/platformio-ide/lib/services/busy.js:25:20)
    at ProjectIndexer.<anonymous> (/Users/derek/.atom/packages/platformio-ide/lib/project/indexer.js:158:7)
    at Generator.next (<anonymous>)
    at step (/Users/derek/.atom/packages/platformio-ide/lib/project/indexer.js:11:273)
    at /Users/derek/.atom/packages/platformio-ide/lib/project/indexer.js:11:443
    at ProjectIndexer.<anonymous> (/Users/derek/.atom/packages/platformio-ide/lib/project/indexer.js:11:99)

**Comment by ivankravets** [comment] 2017-10-17 12:21
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1013

**Closed by ivankravets** 2017-10-17 12:21 UTC
