### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by mraczka** [platformio/platformio-atom-ide#1511] opened 2018-02-11 21:57 UTC
Error: Traceback (most recent call last):
  File "c:\.platformio\penv\lib\site-packages\platformio\__main__.py", line 120, in main
    cli(None, None, None)
  File "c:\.platformio\penv\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\.platformio\penv\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\.platformio\penv\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\.platformio\penv\lib\site-packages\click\decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\.platformio\penv\lib\site-packages\platformio\commands\init.py", line 92, in cli
    init_base_project(project_dir)
  File "c:\.platformio\penv\lib\site-packages\platformio\commands\init.py", line 144, in init_base_project
    config = util.load_project_config(project_dir)
  File "c:\.platformio\penv\lib\site-packages\platformio\util.py", line 349, in load_project_config
    cp.read(path)
  File "C:\.platformio\python27\Lib\ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "C:\.platformio\python27\Lib\ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
MissingSectionHeaderError: File contains no section headers.
file: C:\Users\Micha�\Downloads\platformio.ini, line: 7
'<!DOCTYPE html>\n'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\.platformio\python27\Lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "c:\.platformio\penv\lib\site-packages\platformio\telemetry.py", line 364, in _finalize
    backup_reports(MPDataPusher().get_items())
  File "c:\.platformio\penv\lib\site-packages\platformio\telemetry.py", line 393, in backup_reports
    app.set_state_item("telemetry", tm)
  File "c:\.platformio\penv\lib\site-packages\platformio\app.py", line 298, in set_state_item
    data[name] = value
  File "c:\.platformio\penv\lib\site-packages\platformio\app.py", line 113, in __exit__
    json.dump(self._state, fp)
  File "C:\.platformio\python27\Lib\json\__init__.py", line 189, in dump
    for chunk in iterable:
  File "C:\.platformio\python27\Lib\json\encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "C:\.platformio\python27\Lib\json\encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "C:\.platformio\python27\Lib\json\encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "C:\.platformio\python27\Lib\json\encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "C:\.platformio\python27\Lib\json\encoder.py", line 390, in _iterencode_dict
    yield _encoder(value)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb3 in position 1017: invalid start byte
Error in sys.exitfunc:
Traceback (most recent call last):
  File "C:\.platformio\python27\Lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "c:\.platformio\penv\lib\site-packages\platformio\telemetry.py", line 364, in _finalize
    backup_reports(MPDataPusher().get_items())
  File "c:\.platformio\penv\lib\site-packages\platformio\telemetry.py", line 393, in backup_reports
    app.set_state_item("telemetry", tm)
  File "c:\.platformio\penv\lib\site-packages\platformio\app.py", line 298, in set_state_item
    data[name] = value
  File "c:\.platformio\penv\lib\site-packages\platformio\app.py", line 113, in __exit__
    json.dump(self._state, fp)
  File "C:\.platformio\python27\Lib\json\__init__.py", line 189, in dump
    for chunk in iterable:
  File "C:\.platformio\python27\Lib\json\encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "C:\.platformio\python27\Lib\json\encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "C:\.platformio\python27\Lib\json\encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "C:\.platformio\python27\Lib\json\encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "C:\.platformio\python27\Lib\json\encoder.py", line 390, in _iterencode_dict
    yield _encoder(value)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb3 in position 1017: invalid start byte

**Comment by ivankravets** [comment] 2018-02-17 16:30
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1485

**Closed by ivankravets** 2018-02-17 16:30 UTC
